/**
 * **English — dịch từ `vi.ts`** (23/09/2026).
 *
 * Sinh bằng `scripts/sinh-tep-ngon-ngu.py` để cấu trúc khoá **luôn khớp `vi.ts`**.
 * Sửa tay được, nhưng đừng thêm/bớt khoá ở đây — thêm ở `vi.ts` trước, vì
 * `check-i18n-keys.py` so mọi ngôn ngữ với tệp đó.
 *
 * Chỉ dịch GIAO DIỆN. Dữ liệu người dùng nhập (tên lớp, tên học viên, ghi chú)
 * giữ nguyên — xem `danhSach.ts`.
 */
const en = {
  chung: {
    tieuDeTab: 'LangCenter — Language center management',
    xacNhanLuu: 'Confirm save',
    xemChiTiet: 'View details',
    ghiChu: 'Note',
    dangPhatTrien: 'Module under development',
    dangPhatTrienGoiY: 'The permissions and navigation parts of this module are already working — you can grant access to groups right now. The detailed business features will be added later.',
    xacNhanThem: 'Confirm add',
    hoiLuu: 'Save changes for "{{ten}}"? The current information will be overwritten.',
    hoiThem: 'Add "{{ten}}"?',
    hoiLuuChung: 'Save changes?',
    hoiThemChung: 'Add this record?',
    dangTai: 'Loading…',
    tatCa: 'All',
    dongY: 'OK',
    luu: 'Save',
    huy: 'Cancel',
    them: 'Add',
    sua: 'Edit',
    xoa: 'Delete',
    timKiem: 'Search',
    thaoTac: 'Actions',
    khongCoDuLieu: 'No data yet',
    xacNhanXoa: 'Are you sure you want to delete?',
    dangXuat: 'Log out',
    quayLai: 'Back',
    dong: 'Close',
    moMenu: 'Open menu',
    moSidebar: 'Expand sidebar',
    thuGonSidebar: 'Collapse sidebar',
    daLuu: 'Saved',
    taiVe: 'Download',
    xem: 'View',
  },
  dangKy: {
    tieuDe: 'Register a center',
    moTa: 'Enter the center name and the system will issue a center code for you',
    nut: 'Create center',
    thanhCong: 'Center created successfully',
    maTrungTamCuaBan: 'Your center code',
    saoChep: 'Copy',
    giaiThichMa: 'The center code is 7 characters issued by the system and is used to log in.',
    canhBaoLuuMa: 'Write down the center code. You need it every time you log in and you cannot look it up yourself.',
    luuYDoiMatKhau: 'You will be asked to change your password at your first login.',
    chuaMo: 'Registration is not open',
    chuaMoMoTa: 'This system has not opened self-registration. Contact an administrator to have a center created.',
    veDangNhap: '← Back to login',
  },
  ngonNgu: {
    doi: 'Change language',
    nhan: 'Language',
  },
  linhVat: {
    tat: 'Hide mascot',
    thoai: [
      'Have a wonderful day of teaching and learning!',
      'Don\'t forget to save before you close the page.',
      'Coffee yet? A short break never hurts.',
      'How is class going today?',
      'Just off for a little walk — you carry on working.',
      'Tidy numbers today, an easier month-end tomorrow.',
      'Stuck on something? Just ask your administrator!',
      'Every lesson counts — teach well out there!',
    ],
  },
  dangNhap: {
    tieuDe: 'Log in',
    moTa: 'Enter your center code, username and password',
    maTrungTam: 'Center code',
    tenPhanMem: 'LangCenter',
    bannerTieuDe: 'Language center management system',
    bannerMoTa: 'Enter your center code to begin. Manage classes, students, attendance and tuition in one single system.',
    banQuyen: '© {{nam}} LangCenter · Software developed by GiapTex',
    banQuyenCoTen: '© {{nam}} {{ten}} · Software developed by GiapTex',
    maTrungTamGoiY: '7 characters, not case-sensitive',
    dangTraTenTrungTam: 'Looking up center code…',
    khongTimThayTrungTam: 'No matching center found',
    chuaCoTrungTam: 'No center yet?',
    username: 'Username',
    matKhau: 'Password',
    nut: 'Log in',
    nhoDangNhap: 'Remember center code and username',
    quenMatKhau: 'Forgot your password?',
    doiMatKhauTieuDe: 'Change password',
    doiMatKhauMoTa: 'Your account must change its password before entering the system',
    matKhauCu: 'Current password',
    matKhauMoi: 'New password',
    xacNhanMatKhau: 'Confirm new password',
    quenTieuDe: 'Forgot password',
    quenMoTa: 'Enter your registered email to receive a password reset code',
    email: 'Email',
    guiYeuCau: 'Send request',
    daGuiEmail: 'If the email exists in the system, a reset code has been sent to your inbox.',
    maDatLai: 'Reset code',
    datLaiMatKhau: 'Reset password',
  },
  menu: {
    tongQuan: 'Overview',
    daoTao: 'Training',
    nhanSu: 'Staff',
    khachHang: 'Customers',
    nhanVienKinhDoanh: 'Sales staff',
    giaoVienNhanSu: 'Teachers',
    nhanSuNguoiDung: 'Staff profiles',
    coCauToChuc: 'Organization structure',
    chucVu: 'Job titles',
    hocVien: 'Students',
    doanhThu: 'Revenue',
    khachHangDs: 'Customers',
    khoaHoc: 'Courses',
    sanPham: 'Products',
    lopHoc: 'Classes',
    choXepLop: 'Awaiting class placement',
    taiLieu: 'Documents',
    khoaOnline: 'Online courses',
    thongKeCrm: 'Statistics',
    hocPhi: 'Tuition',
    quanTri: 'System administration',
    taiKhoan: 'Accounts',
    nguoiDung: 'People',
    phanQuyen: 'Permissions',
    thietLap: 'General settings',
    nhatKy: 'System log',
  },
  hocPhi: {
    hoiThu: 'Record a payment of {{soTien}}? The student\'s outstanding balance will decrease accordingly.',
    hoiSua: 'Change this payment to {{soTien}}? The outstanding balance will be recalculated from the new amount.',
    tabCongNo: 'Outstanding balance',
    tabSoThu: 'Receipt book',
    thuTien: 'Collect payment',
    suaKhoanThu: 'Edit payment',
    xoaKhoanThu: 'Delete payment',
    xacNhanXoa: 'Delete the {{soTien}} payment from {{hocVien}}? The outstanding balance will increase accordingly.',
    lop: 'Class',
    tatCaLop: 'All classes',
    chonLop: 'Select a class',
    hocVien: 'Student',
    chonHocVien: 'Select a student',
    hocPhi: 'Tuition',
    daThu: 'Collected',
    tongPhaiThu: 'Total receivable',
    tienDoThu: 'Collection progress',
    khongCoQuyenXem: 'You do not have permission to view tuition information. Only administrators can track tuition for a whole class; students can see their own outstanding balance.',
    conNo: 'Outstanding',
    conNoNhan: 'Outstanding',
    daDuUpper: 'Paid in full',
    quaHan: 'Overdue',
    chiConNo: 'Show only people with a balance',
    khongCoCongNo: 'No outstanding balance matches the filter',
    chuaCoKhoanThu: 'No payment recorded yet',
    soTien: 'Amount',
    ngayThu: 'Payment date',
    phuongThuc: 'Method',
    soPhieu: 'Receipt number',
    ghiChu: 'Note',
    nguoiThu: 'Collected by',
    pt: {
      TienMat: 'Cash',
      ChuyenKhoan: 'Bank transfer',
      Khac: 'Other',
    },
  },
  nguoiDung: {
    gomPhongCon: 'Include sub-departments',
    themNguoiDung: 'Add person',
    suaNguoiDung: 'Edit person',
    timTheo: 'Full name, email, phone',
    trangThaiNhanSu: 'Staff',
    DangLamViec: 'Active',
    DaNghi: 'Left',
    hoSo: 'Profile',
    hoSo_GiaoVien: 'Teacher profile',
    hoSo_HocVien: 'Student profile',
    hoSo_NhanVien: 'Staff profile',
    bangCap: 'Qualifications',
    chuyenMon: 'Specialization',
    ngayVaoLam: 'Start date',
    truongLop: 'School / grade',
    khachHangCrm: 'Customer (CRM)',
    khachHangCrmChon: 'Select an existing customer…',
    khachHangCrmGoiY: 'Optional — link this profile to a customer who already bought in CRM so the same person is not duplicated.',
    tenPhuHuynh: 'Parent name',
    sdtPhuHuynh: 'Parent phone',
    chucVu: 'Job title',
    chuaGanChucVu: 'No job title assigned',
    ngaySinh: 'Date of birth',
    diaChi: 'Address',
    cccd: 'ID card number',
    soTaiKhoan: 'Bank account number',
    tenNganHang: 'Bank',
    lienKetMxh: 'Social media links',
    duongDanMxh: 'Link or phone number…',
    themMxh: 'Add link',
    tepHoSo: 'Profile files',
    taiTep: 'Upload file',
    chuaCoTep: 'No files yet — contracts, scanned qualifications, scanned ID card…',
    gioiHanTep: 'PDF, Word and Excel only · maximum 20 MB per file',
    soTepDaDung: '{{so}}/{{toiDa}} files used',
    datTenTep: 'Name the file',
    doiTenTep: 'Rename file',
    tenHienThi: 'Display name',
    viDuTenTep: 'E.g. Employment contract 2026',
    giuDuoiTep: 'No need to type the file extension — the system keeps it automatically (.pdf, .docx…)',
    hoiXoaTep: 'Delete the file "{{ten}}"? This cannot be undone.',
    phongBan: 'Department',
    chuaXepPhongBan: 'Not placed in the organization structure',
    taiKhoan: 'Account',
    chuaCoTaiKhoan: 'None',
    nguoiSoHuu: 'Person',
    khongGanAi: 'Not linked to anyone',
    taoTaiKhoanDangNhap: 'Create a login account',
    khongCanDangNhap: 'This person will not be able to log in. You can create an account for them later on the Accounts tab.',
    giaiThichGanNguoi: 'Leave empty if this is a technical account that belongs to no one.',
    hoiXoa: 'Delete the person "{{ten}}"? This cannot be undone. If they already have data, mark them as "Left" instead of deleting.',
    giaiThichVoHieuHoa: 'Deactivating only blocks login. This person\'s profile and all their data stay intact.',
  },
  nhatKy: {
    timTheo: 'Command name, performed by',
    module: 'Module',
    hanhDong: 'Action',
    thoiDiem: 'Time',
    nguoiThucHien: 'Performed by',
    thaoTac: 'Command',
    soBanGhi: 'Record',
    ketQua: 'Result',
    thanhCong: 'Success',
    thatBai: 'Failure',
    chiThatBai: 'Show only failed operations',
    khongCoBanGhi: 'No operation has been recorded yet',
    xemChiTiet: 'View details',
    truongDaDoi: 'Changed fields',
    thamSo: 'Command parameters',
    diaChiIp: 'IP',
  },
  hanhDongNhatKy: {
    Them: 'Create',
    Sua: 'Update',
    Xoa: 'Delete',
    XacThuc: 'Authentication',
    Khac: 'Other',
  },
  thongKe: {
    loaiThongKe: 'Break down by',
    kyMacDinh: 'Default period',
    khoangSai: 'The from date must be on or before the to date.',
    loai: {
      KhoaHoc: 'Course',
      SanPham: 'Product',
      Elearning: 'Online learning',
      DoiNhom: 'Team',
    },
    loaiMoTa: {
      KhoaHoc: 'Revenue from each course sold.',
      SanPham: 'Revenue from each product — books, learning materials.',
      Elearning: '',
      DoiNhom: 'Revenue per department, based on who created the customer profile.',
    },
    locTheo: {
      KhoaHoc: 'Only these courses',
      SanPham: 'Only these products',
      Elearning: '',
      DoiNhom: 'Only these teams',
    },
    boLoc: 'Clear filter',
    dangLoc: 'Filtering {{so}} items — every figure on this screen counts only the selected ones.',
    elearningMoTa: 'Measures volume only, not money: online courses are not linked to orders — administrators grant access manually.',
    chuaCoKhoaMo: 'No online course is open yet. Courses in Draft status are not counted here — once the lessons are ready, switch them to "Open".',
    elearningGoiY: 'The learning figures are in the row above. E-learning revenue does not exist by design.',
    soKhoaOnline: 'Open courses',
    soNguoiHoc: 'Active learners',
    soLuotGhiDanh: 'Enrollments',
    tyLeHoanThanh: 'Completion rate',
    baiTrenTong: '{{da}}/{{tong}} lessons',
    tongDoanhThu: 'Total revenue',
    soDon: 'Orders',
    giaTriDonTb: 'Average order value',
    daThu: 'Collected',
    conThieu: '{{so}} still owed',
    thuDu: 'Paid in full',
    soKyTruoc: 'vs. previous period',
    chuaCoKyTruoc: 'no previous period to compare',
    soDonNgan: '{{so}} orders',
    khongXacDinh: 'Unspecified',
    chuaCoDon: 'No orders in this period yet',
    chuaCoKhach: 'No customers yet',
    doanhThuTheoThang: 'Revenue by month',
    doanhThuTheoThangMoTa: 'Converted to VND at the exchange rate captured at registration — past reports never change.',
    theoCaNhan: 'Revenue by individual',
    theoCaNhanMoTa: 'Counted for whoever created the customer profile. Older orders with no creator are grouped under "Unspecified".',
    theoDoiNhom: 'Revenue by team',
    theoDoiNhomMoTa: 'Based on the department of whoever created the customer profile.',
    theoSanPham: 'Revenue by item',
    theoSanPhamMoTa: 'Includes both courses and other products.',
    theoNguon: 'Revenue by customer source',
    theoNguonMoTa: 'Self-registered customers do not count towards anyone\'s personal sales.',
    pheu: 'Sales funnel',
    pheuMoTa: 'How many customers are at each stage, and the share of all customers.',
  },
  nguonKhachHang: {
    NhanVienTao: 'Created by staff',
    TuDangKy: 'Self-registered',
  },
  khoaOnline: {
    ten: 'Course name',
    trangThai: 'Status',
    moTa: 'Description',
    chuaCo: 'No online courses yet',
    chuaCoBai: 'This course has no lessons yet',
    chuaCoHocVien: 'No one has been granted access yet',
    themKhoa: 'Add online course',
    suaKhoa: 'Edit course',
    soBaiHoc: 'Lessons',
    soHocVien: 'Students',
    tienDo: 'Progress',
    taoRaLaNhap: 'A new course always starts as a Draft — once the lessons are ready, switch it to Open.',
    dangNhapGoiY: 'This course is still a Draft, so students cannot see it and access cannot be granted yet. Once the lessons are ready, edit the course and switch it to Open.',
    tabBaiHoc: 'Lessons',
    tabHocVien: 'Students',
    themBai: 'Add lesson',
    suaBai: 'Edit lesson',
    xoaBai: 'Delete lesson',
    xoaBaiHoi: 'Delete the lesson "{{ten}}"? Students\' progress on this lesson is lost with it.',
    tieuDeBai: 'Lesson title',
    thuTu: 'Order',
    noiDung: 'Content',
    baiTrong: 'This lesson has no content yet.',
    congKhai: 'Public',
    congKhaiGoiY: 'Anyone logged in can read it without enrollment — even after access expires. Use it for intro or sample lessons.',
    danhDauDaHoc: 'Mark as completed',
    capQuyen: 'Grant access',
    hoiTaoKhoa: 'Create this online course? The new course starts as a Draft and no one can see it yet.',
    hoiLuuKhoa: 'Save changes to this course?',
    hoiLuuBai: 'Save this lesson?',
    hoiCapQuyen: 'Grant access to this course for the selected students?',
    thuQuyen: 'Revoke access',
    thuQuyenHoi: 'Revoke {{ten}}\'s access? Their progress is kept, so they can continue if access is granted again.',
    hocVien: 'Student',
    hetHan: 'Expires',
    hetHanGoiY: 'Leave empty = lifetime access.',
    ghiChuCap: 'Note',
    ghiChuVd: 'E.g. bought in order #123, trial, bundled with IELTS class',
    nguoiCap: 'Granted by',
    vinhVien: 'Lifetime',
  },
  trangThaiKhoaOnline: {
    Nhap: 'Draft',
    DangMo: 'Open',
    NgungCapMoi: 'Closed to new access',
  },
  tongQuan: {
    viecCanLam: 'To do',
    khongCoViec: 'Nothing needs your attention',
    buoiHomNay: 'Today\'s sessions',
    buoiSapToi: 'Upcoming sessions',
    buoiThu: 'Session {{so}}',
    lopDangHoatDong: 'Active classes',
    buoiQuaHan: 'Past sessions with attendance not finalized',
    baiChuaCham: 'Ungraded submissions',
    choXepLop: 'Students awaiting class placement',
    chuaCoNoiDung: 'The system is in its baseline state — no business features have been configured yet. Start by creating accounts and permission groups for your center.',
  },
  phanTrang: {
    dangXem: 'Showing {{tu}}–{{den}} of {{tong}}',
    soDong: 'Rows',
    trangTruoc: 'Previous page',
    trangSau: 'Next page',
  },
  anh: {
    chonAnh: 'Choose image',
    doiAnh: 'Change image',
    goAnh: 'Remove image',
    goiY: 'JPG, PNG, WebP or GIF · maximum 5 MB',
  },
  loaiNguoiDung: {
    NhanVien: 'Other staff',
    NhanVienKinhDoanh: 'Sales staff',
    GiaoVien: 'Teacher',
    TroGiang: 'Teaching assistant',
    HocVien: 'Student',
  },
  lopHoc: {
    hoiThemHocVien: 'Enroll {{soLuong}} students in this class?',
    hoiGoHocVien: 'Remove "{{ten}}" from the class? Recorded attendance and tuition are kept.',
    tieuDe: 'Classes',
    themMoi: 'Add class',
    ten: 'Class name',
    giaoVienChinh: 'Lead teacher',
    troGiang: 'Teaching assistant',
    hinhThuc: 'Learning mode',
    phongHoc: 'Classroom',
    linkHoc: 'Online class link',
    hocPhi: 'Tuition',
    sucChuaToiDa: 'Maximum capacity',
    khongGioiHan: 'Unlimited',
    ngayKhaiGiang: 'Start date',
    ngayKetThuc: 'End date',
    trangThai: 'Status',
    ghiChu: 'Note',
    soHocVien: 'Students',
    hocVien: 'Students in class',
    xemThongTin: 'View information',
    hocVienCuaLop: 'Students of class {{lop}}',
    nhanVienKinhDoanh: 'Sales staff',
    themTrucTiep: 'Or add existing students',
    themTrucTiepGiaLop: 'The applied tuition is taken from the class standard rate',
    themHocVien: 'Add students',
    goHocVien: 'Remove from class',
    hocPhiApDung: 'Applied tuition',
    ngayVaoLop: 'Joined on',
    hoanTat: 'Finalize class',
    huyLop: 'Cancel class',
    xacNhanHuy: 'Cancel this class? Attendance history and tuition are kept.',
    chuaCoLop: 'No classes yet',
    chonGiaoVien: 'Select a teacher…',
    timGiaoVien: 'Type a teacher\'s name to search…',
    khoaHocCuaLop: 'Courses taught by this class',
    chuaGanKhoa: 'No course assigned',
    toiDaNKhoa: '(maximum {{so}})',
    chonKhoaHoc: 'Select a course...',
    timKhoaHoc: 'Search courses',
    daDatToiDaKhoa: 'Maximum of {{so}} courses reached',
    chonTroGiang: 'Select a teaching assistant…',
    timTroGiang: 'Type an assistant\'s name to search…',
    timHocVien: 'Type a student\'s name to search…',
    locTrangThai: 'Filter by status',
    nhapGoiY: 'A draft class is visible only to you. Click "Finalize class" to publish it.',
    xemChiTiet: 'View details',
    siSo: 'Class size',
    buoiDaHoc: 'Sessions held',
    thoiGian: 'Time',
    tabLichTatCa: 'Schedule',
    locTheoLop: 'Filter by class',
    lichTuNgay: 'From',
    lichDenNgay: 'To',
    lichXoaLoc: 'Clear filter',
    dangLocKhoangNgay: 'Filtering by a date range — the calendar\'s month buttons do not change the data. Clear the filter to browse by month again.',
    tabDanhSach: 'Class list',
    tabTongQuan: 'Overview',
    tabHocVien: 'Students',
    tabLich: 'Schedule & attendance',
    tabBaiTap: 'Assignments',
    tabHocPhi: 'Tuition',
    tabTaiLieu: 'Documents',
    suaThongTin: 'Edit class information',
    luuThongTin: 'Save class information',
    daChon: '{{soLuong}} selected',
    sucChuaConLai: '{{daChon}} selected / maximum {{toiDa}}',
  },
  hinhThucHoc: {
    ChuaChon: '— Select —',
    Online: 'Online',
    Offline: 'In class',
    KetHop: 'Hybrid',
  },
  trangThaiLopHoc: {
    Nhap: 'Draft',
    SapKhaiGiang: 'Starting soon',
    DangHoc: 'In progress',
    DaKetThuc: 'Finished',
    DaHuy: 'Cancelled',
  },
  trangThaiHocVien: {
    DangHoc: 'Studying',
    BaoLuu: 'On hold',
    ChuyenLop: 'Transferred',
    DaNghi: 'Dropped out',
  },
  lich: {
    thang: 'Month',
    tuan: 'Week',
    danhSach: 'List',
    homNay: 'Today',
    truoc: 'Previous period',
    sau: 'Next period',
    kieuBang: 'Table',
    kieuLich: 'Calendar',
  },
  chiTietBuoi: {
    tabThongTin: 'Session information',
    tabDiemDanh: 'Attendance',
    tabNhanXet: 'Feedback',
    tabBaiTap: 'Assignments',
    tabTaiLieu: 'Documents',
    quayLaiLich: 'Back to schedule',
    buoiTruoc: 'Previous session',
    buoiSau: 'Next session',
    chonBuoi: 'Select another session',
    khongTimThayBuoi: 'Session not found',
    taiLieuTheoLop: 'Documents are attached to the whole class, not to individual sessions — these are the class\'s shared documents.',
  },
  nhanXetBuoi: {
    tieuDe: 'Student feedback on the session',
    cuaToi: 'My feedback',
    noiDung: 'Content',
    noiDungGoiY: 'How was today\'s session? What could be improved?',
    mucHaiLong: 'Overall satisfaction',
    theoTieuChi: 'Rate by criteria (scale of 5)',
    khongChon: 'No rating',
    chamNguoiDungLop: 'Rate the person leading the class',
    vaiTro: {
      GiaoVien: 'Teacher',
      TroGiang: 'Teaching assistant',
    },
    chuaChonDiem: 'Not rated',
    boChon: 'Click the selected level again to clear the rating',
    khongCoTieuChi: 'The center has not configured any teaching evaluation criteria. Contact an administrator to add them under Evaluation criteria (HRM).',
    diemDaCham: 'Rating given',
    chamChung: 'Rate the session as a whole',
    gui: 'Submit feedback',
    capNhat: 'Update feedback',
    hoiGui: 'Submit feedback on this session?',
    hoiCapNhat: 'Update the feedback you already submitted? The previous content will be overwritten.',
    daGui: 'Feedback submitted',
    chuaCo: 'No feedback for this session yet',
    nhanXetHocVien: 'Student feedback',
    nhanXetGiaoVien: 'Teacher feedback on students',
    chuaCoNhanXetGv: 'The teacher has not commented on any student in this session',
    ghiONhanXetGv: 'Teacher comments are recorded on the Attendance tab, per student.',
    giaiThichChoGv: 'The feedback section here is the students\' own channel for commenting on the session, so only students currently studying in the class can post. To comment on individual students, open the Attendance tab — each student has their own comment box.',
  },
  buoiHoc: {
    hoiSinhLich: 'Generate the schedule with the selected frequency?',
    hoiSinhThem: 'Add sessions to the current schedule? No session will be deleted.',
    hoiSinhLai: 'Regenerating will DELETE all sessions not yet held and create a new schedule. Finalized sessions are kept. Continue?',
    hoiChotBuoi: 'Finalize this session? Anyone not marked will be recorded as Absent, and once finalized the time can no longer be changed and the session can no longer be cancelled or deleted.',
    thuTuNgan: 'Session {{n}}',
    sinhThemBuoi: 'Add sessions',
    xoaBuoi: 'Delete session',
    doiTrangThai: 'Change status',
    moTaDoiTrangThai: 'Session {{thuTu}} — {{gio}}. Choose a new status:',
    dangApDung: 'currently applied',
    laHocBu: 'This is a make-up session',
    macDinhTheoLop: 'Leave empty = same as class',
    tuNgay: 'Generate from',
    daChot: '{{soLuong}} sessions finalized',
    goiYSinhThem: 'Adds sessions to the current schedule — nothing is deleted and new sessions continue the numbering. Set the number of sessions to 1 if you only need one (make-up or revision session).',
    canhBaoSinhLai: 'Regenerating will DELETE all sessions not yet held and create a new schedule. Finalized sessions are kept.',
    xacNhanSinhLai: 'Delete {{soLuong}} sessions not yet held and generate a new schedule? {{daChot}} finalized sessions are kept. To add sessions without losing the current schedule, use "Add sessions" or "Generate extra sessions" instead.',
    xacNhanHuyBuoi: 'Cancel session {{thuTu}} ({{gio}})? The record is kept so the history stays intact.',
    xacNhanXoaBuoi: 'Permanently delete session {{thuTu}} ({{gio}})? This cannot be undone. If the session already took place, cancel it instead of deleting it.',
    tieuDe: 'Sessions',
    lich: 'Schedule',
    thuTu: 'Session',
    thoiGian: 'Time',
    giaoVien: 'Teacher',
    giaoVienRieng: 'Session teacher',
    phongHoc: 'Classroom',
    linkHoc: 'Online class link',
    ghiChu: 'Note',
    troGiang: 'Teaching assistant',
    troGiangTheoLop: 'The class\'s teaching assistant — no separate assistant assigned to this session.',
    theoLop: '(same as class)',
    khongCoTroGiang: 'The class has no teaching assistant',
    hocBu: 'Make-up',
    hocOnline: 'Online session',
    nhom: {
      sapToi: 'Upcoming',
      daQua: 'Past',
    },
    trangThai: 'Status',
    diemDanh: 'Attendance',
    chuaCoLich: 'The class has no schedule yet',
    sinhLich: 'Generate schedule',
    sinhLaiLich: 'Regenerate schedule',
    thuTrongTuan: 'Days of the week',
    gioBatDau: 'Start time',
    gioKetThuc: 'End time',
    ketThucTheo: 'End by',
    theoSoBuoi: 'Number of sessions',
    theoNgay: 'End date',
    ngayLoaiTru: 'Days off (no class)',
    ngayLoaiTruGoiY: 'One date per line, in the format 2026-04-30',
    xemTruoc: 'Preview schedule',
    daSinh: '{{soLuong}} sessions will be generated',
    huyBuoi: 'Cancel this session',
    chotBuoi: 'Finalize session',
    chotBuoiGoiY: 'Anyone not marked will be recorded as Absent.',
    tuDiemDanh: 'Quick attendance',
  },
  diemDanh: {
    hoiLuu: 'Save attendance for {{soLuong}} students?',
    tieuDe: 'Attendance',
    hocVien: 'Student',
    tuKhai: 'Student self-reported',
    chinhThuc: 'Official',
    lyDoVang: 'Reason for absence',
    thieuLyDoVang: 'No reason for absence entered for {{soLuong}} students: {{ten}}. Enter a reason and save, or use "Finalize session" to record them as "Not marked".',
    thieuLyDoNgan: 'Some absent students still have no reason',
    nguon: 'Source',
    chuaGhiNhan: 'Not recorded',
    khacTuKhai: 'Differs from self-report',
    luu: 'Save attendance',
    daLuu: 'Attendance saved',
    chiXem: 'You only have permission to view this attendance sheet.',
    nhanXetGv: 'Teacher\'s comment',
    nhanXetGoiY: 'Pronunciation, participation, homework…',
    buoiDaChot: 'Session finalized — attendance and comments can still be edited, but the session time cannot.',
  },
  trangThaiDiemDanh: {
    CoMat: 'Present',
    Vang: 'Absent',
    DiMuon: 'Late',
    VangCoPhep: 'Excused absence',
  },
  nguonDiemDanh: {
    HocVienTuKhai: 'Student self-reported',
    GiaoVien: 'Teacher',
    QuanTri: 'Administrator',
  },
  trangThaiBuoiHoc: {
    DaLenLich: 'Scheduled',
    DaHoanThanh: 'Completed',
    DaHuy: 'Cancelled',
    ChuyenLich: 'Rescheduled',
  },
  tinhTrangBuoi: {
    ChuaBatDau: 'Not started',
    DangDienRa: 'In progress',
    ChuaChot: 'Not finalized',
    DaXong: 'Done',
    ChuyenLich: 'Rescheduled',
    DaHuy: 'Cancelled',
  },
  thu: {
    Monday: 'Mon',
    Tuesday: 'Tue',
    Wednesday: 'Wed',
    Thursday: 'Thu',
    Friday: 'Fri',
    Saturday: 'Sat',
    Sunday: 'Sun',
  },
  hocLieu: {
    luuDiem: 'Save grades',
    daSuaChuaLuu: '{{soLuong}} submissions edited, not saved',
    hoiLuuDiem: 'Save grades and comments for {{soLuong}} submissions?',
    hoiXoaBaiTap: 'Delete the assignment "{{ten}}"? Student submissions are lost with it.',
    baiTap: 'Assignments',
    taiLieu: 'Documents',
    themBaiTap: 'Assign homework',
    themTaiLieu: 'Add document',
    tieuDe: 'Title',
    moTa: 'Description',
    hanNop: 'Due date',
    buoiHoc: 'Session',
    loai: 'Category',
    ganLop: 'Attach to class',
    ganLopGoiY: 'Leave empty = shared document for the whole center',
    lopChung: 'Shared',
    tep: 'Attachments',
    themTep: 'Add file',
    keoThaTep: 'Choose a file (PDF, Word, Excel, image — maximum 20 MB)',
    daNop: 'Submitted',
    chuaCoBaiTap: 'No assignments yet',
    chuaCoTaiLieu: 'No documents yet',
    xemBaiNop: 'View submissions',
    lanNop: 'Attempt',
    thoiDiemNop: 'Submitted at',
    diem: 'Grade',
    nhanXet: 'Comment',
    cham: 'Grade',
    nguoiTaiLen: 'Uploaded by',
  },
  trangThaiBaiNop: {
    DaNop: 'Submitted',
    NopMuon: 'Submitted late',
    DaCham: 'Graded',
  },
  loaiTaiLieu: {
    GiaoTrinh: 'Coursebook',
    BaiGiang: 'Lecture',
    ThamKhao: 'Reference',
    DeThi: 'Exam paper',
    Khac: 'Other',
  },
  taiKhoan: {
    tieuDe: 'User accounts',
    username: 'Username',
    hoTen: 'Full name',
    ngaySinh: 'Date of birth',
    loaiNguoiDung: 'Role',
    email: 'Email',
    soDienThoai: 'Phone number',
    diaChi: 'Address',
    quyen: 'Permission group',
    trangThai: 'Status',
    hoatDong: 'Active',
    voHieuHoa: 'Disabled',
    themMoi: 'Add account',
    suaTieuDe: 'Update account',
    datLaiMatKhau: 'Reset password',
    canDoiMatKhau: 'Password change required',
    wizardGoiY: 'Select a permission group if one already exists',
    chonQuyen: 'Select a permission group…',
    timQuyen: 'Type a permission group name to search…',
    buocDoiMk: 'Require a password change at first login',
    buocDoiMkGoiY: 'Recommended: if you set the password for them, you know it too.',
    datLaiGoiY: 'The user will be asked to change it again at their next login.',
    matKhau: 'Password',
    matKhauMoi: 'New password',
    themTaiKhoan: 'Add account',
    suaTaiKhoan: 'Update account',
    buocDoiMatKhau: 'Require a password change at first login',
    phaiDoiMatKhau: 'Password change required',
    hoiXoa: 'Delete the account "{{ten}}"? The person\'s profile is kept; only their way to log in is removed.',
    hoiDatLaiMatKhau: 'Reset the password for "{{ten}}"? They will have to change it again at their next login, and the old password stops working immediately.',
    HoatDong: 'Active',
    VoHieuHoa: 'Disabled',
  },
  quyen: {
    hoiLuu: 'Save the permission group "{{ten}}"? The permissions of every account in the group change immediately.',
    tieuDe: 'Access permissions',
    tenQuyen: 'Permission group name',
    moTa: 'Description',
    soTaiKhoan: 'Accounts',
    themMoi: 'Add permission group',
    suaTieuDe: 'Edit permission group',
    maTran: 'Permission matrix',
    chucNang: 'Feature',
    soO: 'Permission cells',
    cauHinh: 'Configure permissions',
    taoVaCauHinh: 'Create and configure permissions',
    themMoiGoiY: 'Name the group first; in the next step you choose permissions, with role templates so you do not have to tick everything from scratch.',
    batDauTuMau: 'Start from a role template',
    apMauTieuDe: 'Apply a role template',
    apMauHoi: 'Replace all currently selected permissions with the permission set of "{{ten}}" ({{so}} cells)? You can still fine-tune each cell afterwards.',
    dangDung: '{{so}} accounts are using it',
    tongDaChon: '{{so}} cells selected',
    chiXem: 'You do not have the Configure permission matrix right, so this is view-only. Contact a system administrator if changes are needed.',
    khongThayNhom: 'This permission group was not found. It may have been deleted.',
    veDanhSach: 'Back to permission groups',
    canNhac: {
      DiemDanh: {
        Chot: 'Closes the attendance sheet and records Absent for everyone who did not report. This cannot be undone.',
      },
      XepLop: {
        Duyet: 'Decides on behalf of the sales side and affects their orders. This cannot be reversed.',
      },
      LopHoc: {
        HoanTat: 'The class leaves draft status and becomes visible to everyone involved. One-way.',
        Huy: 'Cancels the class and all of its sessions. The data remains but the class stops running.',
      },
      BuoiHoc: {
        Huy: 'Cancels the session; students see it as cancelled on their schedule.',
      },
      PhanQuyen: {
        CauHinhQuyen: 'Anyone with this right can grant EVERY other permission to their own group. Give it to administrators only.',
      },
      DoiMatKhauNguoiKhac: {
        Sua: 'Resets other people\'s passwords, which means being able to log into their accounts.',
      },
      DoanhThu: {
        ThuTien: 'Confirms that money was received from a customer. Best kept separate from whoever creates the order.',
      },
      HocPhi: {
        ThuTien: 'Records a student\'s payment in the tuition book.',
      },
      ThietLapChung: {
        CauHinhTien: 'Changes the payment details (bank transfer QR code) that customers will pay into.',
      },
      NhanXetBuoiHoc: {
        Xem: 'Reads EVERYONE\'s feedback on a session. Do not grant it to students — they would read their classmates\' private feedback.',
      },
      LopHocToanTrungTam: {
        Xem: 'Sees every class in the center, together with the profiles and contact details of the students in them — not just the classes they are in charge of.',
        Sua: 'Can also edit classes they are not in charge of.',
      },
      chung: {
        Chot: 'Closes the book — nothing can be edited afterwards.',
        Duyet: 'A decision that cannot be reversed.',
        ThuTien: 'An operation involving money.',
        Huy: 'Cancels but keeps the record.',
      },
    },
    phamViDuLieu: 'Data scope',
    phamViGoiY: 'These permissions do not unlock more features; they widen the data a user can see. Not granted: they see only the classes they are in charge of. Granted: they see every class in the center, together with the profiles and contact details of the students in them.',
    oCu: 'This group still holds permissions that are no longer in the catalog: {{ds}}. Saving keeps them, but they have no effect — contact a system administrator if they should be cleaned up.',
  },
  hanhDong: {
    Xem: 'View',
    Them: 'Create',
    Sua: 'Edit',
    Xoa: 'Delete',
    Duyet: 'Approve / reject',
    Chot: 'Close the book',
    Huy: 'Cancel',
    SinhLich: 'Generate schedule',
    ThuTien: 'Collect payment',
    Cham: 'Grade',
    TuLam: 'Do it myself (own records)',
    DocTep: 'Read attachments',
    QuanLyTep: 'Upload / delete files',
    CauHinhTien: 'Configure payments',
    CauHinhQuyen: 'Configure the permission matrix',
    HoanTat: 'Finalize class creation',
    XepNhanSu: 'Assign staff to departments',
    GuiXepLop: 'Send class placement requests',
  },
  tieuChi: {
    them: 'Add criterion',
    sua: 'Edit criterion',
    ten: 'Criterion name',
    moTa: 'Hint for the rater',
    nhomLabel: 'Group',
    chuaCo: 'No criteria yet',
    soLanDaCham: 'Times rated',
    hoiLuu: 'Save this criterion?',
    giaiThich: 'Criteria are rated on a scale of 5. The Sales group is rated by managers each monthly period; the Teaching group is rated by students in each session.',
    khongDoiNhom: 'This criterion already has ratings, so its group cannot be changed.',
    ngungDungGoiY: 'Untick to stop using it — it no longer appears on new forms, while old forms remain readable. A criterion that has been rated cannot be deleted because that would distort every period already evaluated.',
    nhom: {
      KinhDoanh: 'Sales staff',
      GiangDay: 'Teachers / teaching assistants',
    },
    nhomMoTa: {
      KinhDoanh: 'rated by managers each monthly period',
      GiangDay: 'rated by students in each session',
    },
  },
  thongKeNs: {
    tabKinhDoanh: 'Sales',
    tabGiaoVien: 'Teachers',
    tabTroGiang: 'Teaching assistants',
    hoTen: 'Full name',
    soHocVien: 'Students',
    soLop: 'Classes',
    soBuoiDayDu: 'Sessions taught in full',
    soBuoiHuy: 'Cancelled sessions',
    chatLuongChamSoc: 'Customer care quality',
    chatLuongGiangDay: 'Teaching quality',
    soPhieu: '{{so}} forms',
    soLopNgan: '{{so}} classes',
    cham: 'Rate',
    chamTieuDe: 'Rate a sales staff member',
    ky: 'Evaluation period',
    kyGoiY: 'One form per staff member per period — rating again edits the existing form.',
    nhanXet: 'Manager\'s comment',
    hoiLuuPhieu: 'Save the evaluation form for {{ten}}, period {{ky}}?',
    xepHangDoanhThu: 'Ranking by revenue',
    xepHangHocVien: 'Ranking by number of students',
    xepHangHocVienMoTa: 'Customers this person brought in who actually started studying.',
    xepHangBuoiDay: 'Ranking by sessions taught in full',
    xepHangChatLuong: 'Ranking by teaching quality',
    xepHangChatLuongMoTa: 'Average score given by students for each session.',
    chuaCoNhanVienKd: 'No sales staff yet.',
    chuaCoNguoi: 'No one holds this role yet.',
    chuaCoHocVien: 'No customer started studying in this period.',
    chuaCoBuoi: 'No session was completed in this period.',
    chuaCoDanhGia: 'No evaluation in this period yet.',
    chuaCoTieuChiKd: 'No criteria in the Sales group yet — add them on the Evaluation criteria tab before you can rate.',
    chuaCoTieuChiGd: 'No criteria in the Teaching group yet — add them on the Evaluation criteria tab so students can give detailed ratings.',
  },
  chucNang: {
    TaiKhoan: 'Login accounts',
    HoSoNguoiDung: 'Person profiles',
    LopHoc: 'Classes',
    GhiDanhLop: 'Enrolling students in classes',
    XepLop: 'Class placement from CRM',
    BuoiHoc: 'Sessions',
    DiemDanh: 'Attendance',
    NhanXetBuoiHoc: 'Session feedback',
    BaiTap: 'Assignments',
    BaiNopBaiTap: 'Student submissions',
    BaiKiemTra: 'Tests',
    BaiLamKiemTra: 'Student test papers',
    KhoaOnline: 'Online courses (content authoring)',
    GhiDanhKhoaOnline: 'Granting access to online courses',
    HocOnline: 'Online learning',
    TaiLieu: 'Documents',
    HocPhi: 'Tuition',
    ThongKe: 'Statistics',
    LopHocToanTrungTam: 'All classes in the center',
    NhatKyHeThong: 'System log',
    PhanQuyen: 'Permissions',
    ThietLapChung: 'General settings',
    Anh: 'Images (logo, cover, QR code)',
    DoiMatKhauNguoiKhac: 'Changing other people\'s passwords',
    NhanSu: 'Staff',
    ChucVu: 'Job titles',
    PhongBan: 'Departments',
    TieuChiDanhGia: 'Evaluation criteria',
    ThongKeNhanSu: 'Staff statistics',
    DoanhThu: 'Revenue',
    ThongKeDoanhThu: 'Revenue statistics',
    KhachHang: 'Customers',
    ChamSocKhachHang: 'Customer care',
    KhoaHoc: 'Courses',
    SanPham: 'Products',
  },
  heThong: {
    Hrm: 'HRM — Staff',
    Crm: 'CRM — Customers',
    Lms: 'LMS — Training',
    DungChung: 'Shared across all three systems',
    chuyenHeThong: 'Switch system',
    dungChungGoiY: 'These administrative features are shared by all three systems, so they appear on every tab.',
  },
  hrm: {
    moTaNvkd: 'Sales staff profile: targets, assigned customers, commission.',
    moTaGiaoVien: 'Teachers from the staff point of view: contract, salary, timekeeping. This is the same person as the teacher in LMS, only the tracked information differs.',
  },
  phuongThucThanhToan: {
    TienMat: 'Cash',
    ChuyenKhoan: 'Bank transfer',
    Khac: 'Other',
  },
  donViTien: {
    VND: 'VND — Vietnamese dong',
    USD: 'USD — US dollar',
    EUR: 'EUR — Euro',
    CAD: 'CAD — Canadian dollar',
  },
  crmLoc: {
    locThem: 'More filters',
    xoaLoc: 'Clear filters',
    doiNhom: 'Team',
    chuaCoTag: 'No department has been tagged as Sales yet.',
    denCoCau: 'Add tags in Organization structure →',
    nhanVien: 'Assigned staff member',
    nguon: 'Customer source',
    nguonNhanVien: 'Created by staff',
    nguonTuDangKy: 'Self-registered',
    taoTuNgay: 'Profile created from',
    denNgay: 'To',
    hinhThuc: 'Payment method',
    sanPham: 'Product',
    theoNguoiMangKhach: 'Team and staff member are counted by WHO BROUGHT THE CUSTOMER IN — the same basis as the Statistics screen. Self-registered customers belong to no team.',
  },
  khachHang: {
    them: 'Add customer',
    sua: 'Edit customer',
    hoTen: 'Full name',
    email: 'Email',
    soDienThoai: 'Phone number',
    linkFacebook: 'Facebook link',
    lienHe: 'Contact',
    phuongThuc: 'Payment method',
    phuongThucGoiY: 'This customer\'s default method — each registration still records its own.',
    tinhTrang: 'Status',
    daMua: 'Purchased',
    chuaMua: 'Not purchased',
    soKhoa: 'Courses',
    tongMua: 'Total purchased',
    hocVien: 'Student profile',
    capTaiKhoan: 'Create a student account',
    sdtDaCo: 'This number already belongs to {{ten}}.',
    moHoSoNay: 'Open this customer\'s profile',
    hoiCapTaiKhoan: 'Create a student profile and login account for {{ten}}? The profile will be permanently linked to this customer.',
    capTaiKhoanGoiY: 'Creates a student profile and login account for {{ten}}. The profile is linked to this customer automatically, so the same person is not duplicated.',
    matKhauGoiY: 'Read this password out to the student — the system forces them to change it at their first login.',
    chuaVaoHoc: 'Not studying yet',
    noiHocVien: 'Link to a student profile',
    noiHocVienGoiY: 'Select this once the customer has actually started studying. The two are the SAME person but stored separately: changing the name here does not change the student\'s name, and vice versa.',
    timTheo: 'Name, phone number or email',
    chuaCo: 'No customers yet',
    hoiLuu: 'Save this customer\'s information? The current data will be overwritten.',
    hoiXoa: 'Delete the customer "{{ten}}"? This cannot be undone.',
  },
  hinhThucChamSoc: {
    GoiDien: 'Phone call',
    ZaloFacebook: 'Zalo / Facebook',
    Email: 'Email',
    GapTrucTiep: 'In person',
    Khac: 'Other',
  },
  trangThaiKhachHang: {
    Moi: 'New',
    DangTuVan: 'In consultation',
    DaMua: 'Purchased',
    TuChoi: 'Declined',
  },
  chiTietNhanSu: {
    tabThongTin: 'General information',
    tabTep: 'Profile files',
  },
  chiTietKhach: {
    tabThongTin: 'General information',
    tabChamSoc: 'Customer care history',
    soLanMua: '{{so}} purchases',
    tongNhom: 'Group total',
    tongTatCa: 'Grand total',
    boSungThanhToan: 'Add a payment',
    guiYeuCau: 'Send a class request',
    guiYeuCauXepLop: 'Send a class request',
    hoiGuiYeuCau: 'Send a class placement request for "{{ten}}"? The training side will see this student in their waiting list.',
    dangChoXepLop: 'Awaiting class placement',
    daXepLop: 'Placed in class {{ten}}',
    daHocLop: 'Studied: {{ten}}',
    guiLai: 'Resend request',
    guiLanThu: 'This is submission number {{so}}',
    daGuiNLan: 'Sent {{so}} times',
    lanThu: 'Attempt {{so}}',
    lichSuGuiYeuCau: 'Class placement request history',
    ghiChuYeuCau: 'Note for the training team',
    ghiChuYeuCauGoiY: 'Level, preferred class times, things to note about the student…',
    lyDoTuChoi: 'Reason for rejection',
    lyDoTuChoiTruoc: 'The previous request was rejected because',
    nguoiGui: 'Sent by',
    nguoiXuLy: 'Handled by',
    suaThongTin: 'Edit information',
    soLanChamSoc: 'Care interactions',
    tongCamKet: 'Total committed',
    tongDaThu: 'Total collected',
    conThieu: '{{so}} still owed',
    themChamSoc: 'Log a care interaction',
    ghiMuaHangMoTa: 'Records the order and automatically adds a care history entry',
    chonMatHang: 'Select an item…',
    soLuong: 'Quantity',
    ngayMua: 'Purchase date',
    noiDungMuaGoiY: 'Leave empty and the system writes "Bought <item name>" automatically',
    daThuDu: 'Payment received in full',
    daThuDuGoiY: 'Tick this and the system records a single payment for the full amount above. Untick it if the customer pays in installments — use the "Amount paid" tab to record each one.',
    hoiMuaHang: 'Record this order? The system will add one revenue entry and one care history entry.',
    suaChamSoc: 'Edit care interaction',
    chamSocGoiY: 'Log one entry per contact with the customer — the most recent appears first.',
    chuaChamSoc: 'No care interaction yet',
    thoiDiem: 'Contact date',
    hinhThuc: 'Method',
    noiDung: 'Content',
    noiDungGoiY: 'What the customer said, what was sent, when to call back…',
    trangThaiSau: 'Status after this interaction',
    trangThaiSauGoiY: 'The customer\'s current status IS the status of the latest care interaction — there is no separate column that could drift out of sync.',
    hoiLuuChamSoc: 'Save this care interaction?',
    hoiXoaChamSoc: 'Delete this care interaction? This cannot be undone.',
    chuaDangKy: 'This customer has not registered for any course',
    camKet: 'Committed',
    daThu: 'Collected',
    daDu: 'Paid in full',
    chuaDong: 'Not paid',
    thieu: '{{so}} short',
    ghiThu: 'Record a payment',
    suaThu: 'Edit payment',
    ngayThu: 'Payment date',
    nguoiThu: 'Collected by',
    chuaThu: 'Nothing has been collected for this registration yet.',
    conThieuGoiY: '{{so}} still owed. Enter the amount actually received — payment can be made in installments.',
    hoiLuuThu: 'Save this payment?',
    hoiXoaThu: 'Delete the payment of {{so}}? This is financial data.',
  },
  loaiDonHang: {
    KhoaHoc: 'Course',
    SanPham: 'Product',
  },
  sanPham: {
    them: 'Add product',
    sua: 'Edit product',
    tenSp: 'Product name',
    giaTien: 'Price',
    donViTien: 'Currency',
    donViTinh: 'Unit',
    donViTinhGoiY: 'book, set, piece…',
    soDonHang: 'Orders',
    tongSoLuongBan: 'Sold',
    trangThaiBan: 'Status',
    dangBan: 'On sale',
    ngungBan: 'Discontinued',
    conBan: 'Still selling this product',
    ngungBanGoiY: 'A product that already has orders CANNOT be deleted — past orders must keep the name of the product that was sold. Untick the box above to stop selling it while keeping the history.',
    chuaCo: 'No products yet',
    hoiLuu: 'Save this product? The current information will be overwritten.',
    hoiXoa: 'Delete the product "{{ten}}"? This cannot be undone.',
  },
  trangThaiXepLop: {
    DangCho: 'Waiting',
    DaXep: 'Placed in a class',
    DaHuy: 'Cancelled',
    TuChoi: 'Rejected',
  },
  loaiMxh: {
    Facebook: 'Facebook',
    Zalo: 'Zalo',
    LinkedIn: 'LinkedIn',
    Telegram: 'Telegram',
    Khac: 'Other',
  },
  chucVu: {
    them: 'Add job title',
    sua: 'Edit job title',
    ten: 'Job title',
    thuTu: 'Display order',
    soNhanSu: 'Currently held by',
    trangThai: 'Status',
    dangDung: 'In use',
    ngungDung: 'Retired',
    conDung: 'Still using this job title',
    ngungDungGoiY: 'A job title that someone still holds CANNOT be deleted — existing profiles must keep the title they recorded. Untick the box above to retire it while keeping the history.',
    chuaCo: 'No job titles yet',
    giaiThich: 'A job title is a POSITION (Management board, Department head…), which differs from the business role (Staff, Teacher, Teaching assistant, Student). A job title grants NO additional permissions — permissions still come from the account\'s permission group.',
    hoiLuu: 'Save this job title? The current information will be overwritten.',
    hoiXoa: 'Delete the job title "{{ten}}"? A title that someone still holds cannot be deleted.',
  },
  tagVaiTro: {
    KinhDoanh: 'Sales group',
    GiaoVien: 'Teacher group',
    TroGiang: 'Teaching assistant group',
    goiYKinhDoanh: 'This department will appear in the team filter of Customers, Revenue and Statistics.',
    goiYGiaoVien: 'Identifies the group of teachers who lead classes. Does not appear in the sales filters.',
    goiYTroGiang: 'Identifies the group of teaching assistants. Does not appear in the sales filters.',
    KHAC: 'Other (untagged department)',
  },
  coCau: {
    xemNhanSuPhong: 'View this department\'s staff list',
    tagVaiTro: 'Role tag',
    khongTag: 'No tag (structure description only)',
    khongTagGoiY: 'An untagged department appears only in this structure tree — it shows up in no module\'s filters.',
    themPhongGoc: 'Add department',
    themPhongBan: 'Add department',
    themPhongCon: 'Add sub-department',
    suaPhongBan: 'Edit department',
    tenPhongBan: 'Department name',
    nguoiQuanLy: 'Manager',
    chuaChonQuanLy: 'No manager selected',
    quanLy: 'Manager',
    quanLyChiLaThongTin: 'Organizational information only — it grants no additional permissions. Permissions still come from the account\'s permission group.',
    thuTu: 'Display order',
    moTa: 'Description',
    phongGoc: 'Top-level department',
    duoiPhong: 'Under {{ten}}',
    chuaCoPhongBan: 'No departments yet — click "Add department" to begin',
    chuaXep: 'No department assigned',
    themNhanSu: 'Add staff to the department',
    chonNhanSu: 'Select staff',
    goTenNhanSu: 'Type a staff member\'s name to search…',
    hocVienKhongVaoCoCau: 'Students are not part of the organization structure, so they are not in this list.',
    hoiLuu: 'Save this department? The current information will be overwritten.',
    hoiXoa: 'Delete the department "{{ten}}"? A department that still has staff or sub-departments cannot be deleted.',
    hoiXepNhanSu: 'Assign {{soLuong}} staff to "{{ten}}"? They will leave their current department.',
  },
  xepLop: {
    dangCho: 'Students awaiting class placement',
    khongCoAiCho: 'No student is awaiting class placement',
    hocVien: 'Student',
    hocPhiTuDon: 'CRM order amount',
    nguoiGui: 'Sent by',
    thoiDiemGui: 'Sent on',
    duyet: 'Approve into class',
    timHocVienCho: 'Search by name or phone number...',
    timKhongThayCho: 'No matching student found',
    canhBaoLechKhoa: 'Course mismatch',
    hoiLechKhoa: 'The student\'s order is for the course "{{khoaDon}}", but class {{lop}} teaches "{{khoaLop}}". Place the student in this class anyway?',
    vanDuyet: 'Approve anyway',
    duyetVaoLop: 'Approve a student into a class',
    chonLop: 'Select a class',
    khoaDaMua: 'Course purchased',
    hocPhiSeApDung: 'The applied tuition will be {{so}} — taken from the CRM order amount, not the class price.',
    hoiDuyet: 'Place "{{ten}}" in class {{lop}} with tuition of {{hocPhi}}? The student will appear in the class\'s tuition book.',
    huyYeuCau: 'Cancel request',
    tuChoi: 'Reject',
    tuChoiXepLop: 'Reject class placement',
    lyDo: 'Reason for rejection',
    lyDoGoiY: 'No suitable class for this level has opened, please wait for the next intake…',
    lyDoBatBuoc: 'The seller needs to know why so they can answer the customer — please state the reason clearly.',
    hoiTuChoi: 'Reject the request for "{{ten}}"? The seller will see this reason and may resubmit.',
    lanGuiThu: 'Submission number {{so}}',
    ghiChuNguoiGui: 'Sender\'s note',
    hoiHuy: 'Cancel the class placement request for "{{ten}}"? The request is kept as history; to place them later the seller must send a new request.',
  },
  khoaHoc: {
    them: 'Add course',
    sua: 'Edit course',
    tenKhoa: 'Course name',
    giaTien: 'Price',
    donViTien: 'Currency',
    soBuoi: 'Sessions',
    soBuoiNgan: '{{so}} sessions',
    soDangKy: 'Sold',
    trangThaiBan: 'Status',
    dangBan: 'On sale',
    ngungBan: 'Discontinued',
    conBan: 'Still selling this course',
    ngungBanGoiY: 'A course that already has registrations CANNOT be deleted — past orders must keep the name of the course that was sold. Untick the box above to stop selling it while keeping the history.',
    chuaCo: 'No courses yet',
    hoiLuu: 'Save this course? The current information will be overwritten.',
    hoiXoa: 'Delete the course "{{ten}}"? This cannot be undone.',
  },
  donHang: {
    ghiDon: 'Record order',
    suaDon: 'Edit order',
    lichSu: 'Order history',
    loaiMatHang: 'What the customer bought',
    soLuong: 'Quantity',
    chonSanPham: 'Select a product',
    hoiLuu: 'Save this order?',
    hoiLuuKemChamSoc: 'Save this order? The system will add one revenue entry and one care history entry.',
    chuaCo: 'No orders yet',
  },
  doanhThu: {
    them: 'Add registration',
    sua: 'Edit registration',
    khachHang: 'Customer',
    khoaHoc: 'Course',
    matHang: 'Item',
    chonKhach: 'Select a customer…',
    chonKhoa: 'Select a course…',
    giaGoc: 'List price',
    soTien: 'Amount collected',
    phanTram: '% of list price',
    tyGia: 'Exchange rate to VND',
    tyGiaNgan: '×{{ty}}',
    soLuongNgan: 'Qty {{so}}',
    quyDoiVnd: 'Converted to VND',
    ngayDangKy: 'Registration date',
    tuNgay: 'From',
    denNgay: 'To',
    tongDoanhThu: 'Total revenue (VND)',
    soDangKy: 'Registrations',
    soKhachHang: 'Customers',
    giaNiemYet: 'List price: {{gia}} · {{so}} sessions. Change the amount if a discount applies.',
    tyGiaGoiY: 'The exchange rate is CAPTURED at registration time, not looked up dynamically — so last month\'s revenue figures do not change when rates move.',
    timTheo: 'Customer name, course name or phone number',
    chuaCo: 'No registrations yet',
    hoiLuu: 'Save this registration? The current information will be overwritten.',
    hoiXoa: 'Delete {{ten}}\'s registration for the course "{{khoa}}"? This is revenue data.',
  },
  crm: {
    moTaDoanhThu: 'Revenue aggregated by period, by class and by staff member. Different from the tuition receipt book in LMS: the receipt book holds each individual payment for one class, while revenue is the aggregated figure.',
  },
  thietLap: {
    hoiLuu: 'Save the center settings? The current information will be overwritten.',
    tieuDe: 'General settings',
    tenTrungTam: 'Center name',
    tenVietTat: 'Short name',
    moTa: 'Description',
    maTrungTam: 'Center code',
    maTrungTamKhongDoi: 'The center code is issued by the system and used to log in — it cannot be changed',
    logo: 'Center logo',
    anhBia: 'Cover image',
    diaChi: 'Address',
    diaChiGoiY: 'E.g. 123 Nguyen Van Linh, Hai Chau, Da Nang',
    lienHe: 'Contact',
    lienHeGoiY: 'Phone number or email',
    nhomChuyenKhoan: 'Bank transfer details',
    nhomChuyenKhoanMoTa: 'Shown to learners so they know where to transfer money. The system does NOT process payments.',
    soTaiKhoan: 'Account number',
    soTaiKhoanGoiY: 'E.g. 0123456789',
    tenNganHang: 'Bank',
    tenNganHangGoiY: 'E.g. Vietcombank',
    chuTaiKhoan: 'Account holder',
    chuTaiKhoanGoiY: 'Exactly as it appears in the banking app',
    chuTaiKhoanLuuY: 'The sender needs a matching name so the money does not go to the wrong account.',
    anhQr: 'Bank transfer QR code',
    anhQrGoiY: 'Take it from your banking app.',
  },
  loi: {
    KHONG_TIM_THAY_TRUNG_TAM: 'No center uses this code. Check the center code again (7 characters, with no 0 or 1).',
    MA_TRUNG_TAM_KHONG_HOP_LE: 'Invalid center code — 7 characters, and it must not contain 0/O/1/I/L',
    BAI_TAP_DA_CO_BAI_NOP: 'Students have already submitted work for this assignment — it cannot be deleted. Their submissions are their learning record.',
    LOP_HOC_KHONG_HOP_LE: 'The class is invalid or you do not have permission for it',
    LOAI_DINH_KEM_KHONG_HO_TRO: 'Unsupported attachment type',
    TAN_SUAT_TRONG: 'No day of the week has been selected',
    NGAY_KHONG_HOP_LE: 'Invalid date. Choose a different start date for generating the schedule.',
    KHACH_HANG_TRUNG_SO_DIEN_THOAI: 'Another customer is already using this phone number. Search by that number and edit the existing customer instead.',
    KHACH_HANG_DA_CO_DANG_KY: 'This customer already has a course registration — that is revenue data and cannot be deleted.',
    KHACH_HANG_KHONG_HOP_LE: 'Invalid customer',
    KHOA_ONLINE_KHONG_HOP_LE: 'Invalid online course',
    KHOA_ONLINE_DA_CO_NGUOI_HOC: 'This course already has learners, so it cannot be deleted. Switch it to "Closed to new access" to stop granting access.',
    KHOA_ONLINE_KHONG_NHAN_GHI_DANH: 'Access can only be granted for courses that are open. A draft course has no content yet; a course closed to new access takes no more learners.',
    BAI_HOC_KHONG_DOI_DUOC_KHOA: 'A lesson cannot be moved to another course.',
    KHONG_XAC_DINH_DUOC_NGUOI_DUNG: 'The current user could not be identified.',
    KHACH_HANG_DA_NOI_HO_SO_KHAC: 'This customer is already linked to another profile. Open that profile instead of creating a new one.',
    KHOA_HOC_TRUNG_TEN: 'A course with this name already exists',
    KHOA_HOC_DA_CO_DANG_KY: 'This course already has registrations and cannot be deleted. Untick "Still selling this course" to stop selling it while keeping the order history.',
    KHOA_HOC_KHONG_HOP_LE: 'Invalid course',
    SAN_PHAM_KHONG_HOP_LE: 'Invalid product',
    SAN_PHAM_TRUNG_TEN: 'A product with this name already exists',
    SAN_PHAM_DA_CO_DON_HANG: 'This product already has orders and cannot be deleted. Untick "Still selling this product" to stop selling it while keeping the order history.',
    PHAI_CHON_DUNG_MOT_MAT_HANG: 'Select exactly one item: either a course or a product.',
    TY_GIA_KHONG_HOP_LE: 'The exchange rate must be greater than 0',
    THU_VUOT_CAM_KET: 'The total collected exceeds the amount the customer committed to pay. Check the amount — usually it is one extra zero.',
    DANG_KY_KHONG_HOP_LE: 'Invalid registration',
    SO_TIEN_KHONG_HOP_LE: 'Invalid amount',
    GIO_KET_THUC_KHONG_HOP_LE: 'The end time must be after the start time (overnight classes are not supported)',
    SO_BUOI_KHONG_HOP_LE: 'The number of sessions must be between 1 and 500',
    NGAY_KET_THUC_TRUOC_KHAI_GIANG: 'The end date must be after the start date',
    DIEU_KIEN_DUNG_KHONG_HOP_LE: 'Choose exactly one way to end: by number of sessions OR by date',
    KHONG_SINH_DUOC_BUOI_NAO: 'No session could be generated — check the days of the week and the date range',
    CHAN_TREN_SINH_BUOI: 'Not enough sessions fit within the allowed time range',
    GIO_KHONG_TON_TAI_DO_DOI_GIO: 'This time does not exist because of the daylight saving change',
    LICH_DA_CO_DIEM_DANH: 'The class already has sessions with attendance — regenerating the schedule would lose that data. Edit individual sessions instead of regenerating.',
    BUOI_DA_HUY: 'The session has been cancelled',
    HOC_VIEN_KHONG_THUOC_LOP: 'The student is not in this class',
    KHONG_THUOC_LOP_NAY: 'You are not in this class',
    NGOAI_KHUNG_GIO_DIEM_DANH: 'Outside the attendance window (open from 15 minutes before the session until it ends)',
    THIEU_LY_DO_VANG: 'An absence must have a reason',
    NHAN_SU_KHONG_HOP_LE: 'Some staff are invalid (they have left or do not exist)',
    GIAO_VIEN_TRUNG_TRO_GIANG: 'The lead teacher cannot also be the teaching assistant of the class',
    CHUA_CHON_HINH_THUC_HOC: 'No learning mode has been selected',
    HOC_PHI_AM: 'Tuition cannot be negative',
    SUC_CHUA_KHONG_HOP_LE: 'Capacity must be greater than 0',
    LOP_DA_HOAN_TAT: 'This class has already been finalized; there is no need to finalize it again',
    CHUA_NHAP_HOC_PHI: 'Tuition must be entered before the class can be finalized',
    CHI_XOA_DUOC_LOP_NHAP: 'Only classes still in draft status can be deleted. For a class that has started, use Cancel class to keep the history.',
    CHUA_CHON_HOC_VIEN: 'No student has been selected',
    HOC_VIEN_KHONG_HOP_LE: 'Invalid student (they have dropped out or do not exist)',
    HOC_VIEN_DA_TRONG_LOP: 'The student is already in this class',
    KHOA_HOC_KHONG_KHOP_LOP: 'The course on the order does not match the course this class teaches',
    VUOT_SO_KHOA_HOC_CUA_LOP: 'A class can be assigned at most 3 courses',
    VUOT_SUC_CHUA: 'This exceeds the maximum capacity of the class',
    CHI_KHOA_HOC_MOI_XEP_LOP: 'Only course orders can be submitted for class placement',
    DA_GUI_YEU_CAU_XEP_LOP: 'A class placement request has already been sent for this order',
    YEU_CAU_KHONG_HOP_LE: 'The class placement request is invalid or has been deleted',
    YEU_CAU_DA_XU_LY: 'This request has already been handled; please reload the list',
    CHUA_NHAP_LY_DO_TU_CHOI: 'A reason for rejection must be entered',
    PHONG_BAN_TRUNG_TEN: 'A department with this name already exists at this level',
    CHUC_VU_TRUNG_TEN: 'A job title with this name already exists in the center',
    CHUC_VU_CON_NGUOI_GIU: 'Someone still holds this job title — untick "In use" to retire it while keeping the history',
    CHUC_VU_KHONG_HOP_LE: 'The job title does not exist',
    PHONG_BAN_CON_NGUOI: 'The department still has staff — move them to another department before deleting it',
    PHONG_BAN_CON_CAP_DUOI: 'The department still has sub-departments — delete from the bottom up',
    PHONG_BAN_CHU_TRINH: 'A department cannot be placed under itself',
    PHONG_BAN_KHONG_HOP_LE: 'The department does not exist',
    NGUOI_QUAN_LY_KHONG_HOP_LE: 'Invalid manager (they have left, or they are a student)',
    HOC_VIEN_KHONG_VAO_CO_CAU: 'Students are not part of the organization structure',
    CHUA_CHON_NHAN_SU: 'No staff member has been selected',
    LOAI_TEP_KHONG_HO_TRO: 'Only PDF, Word, Excel, PowerPoint, images or archive files are accepted',
    LOAI_TEP_HO_SO_KHONG_HO_TRO: 'Staff profiles accept only PDF, Word or Excel files',
    VUOT_SO_TEP_HO_SO: 'Each profile can hold at most 10 files — delete some old files and try again.',
    TIEU_CHI_THIEU_TEN: 'A criterion must have a name.',
    TIEU_CHI_TEN_QUA_DAI: 'The criterion name is too long (maximum 200 characters).',
    TIEU_CHI_TRUNG_TEN: 'This group already has a criterion with the same name.',
    TIEU_CHI_NHOM_KHONG_HOP_LE: 'Invalid criterion group.',
    TIEU_CHI_DA_CHAM_KHONG_DOI_NHOM: 'This criterion has already been rated, so its group cannot be changed — changing it would distort every period already rated. Retire it and create a new criterion in the other group instead.',
    TIEU_CHI_KHONG_THUOC_NHOM: 'Some criteria do not belong to the Sales group.',
    DIEM_TIEU_CHI_KHONG_HOP_LE: 'The score must be between 1 and 5.',
    KY_DANH_GIA_KHONG_HOP_LE: 'The evaluation period must be in the format yyyy-MM, for example 2026-09.',
    KHONG_PHAI_NHAN_VIEN_KINH_DOANH: 'Only sales staff can be rated.',
    TEN_TEP_KHONG_HOP_LE: 'Invalid file name — enter at least one character.',
    TEP_QUA_LON: 'The file is too large, maximum 20 MB',
    TEP_RONG: 'The file is empty',
    LOAI_ANH_KHONG_HO_TRO: 'Only JPG, PNG, WebP or GIF images are accepted',
    ANH_QUA_LON: 'The image is too large, maximum 5 MB',
    ANH_RONG: 'The image file is empty',
    DANG_NHAP_THAT_BAI: 'The center code, username or password is incorrect',
    TAI_KHOAN_BI_VO_HIEU_HOA: 'The account has been disabled',
    TAI_KHOAN_BI_KHOA_TAM: 'Too many incorrect passwords. The account is temporarily locked; please try again in a few minutes or use "Forgot password".',
    PHAI_DOI_MAT_KHAU: 'You must change your password before continuing',
    MAT_KHAU_CU_KHONG_DUNG: 'The current password is incorrect',
    TOKEN_DAT_LAI_KHONG_HOP_LE: 'The reset code is invalid or has expired',
    PHIEN_DA_BI_DAY_RA: 'This account has just logged in elsewhere, so your session has ended. If it was not you, log in again and change your password.',
    CHUA_XAC_THUC: 'You need to log in',
    KHONG_DU_QUYEN: 'You do not have permission to perform this action',
    TOKEN_THIEU_TENANT: 'Your session is invalid, please log in again',
    KHONG_TIM_THAY: 'No data found',
    DU_LIEU_KHONG_HOP_LE: 'The data entered is not valid',
    TRUNG_TAM_PHAI_CON_NGUOI_PHAN_QUYEN: 'The center must keep at least one person with the Permissions right. Grant that right to someone else first, then try again.',
    KHONG_TU_KHOA_TAI_KHOAN_CHINH_MINH: 'You cannot lock the account you are logged in with. Untick it and try again.',
    QUA_NHIEU_YEU_CAU: 'You are going too fast. Wait a moment and try again.',
    LOI_HE_THONG: 'Something went wrong, please try again',
    USERNAME_DA_TON_TAI: 'This username already exists in the center',
    QUYEN_KHONG_HOP_LE: 'Invalid permission group',
    QUYEN_DANG_DUOC_GAN: 'Cannot delete: the permission group is assigned to accounts',
    KHONG_TU_XOA_TAI_KHOAN_CUA_MINH: 'You cannot delete your own account',
    KHONG_TU_VO_HIEU_HOA_MINH: 'You cannot disable your own account',
    CHUC_NANG_KHONG_HOP_LE: 'Invalid feature',
    MAT_KHAU_QUA_NGAN: 'The password must be at least 12 characters',
    MAT_KHAU_QUA_DAI: 'The password is too long (maximum 128 characters)',
    MAT_KHAU_MOI_TRUNG_CU: 'The new password must be different from the current one',
    USERNAME_KY_TU_KHONG_HOP_LE: 'A username may contain only letters, digits and . _ -',
    ID_KHONG_KHOP: 'The data does not match',
    NGUOI_DUOC_CHAM_KHONG_DUNG_LOP: 'The person being rated did not lead this session. Reload the page and try again.',
    TRANG_THAI_KHONG_HOP_LE: 'Invalid session status.',
    BUOI_HOC_DA_KHOA: 'This session has been finalized, so it cannot be edited, cancelled or deleted. Attendance for a finalized session is the record of attendance.',
    BUOI_HOC_DA_CO_DIEM_DANH: 'This session already has attendance. Cancel the session instead of deleting it to keep the data.',
    BUOI_HOC_DA_CO_NHAN_XET: 'This session already has student feedback. Cancel the session instead of deleting it to keep the feedback.',
    BUOI_HOC_TRUNG_GIO: 'A session clashes with the current schedule. Choose a start date after the last session.',
    NGUOI_DUNG_KHONG_HOP_LE: 'Invalid person',
    KHONG_PHAI_NHAN_SU: 'The Staff screen manages only employees, teachers and teaching assistants. Students are managed on the Students screen in LMS.',
    KHONG_PHAI_HOC_VIEN: 'The Students screen manages only students. Employees, teachers and teaching assistants are managed on the Staff screen in HRM.',
    NGUOI_DUNG_DA_CO_TAI_KHOAN: 'This person already has an account. Each person may have only one login account.',
    NGUOI_DUNG_DANG_CO_DU_LIEU: 'Cannot delete: this person has classes, attendance or tuition records. Mark them as "Left" instead of deleting to keep the data.',
    SO_TIEN_PHAI_DUONG: 'The amount must be greater than 0',
  },
}

export default en
