/**
 * **日本語 (tiếng Nhật) — dịch từ `vi.ts`** (23/09/2026).
 *
 * Sinh bằng `scripts/sinh-tep-ngon-ngu.py` để cấu trúc khoá **luôn khớp `vi.ts`**.
 * Sửa tay được, nhưng đừng thêm/bớt khoá ở đây — thêm ở `vi.ts` trước, vì
 * `check-i18n-keys.py` so mọi ngôn ngữ với tệp đó.
 *
 * Chỉ dịch GIAO DIỆN. Dữ liệu người dùng nhập (tên lớp, tên học viên, ghi chú)
 * giữ nguyên — xem `danhSach.ts`.
 */
const ja = {
  chung: {
    tieuDeTab: 'LangCenter — 語学センター管理システム',
    xacNhanLuu: '保存の確認',
    xemChiTiet: '詳細を見る',
    ghiChu: '備考',
    dangPhatTrien: 'このモジュールは開発中です',
    dangPhatTrienGoiY: 'モジュールの権限管理と画面遷移はすでに動作しています。今すぐグループへ権限を付与していただけます。詳細な業務機能は後日追加されます。',
    xacNhanThem: '新規追加の確認',
    hoiLuu: '「{{ten}}」の変更を保存しますか？現在の情報は上書きされます。',
    hoiThem: '「{{ten}}」を新規追加しますか？',
    hoiLuuChung: '変更を保存しますか？',
    hoiThemChung: 'このレコードを新規追加しますか？',
    dangTai: '読み込み中…',
    tatCa: 'すべて',
    dongY: '同意する',
    luu: '保存',
    huy: 'キャンセル',
    them: '追加',
    sua: '編集',
    xoa: '削除',
    timKiem: '検索',
    thaoTac: '操作',
    khongCoDuLieu: 'データがありません',
    xacNhanXoa: '本当に削除しますか？',
    dangXuat: 'ログアウト',
    quayLai: '戻る',
    dong: '閉じる',
    moMenu: 'メニューを開く',
    moSidebar: 'サイドバーを展開',
    thuGonSidebar: 'サイドバーを折りたたむ',
    daLuu: '保存しました',
    taiVe: 'ダウンロード',
    xem: '表示',
  },
  dangKy: {
    tieuDe: 'センター登録',
    moTa: 'センター名を入力してください。システムがセンターコードを発行します',
    nut: 'センターを作成',
    thanhCong: 'センターを作成しました',
    maTrungTamCuaBan: 'あなたのセンターコード',
    saoChep: 'コピー',
    giaiThichMa: 'センターコードはシステムが発行する7文字のコードで、ログインに使用します。',
    canhBaoLuuMa: 'センターコードは必ず控えてください。ログインのたびに必要となり、ご自身で再確認することはできません。',
    luuYDoiMatKhau: '初回ログイン時にパスワードの変更を求められます。',
    chuaMo: '登録は受付けていません',
    chuaMoMoTa: 'このシステムでは自由登録を受け付けていません。センターの作成については管理者にお問い合わせください。',
    veDangNhap: '← ログイン画面へ戻る',
  },
  ngonNgu: {
    doi: '言語を変更',
    nhan: '言語',
  },
  linhVat: {
    tat: 'キャラクターを隠す',
    thoai: [
      '今日も楽しい授業になりますように！',
      'ページを閉じる前に保存を忘れずにね。',
      'コーヒーはもう飲んだ？ちょっと休憩するのもいいよ。',
      '今日のクラスの調子はどう？',
      'ちょっとお散歩してくるね。お仕事つづけてどうぞ！',
      'データが整っていると月末がぐっとラクになるよ。',
      '困ったことがあれば管理者に聞いてみてね！',
      '一文字教わればその人は先生。今日もいい授業を！',
    ],
  },
  dangNhap: {
    tieuDe: 'ログイン',
    moTa: 'センターコード、ユーザー名、パスワードを入力してください',
    maTrungTam: 'センターコード',
    tenPhanMem: 'LangCenter',
    bannerTieuDe: '語学センター管理システム',
    bannerMoTa: 'センターコードを入力して始めましょう。クラス、受講生、出欠、授業料をひとつのシステムで管理できます。',
    banQuyen: '© {{nam}} LangCenter · 本ソフトウェアは GiapTex が開発しています',
    banQuyenCoTen: '© {{nam}} {{ten}} · 本ソフトウェアは GiapTex が開発しています',
    maTrungTamGoiY: '7文字、大文字と小文字は区別しません',
    dangTraTenTrungTam: 'センターコードを照会しています…',
    khongTimThayTrungTam: '該当するセンターが見つかりません',
    chuaCoTrungTam: 'センターをお持ちでないですか？',
    username: 'ユーザー名',
    matKhau: 'パスワード',
    nut: 'ログイン',
    nhoDangNhap: 'センターコードとユーザー名を記憶する',
    quenMatKhau: 'パスワードをお忘れですか？',
    doiMatKhauTieuDe: 'パスワード変更',
    doiMatKhauMoTa: 'システムに入る前に、アカウントのパスワードを変更する必要があります',
    matKhauCu: '現在のパスワード',
    matKhauMoi: '新しいパスワード',
    xacNhanMatKhau: '新しいパスワードの確認',
    quenTieuDe: 'パスワードをお忘れの方',
    quenMoTa: '登録済みのメールアドレスを入力し、パスワード再設定コードを受け取ってください',
    email: 'メールアドレス',
    guiYeuCau: 'リクエストを送信',
    daGuiEmail: 'そのメールアドレスがシステムに登録されている場合、再設定コードをお客様のメールボックスへ送信しました。',
    maDatLai: '再設定コード',
    datLaiMatKhau: 'パスワードを再設定',
  },
  menu: {
    tongQuan: 'ダッシュボード',
    daoTao: '教務',
    nhanSu: '人事',
    khachHang: '顧客',
    nhanVienKinhDoanh: '営業担当者',
    giaoVienNhanSu: '講師',
    nhanSuNguoiDung: '職員プロフィール',
    coCauToChuc: '組織構成',
    chucVu: '役職',
    hocVien: '受講生',
    doanhThu: '売上',
    khachHangDs: '顧客',
    khoaHoc: 'コース',
    sanPham: '商品',
    lopHoc: 'クラス',
    choXepLop: 'クラス分け待ち',
    taiLieu: '教材',
    khoaOnline: 'オンラインコース',
    thongKeCrm: '統計',
    hocPhi: '授業料',
    trangDich: 'ランディングページ',
    noiDungTrangDich: 'ページ内容',
    lienHeTrangDich: 'お問い合わせ',
    quanTri: 'システム管理',
    taiKhoan: 'アカウント',
    nguoiDung: 'ユーザー',
    phanQuyen: '権限管理',
    thietLap: '共通設定',
    nhatKy: 'システムログ',
  },
  hocPhi: {
    hoiThu: '入金 {{soTien}} を記録しますか？受講生の未納額がその分減額されます。',
    hoiSua: '入金額を {{soTien}} に変更しますか？未納額は新しい金額に基づいて再計算されます。',
    tabCongNo: '未納額',
    tabSoThu: '入金記録',
    thuTien: '入金処理',
    suaKhoanThu: '入金の編集',
    xoaKhoanThu: '入金の削除',
    xacNhanXoa: '{{hocVien}} さんの入金 {{soTien}} を削除しますか？未納額がその分増加します。',
    lop: 'クラス',
    tatCaLop: 'すべてのクラス',
    chonLop: 'クラスを選択',
    hocVien: '受講生',
    chonHocVien: '受講生を選択',
    hocPhi: '授業料',
    daThu: '入金済み',
    tongPhaiThu: '請求総額',
    tienDoThu: '入金進捗',
    khongCoQuyenXem: '授業料情報を閲覧する権限がありません。クラス全体の授業料を確認できるのは管理者のみで、受講生はご自身の未納額のみ閲覧できます。',
    conNo: '未納',
    conNoNhan: '未納',
    daDuUpper: '完納',
    quaHan: '期限超過',
    chiConNo: '未納者のみ表示',
    khongCoCongNo: 'フィルター条件に一致する未納額はありません',
    chuaCoKhoanThu: '入金はまだ記録されていません',
    soTien: '金額',
    ngayThu: '入金日',
    phuongThuc: '支払方法',
    soPhieu: '伝票番号',
    ghiChu: '備考',
    nguoiThu: '受領者',
    pt: {
      TienMat: '現金',
      ChuyenKhoan: '銀行振込',
      Khac: 'その他',
    },
  },
  nguoiDung: {
    gomPhongCon: '下位部署を含む',
    themNguoiDung: 'ユーザーを追加',
    suaNguoiDung: 'ユーザーを編集',
    timTheo: '氏名、メールアドレス、電話番号',
    trangThaiNhanSu: '職員',
    DangLamViec: '在職中',
    DaNghi: '退職済み',
    hoSo: 'プロフィール',
    hoSo_GiaoVien: '講師プロフィール',
    hoSo_HocVien: '受講生プロフィール',
    hoSo_NhanVien: '職員プロフィール',
    bangCap: '学位・資格',
    chuyenMon: '専門分野',
    ngayVaoLam: '入社日',
    truongLop: '学校・クラス',
    khachHangCrm: '顧客 (CRM)',
    khachHangCrmChon: '既存の顧客を選択…',
    khachHangCrmGoiY: '任意 — 同一人物が重複登録されないよう、このプロフィールを CRM で購入済みの顧客と紐付けます。',
    tenPhuHuynh: '保護者氏名',
    sdtPhuHuynh: '保護者電話番号',
    chucVu: '役職',
    chuaGanChucVu: '役職が未設定です',
    ngaySinh: '生年月日',
    diaChi: '住所',
    cccd: '身分証明書番号',
    soTaiKhoan: '口座番号',
    tenNganHang: '銀行',
    lienKetMxh: 'SNS リンク',
    duongDanMxh: 'URL または電話番号…',
    themMxh: 'リンクを追加',
    tepHoSo: 'プロフィール書類',
    taiTep: 'ファイルをアップロード',
    chuaCoTep: 'ファイルがまだありません — 雇用契約書、資格証明書のスキャン、身分証明書のスキャンなど',
    gioiHanTep: 'PDF・Word・Excel のみ · 1 ファイルあたり最大 20 MB',
    soTepDaDung: '{{so}}/{{toiDa}} ファイル使用中',
    datTenTep: 'ファイル名を設定',
    doiTenTep: 'ファイル名を変更',
    tenHienThi: '表示名',
    viDuTenTep: '例: 2026年 雇用契約書',
    giuDuoiTep: '拡張子を入力する必要はありません — システムが自動的に保持します (.pdf、.docx など)',
    hoiXoaTep: 'ファイル「{{ten}}」を削除しますか？復元はできません。',
    phongBan: '部署',
    chuaXepPhongBan: '組織構成に未配置です',
    taiKhoan: 'アカウント',
    chuaCoTaiKhoan: 'なし',
    nguoiSoHuu: 'ユーザー',
    khongGanAi: '誰にも紐付けない',
    taoTaiKhoanDangNhap: 'ログインアカウントを作成',
    khongCanDangNhap: 'この方はログインできません。あとで「アカウント」タブからアカウントを作成できます。',
    giaiThichGanNguoi: '特定の人に属さない技術用アカウントの場合は空欄のままにしてください。',
    hoiXoa: 'ユーザー「{{ten}}」を削除しますか？復元はできません。すでにデータがある場合は、削除せず「退職済み」としてマークしてください。',
    giaiThichVoHieuHoa: '無効化してもログインが停止されるだけです。この方のプロフィールとすべてのデータはそのまま保持されます。',
  },
  nhatKy: {
    timTheo: '操作名、実行者',
    module: 'モジュール',
    hanhDong: 'アクション',
    thoiDiem: '日時',
    nguoiThucHien: '実行者',
    thaoTac: '操作',
    soBanGhi: 'レコード',
    ketQua: '結果',
    thanhCong: '成功',
    thatBai: '失敗',
    chiThatBai: '失敗した操作のみ表示',
    khongCoBanGhi: '記録された操作はまだありません',
    xemChiTiet: '詳細を表示',
    truongDaDoi: '変更された項目',
    thamSo: '操作パラメータ',
    diaChiIp: 'IP',
  },
  hanhDongNhatKy: {
    Them: '追加',
    Sua: '編集',
    Xoa: '削除',
    XacThuc: '認証',
    Khac: 'その他',
  },
  thongKe: {
    loaiThongKe: '集計の単位',
    kyMacDinh: '既定の期間',
    khoangSai: '開始日は終了日以前である必要があります。',
    loai: {
      KhoaHoc: 'コース',
      SanPham: '商品',
      Elearning: 'オンライン学習',
      DoiNhom: 'チーム',
    },
    loaiMoTa: {
      KhoaHoc: '販売した各コースの売上です。',
      SanPham: '各商品の売上 — 書籍、教材など。',
      Elearning: '',
      DoiNhom: '顧客情報の作成者に基づく、部署ごとの売上です。',
    },
    locTheo: {
      KhoaHoc: '指定したコースのみ',
      SanPham: '指定した商品のみ',
      Elearning: '',
      DoiNhom: '指定したチームのみ',
    },
    boLoc: '絞り込みを解除',
    dangLoc: '{{so}} 件で絞り込み中 — この画面のすべての数値は選択した分のみを集計しています。',
    elearningMoTa: '件数のみを計測し、金額は計測しません。オンラインコースは注文と紐付いておらず、管理者が手動で受講権限を付与します。',
    chuaCoKhoaMo: '公開中のオンラインコースがまだありません。下書き状態のコースはここに含まれません — レッスンを作成し終えたら「公開中」に切り替えてください。',
    elearningGoiY: '学習に関する数値は上の行にあります。オンライン学習の売上は設計上存在しません。',
    soKhoaOnline: '公開中のコース',
    soNguoiHoc: '受講中の人数',
    soLuotGhiDanh: '登録件数',
    tyLeHoanThanh: '修了率',
    baiTrenTong: '{{da}}/{{tong}} レッスン',
    tongDoanhThu: '売上合計',
    soDon: '注文数',
    giaTriDonTb: '平均注文単価',
    daThu: '入金済み',
    conThieu: '残り {{so}} 未納',
    thuDu: '全額入金済み',
    soKyTruoc: '前期比',
    chuaCoKyTruoc: '比較できる前期がありません',
    soDonNgan: '{{so}} 件',
    khongXacDinh: '不明',
    chuaCoDon: 'この期間の注文はまだありません',
    chuaCoKhach: '顧客がまだいません',
    doanhThuTheoThang: '月別売上',
    doanhThuTheoThangMoTa: '登録時点で取得した為替レートで VND に換算しています — 過去の帳票の数値は変わりません。',
    theoCaNhan: '担当者別売上',
    theoCaNhanMoTa: '顧客情報の作成者ごとに集計します。作成者が記録されていない過去の注文は「不明」にまとめられます。',
    theoDoiNhom: 'チーム別売上',
    theoDoiNhomMoTa: '顧客情報の作成者が所属する部署ごとに集計します。',
    theoSanPham: '商品別売上',
    theoSanPhamMoTa: 'コースとその他の商品の両方を含みます。',
    theoNguon: '顧客獲得経路別売上',
    theoNguonMoTa: '自己登録の顧客は、担当者個人の売上実績には計上されません。',
    pheu: '営業ファネル',
    pheuMoTa: '各ステップにいる顧客数と、顧客総数に対する割合です。',
  },
  nguonKhachHang: {
    NhanVienTao: '職員が作成',
    TuDangKy: '顧客の自己登録',
  },
  khoaOnline: {
    ten: 'コース名',
    trangThai: 'ステータス',
    moTa: '説明',
    chuaCo: 'オンラインコースがまだありません',
    chuaCoBai: 'このコースにはレッスンがまだありません',
    chuaCoHocVien: '受講権限を付与した相手がまだいません',
    themKhoa: 'オンラインコースを追加',
    suaKhoa: 'コースを編集',
    soBaiHoc: 'レッスン数',
    soHocVien: '受講生',
    tienDo: '進捗',
    taoRaLaNhap: '新しいコースは必ず下書き状態で作成されます — レッスンを作成し終えたら「公開中」に切り替えてください。',
    dangNhapGoiY: 'このコースは下書き状態のため受講生には表示されず、受講権限も付与できません。レッスンを作成し終えたら、コースを編集して「公開中」に切り替えてください。',
    tabBaiHoc: 'レッスン',
    tabHocVien: '受講生',
    themBai: 'レッスンを追加',
    suaBai: 'レッスンを編集',
    xoaBai: 'レッスンを削除',
    xoaBaiHoi: 'レッスン「{{ten}}」を削除しますか？このレッスンに関する受講生の学習進捗も併せて失われます。',
    tieuDeBai: 'レッスンのタイトル',
    thuTu: '並び順',
    noiDung: '内容',
    baiTrong: 'このレッスンにはまだ内容がありません。',
    congKhai: '一般公開',
    congKhaiGoiY: 'ログインしている人なら誰でも、登録なしで閲覧できます — 期限が切れている場合も同様です。紹介用レッスンやサンプルレッスンにご利用ください。',
    danhDauDaHoc: '学習済みにする',
    capQuyen: '受講権限を付与',
    hoiTaoKhoa: 'このオンラインコースを作成しますか？新しいコースは下書き状態となり、まだ誰にも表示されません。',
    hoiLuuKhoa: 'このコースの変更を保存しますか？',
    hoiLuuBai: 'このレッスンを保存しますか？',
    hoiCapQuyen: '選択した受講生にこのコースの受講権限を付与しますか？',
    thuQuyen: '受講権限を取り消す',
    thuQuyenHoi: '{{ten}} さんの受講権限を取り消しますか？学習済みの進捗は保持されるため、再度付与すれば続きから学習できます。',
    hocVien: '受講生',
    hetHan: '有効期限',
    hetHanGoiY: '空欄＝無期限で受講できます。',
    ghiChuCap: '備考',
    ghiChuVd: '例：注文 #123 で購入、体験受講、IELTS クラスの特典',
    nguoiCap: '付与者',
    vinhVien: '無期限',
  },
  trangThaiKhoaOnline: {
    Nhap: '下書き',
    DangMo: '公開中',
    NgungCapMoi: '新規付与停止',
  },
  tongQuan: {
    viecCanLam: '対応が必要な作業',
    khongCoViec: '対応が必要な作業はありません',
    buoiHomNay: '本日の授業',
    buoiSapToi: '次回の授業',
    buoiThu: '第 {{so}} 回',
    lopDangHoatDong: '稼働中のクラス',
    buoiQuaHan: '終了済みで出欠が未確定の授業',
    baiChuaCham: '未採点の提出物',
    choXepLop: 'クラス分け待ちの受講生',
    chuaCoNoiDung: 'システムは初期状態です — 業務機能がまだ設定されていません。まずはセンターのアカウントと権限グループを作成してください。',
  },
  phanTrang: {
    dangXem: '{{tong}} 件中 {{tu}}〜{{den}} 件を表示',
    soDong: '表示件数',
    trangTruoc: '前のページ',
    trangSau: '次のページ',
  },
  anh: {
    chonAnh: '画像を選択',
    doiAnh: '画像を変更',
    goAnh: '画像を削除',
    goiY: 'JPG、PNG、WebP または GIF · 最大 5 MB',
  },
  loaiNguoiDung: {
    NhanVien: 'その他の職員',
    NhanVienKinhDoanh: '営業担当',
    GiaoVien: '講師',
    TroGiang: 'アシスタント講師',
    HocVien: '受講生',
  },
  lopHoc: {
    hoiThemHocVien: '{{soLuong}} 名の受講生をこのクラスに登録しますか？',
    hoiGoHocVien: '「{{ten}}」をクラスから外しますか？ 記録済みの出欠と授業料は保持されます。',
    tieuDe: 'クラス',
    themMoi: 'クラスを追加',
    ten: 'クラス名',
    giaoVienChinh: '主担当講師',
    troGiang: 'アシスタント講師',
    hinhThuc: '受講形式',
    phongHoc: '教室',
    linkHoc: 'オンライン授業リンク',
    hocPhi: '授業料',
    sucChuaToiDa: '最大定員',
    khongGioiHan: '無制限',
    ngayKhaiGiang: '開講日',
    ngayKetThuc: '終了日',
    trangThai: 'ステータス',
    ghiChu: '備考',
    soHocVien: '受講生',
    hocVien: 'クラスの受講生',
    xemThongTin: '情報を表示',
    hocVienCuaLop: '{{lop}} クラスの受講生',
    nhanVienKinhDoanh: '営業担当',
    themTrucTiep: 'または既存の受講生を追加',
    themTrucTiepGiaLop: '適用授業料はクラスの標準額が適用されます',
    themHocVien: '受講生を追加',
    goHocVien: 'クラスから外す',
    hocPhiApDung: '適用授業料',
    ngayVaoLop: 'クラス参加日',
    hoanTat: 'クラスを確定',
    huyLop: 'クラスを取り消す',
    xacNhanHuy: 'このクラスを取り消しますか？ 出欠と授業料の履歴は保持されます。',
    chuaCoLop: 'クラスがまだありません',
    chonGiaoVien: '講師を選択…',
    timGiaoVien: '講師名を入力して検索…',
    khoaHocCuaLop: 'このクラスで教えるコース',
    chuaGanKhoa: 'コースが未割り当てです',
    toiDaNKhoa: '（最大 {{so}} 件）',
    chonKhoaHoc: 'コースを選択...',
    timKhoaHoc: 'コースを検索',
    daDatToiDaKhoa: 'コースは最大 {{so}} 件に達しています',
    chonTroGiang: 'アシスタント講師を選択…',
    timTroGiang: 'アシスタント講師名を入力して検索…',
    timHocVien: '受講生名を入力して検索…',
    locTrangThai: 'ステータスで絞り込み',
    nhapGoiY: '下書きのクラスはご自身にのみ表示されます。「クラスを確定」を押すと公開されます。',
    xemChiTiet: '詳細を表示',
    siSo: '在籍数',
    buoiDaHoc: '実施済み授業',
    thoiGian: '時間',
    tabLichTatCa: '授業スケジュール',
    locTheoLop: 'クラスで絞り込み',
    lichTuNgay: '開始日',
    lichDenNgay: '終了日',
    lichXoaLoc: '絞り込みを解除',
    dangLocKhoangNgay: '期間で絞り込み中です — カレンダーの月切り替えボタンではデータが変わりません。月単位で見るには絞り込みを解除してください。',
    tabDanhSach: 'クラス一覧',
    tabTongQuan: '概要',
    tabHocVien: '受講生',
    tabLich: 'スケジュールと出欠',
    tabBaiTap: '課題',
    tabHocPhi: '授業料',
    tabTaiLieu: '教材',
    suaThongTin: 'クラス情報を編集',
    luuThongTin: 'クラス情報を保存',
    daChon: '{{soLuong}} 件選択中',
    sucChuaConLai: '{{daChon}} 件選択中 / 最大 {{toiDa}} 件',
  },
  hinhThucHoc: {
    ChuaChon: '— 選択 —',
    Online: 'オンライン',
    Offline: '対面',
    KetHop: 'ハイブリッド',
  },
  trangThaiLopHoc: {
    Nhap: '下書き',
    SapKhaiGiang: '開講予定',
    DangHoc: '開講中',
    DaKetThuc: '終了済み',
    DaHuy: '取り消し済み',
  },
  trangThaiHocVien: {
    DangHoc: '受講中',
    BaoLuu: '休学',
    ChuyenLop: 'クラス変更',
    DaNghi: '退会済み',
  },
  lich: {
    thang: '月',
    tuan: '週',
    danhSach: '一覧',
    homNay: '今日',
    truoc: '前の期間',
    sau: '次の期間',
    kieuBang: 'テーブル',
    kieuLich: 'カレンダー',
  },
  chiTietBuoi: {
    tabThongTin: '授業情報',
    tabDiemDanh: '出欠',
    tabNhanXet: 'コメント',
    tabBaiTap: '課題',
    tabTaiLieu: '教材',
    quayLaiLich: 'スケジュールに戻る',
    buoiTruoc: '前の授業',
    buoiSau: '次の授業',
    chonBuoi: '別の授業を選択',
    khongTimThayBuoi: '授業が見つかりません',
    taiLieuTheoLop: '教材は各授業ではなくクラス全体に紐づきます — これはクラス共通の教材です。',
  },
  nhanXetBuoi: {
    tieuDe: '授業に対する受講生のコメント',
    cuaToi: '自分のコメント',
    noiDung: '内容',
    noiDungGoiY: '本日の授業はいかがでしたか？ 改善すべき点はありますか？',
    mucHaiLong: '総合満足度',
    theoTieuChi: '評価基準ごとの採点（5 段階）',
    khongChon: '評価しない',
    chamNguoiDungLop: '授業担当者を評価',
    vaiTro: {
      GiaoVien: '講師',
      TroGiang: 'アシスタント講師',
    },
    chuaChonDiem: '未採点',
    boChon: '選択中の評価をもう一度押すと採点を取り消せます',
    khongCoTieuChi: 'センターで授業の評価基準が設定されていません。管理者に連絡し、「評価基準」（HRM）の項目から追加してもらってください。',
    diemDaCham: '採点済みの点数',
    chamChung: '授業全体への採点',
    gui: 'コメントを送信',
    capNhat: 'コメントを更新',
    hoiGui: 'この授業についてのコメントを送信しますか？',
    hoiCapNhat: '送信済みのコメントを更新しますか？ 以前の内容は上書きされます。',
    daGui: 'コメントを送信しました',
    chuaCo: 'この授業へのコメントはまだありません',
    nhanXetHocVien: '受講生からのコメント',
    nhanXetGiaoVien: '講師から受講生へのコメント',
    chuaCoNhanXetGv: 'この授業で講師がコメントした受講生はまだいません',
    ghiONhanXetGv: '講師のコメントは「出欠」タブで受講生ごとに記入します。',
    giaiThichChoGv: 'ここのコメント欄は受講生が授業について意見を寄せる専用の場であるため、そのクラスに在籍中の受講生のみ送信できます。受講生一人ひとりへのコメントを記入するには「出欠」タブを開いてください。受講生ごとに個別のコメント欄があります。',
  },
  buoiHoc: {
    hoiSinhLich: '選択した頻度でスケジュールを生成しますか？',
    hoiSinhThem: '現在のスケジュールに授業を追加しますか？既存の授業は削除されません。',
    hoiSinhLai: '再生成すると未実施の授業が削除され、新しいスケジュールが作成されます。確定済みの授業はそのまま残ります。続行しますか？',
    hoiChotBuoi: 'この授業を確定しますか？出欠が未登録の方は「欠席」として記録され、確定後は時間の変更・中止・削除ができなくなります。',
    thuTuNgan: '第{{n}}回',
    sinhThemBuoi: '授業を追加',
    xoaBuoi: '授業を削除',
    doiTrangThai: 'ステータスを変更',
    moTaDoiTrangThai: '第{{thuTu}}回 — {{gio}}。新しいステータスを選択してください：',
    dangApDung: '適用中',
    laHocBu: '補講である',
    macDinhTheoLop: '空欄＝クラスの設定に従う',
    tuNgay: '生成開始日',
    daChot: '確定済み{{soLuong}}回',
    goiYSinhThem: '現在のスケジュールに授業を追加します。既存の授業は削除されず、新しい授業には続きの番号が付きます。1回だけ追加する場合（補講・復習など）は回数を1にしてください。',
    canhBaoSinhLai: '再生成すると未実施の授業が削除され、新しいスケジュールが作成されます。確定済みの授業はそのまま残ります。',
    xacNhanSinhLai: '未実施の授業{{soLuong}}回を削除して新しいスケジュールを生成しますか？確定済みの{{daChot}}回は残ります。既存のスケジュールを残したまま授業を追加したい場合は「授業を追加」または「授業を追加生成」をご利用ください。',
    xacNhanHuyBuoi: '第{{thuTu}}回（{{gio}}）を中止しますか？履歴を残すため記録自体は保持されます。',
    xacNhanXoaBuoi: '第{{thuTu}}回（{{gio}}）を完全に削除しますか？復元はできません。すでに実施済みの授業は削除ではなく中止をおすすめします。',
    tieuDe: '授業',
    lich: '授業スケジュール',
    thuTu: '回',
    thoiGian: '日時',
    giaoVien: '講師',
    giaoVienRieng: '個別講師',
    phongHoc: '教室',
    linkHoc: 'オンライン授業リンク',
    ghiChu: '備考',
    troGiang: 'アシスタント講師',
    troGiangTheoLop: 'クラスのアシスタント講師です。この授業には個別のアシスタント講師が割り当てられていません。',
    theoLop: '（クラスの設定）',
    khongCoTroGiang: 'このクラスにはアシスタント講師がいません',
    hocBu: '補講',
    hocOnline: 'オンライン授業',
    nhom: {
      sapToi: '今後',
      daQua: '過去',
    },
    trangThai: 'ステータス',
    diemDanh: '出欠',
    chuaCoLich: 'このクラスにはまだ授業スケジュールがありません',
    sinhLich: 'スケジュールを生成',
    sinhLaiLich: 'スケジュールを再生成',
    thuTrongTuan: '授業曜日',
    gioBatDau: '開始時刻',
    gioKetThuc: '終了時刻',
    ketThucTheo: '終了条件',
    theoSoBuoi: '回数',
    theoNgay: '終了日',
    ngayLoaiTru: '休講日（授業なし）',
    ngayLoaiTruGoiY: '1行に1日ずつ、2026-04-30 の形式で入力してください',
    xemTruoc: 'スケジュールをプレビュー',
    daSinh: '{{soLuong}}回の授業を生成します',
    huyBuoi: 'この授業を中止',
    chotBuoi: '授業を確定',
    chotBuoiGoiY: '出欠が未登録の方は「欠席」として記録されます。',
    tuDiemDanh: 'クイック出欠登録',
  },
  diemDanh: {
    hoiLuu: '{{soLuong}}名の受講生の出欠を保存しますか？',
    tieuDe: '出欠',
    hocVien: '受講生',
    tuKhai: '受講生の自己申告',
    chinhThuc: '確定',
    lyDoVang: '欠席理由',
    thieuLyDoVang: '{{soLuong}}名の受講生の欠席理由が未入力です：{{ten}}。理由を入力してから保存するか、「授業を確定」を使って「出欠未登録」として記録してください。',
    thieuLyDoNgan: '理由が未入力の欠席者が残っています',
    nguon: '登録元',
    chuaGhiNhan: '未登録',
    khacTuKhai: '自己申告と相違',
    luu: '出欠を保存',
    daLuu: '出欠を保存しました',
    chiXem: 'この出欠表は閲覧のみ可能です。',
    nhanXetGv: '講師のコメント',
    nhanXetGoiY: '発音、参加度、宿題など…',
    buoiDaChot: '確定済みの授業です。出欠とコメントは引き続き修正できますが、授業時間は変更できません。',
  },
  trangThaiDiemDanh: {
    CoMat: '出席',
    Vang: '欠席',
    DiMuon: '遅刻',
    VangCoPhep: '公認欠席',
  },
  nguonDiemDanh: {
    HocVienTuKhai: '受講生の自己申告',
    GiaoVien: '講師',
    QuanTri: '管理者',
  },
  trangThaiBuoiHoc: {
    DaLenLich: '予定済み',
    DaHoanThanh: '完了',
    DaHuy: '中止',
    ChuyenLich: '日程変更',
  },
  tinhTrangBuoi: {
    ChuaBatDau: '開始前',
    DangDienRa: '実施中',
    ChuaChot: '未確定',
    DaXong: '終了',
    ChuyenLich: '日程変更',
    DaHuy: '中止',
  },
  thu: {
    Monday: '月',
    Tuesday: '火',
    Wednesday: '水',
    Thursday: '木',
    Friday: '金',
    Saturday: '土',
    Sunday: '日',
  },
  hocLieu: {
    luuDiem: '点数を保存',
    daSuaChuaLuu: '{{soLuong}}件を編集しました（未保存）',
    hoiLuuDiem: '{{soLuong}}件の提出物の点数とコメントを保存しますか？',
    hoiXoaBaiTap: '課題「{{ten}}」を削除しますか？受講生の提出物も一緒に削除されます。',
    baiTap: '課題',
    taiLieu: '教材',
    themBaiTap: '課題を出す',
    themTaiLieu: '教材を追加',
    tieuDe: 'タイトル',
    moTa: '説明',
    hanNop: '提出期限',
    buoiHoc: '授業',
    loai: '分類',
    ganLop: 'クラスに紐付ける',
    ganLopGoiY: '空欄＝センター全体の共通教材',
    lopChung: '共通',
    tep: '添付ファイル',
    themTep: 'ファイルを追加',
    keoThaTep: 'ファイルを選択（PDF、Word、Excel、画像 — 最大20MB）',
    daNop: '提出済み',
    chuaCoBaiTap: '課題はまだありません',
    chuaCoTaiLieu: '教材はまだありません',
    xemBaiNop: '提出物を見る',
    lanNop: '提出回数',
    thoiDiemNop: '提出日時',
    diem: '点数',
    nhanXet: 'コメント',
    cham: '採点',
    nguoiTaiLen: 'アップロード者',
  },
  trangThaiBaiNop: {
    DaNop: '提出済み',
    NopMuon: '期限後提出',
    DaCham: '採点済み',
  },
  loaiTaiLieu: {
    GiaoTrinh: '教科書',
    BaiGiang: '講義資料',
    ThamKhao: '参考資料',
    DeThi: '試験問題',
    Khac: 'その他',
  },
  taiKhoan: {
    tieuDe: 'ユーザーアカウント',
    username: 'ログインID',
    hoTen: '氏名',
    ngaySinh: '生年月日',
    loaiNguoiDung: '役割',
    email: 'メールアドレス',
    soDienThoai: '電話番号',
    diaChi: '住所',
    quyen: '権限グループ',
    trangThai: 'ステータス',
    hoatDong: '有効',
    voHieuHoa: '無効',
    themMoi: 'アカウント追加',
    suaTieuDe: 'アカウント更新',
    datLaiMatKhau: 'パスワード再設定',
    canDoiMatKhau: 'パスワード変更が必要',
    wizardGoiY: '既にある場合は権限グループを選択してください',
    chonQuyen: '権限グループを選択…',
    timQuyen: '権限グループ名を入力して検索…',
    buocDoiMk: '初回ログイン時にパスワード変更を必須にする',
    buocDoiMkGoiY: '有効にすることを推奨します。代わりに設定したパスワードは、あなたも知っているためです。',
    datLaiGoiY: 'ユーザーは次回ログイン時にパスワードの変更を求められます。',
    matKhau: 'パスワード',
    matKhauMoi: '新しいパスワード',
    themTaiKhoan: 'アカウント追加',
    suaTaiKhoan: 'アカウント更新',
    buocDoiMatKhau: '初回ログイン時にパスワード変更を必須にする',
    phaiDoiMatKhau: 'パスワード変更が必要',
    hoiXoa: 'アカウント「{{ten}}」を削除しますか？ユーザープロフィールは保持され、ログイン手段のみが失われます。',
    hoiDatLaiMatKhau: '「{{ten}}」のパスワードを再設定しますか？次回ログイン時に変更を求められ、古いパスワードは直ちに無効になります。',
    HoatDong: '有効',
    VoHieuHoa: '無効',
  },
  quyen: {
    hoiLuu: '権限グループ「{{ten}}」を保存しますか？グループ内の全アカウントの権限が直ちに変更されます。',
    tieuDe: 'アクセス権限管理',
    tenQuyen: '権限グループ名',
    moTa: '説明',
    soTaiKhoan: 'アカウント数',
    themMoi: '権限グループ追加',
    suaTieuDe: '権限グループ編集',
    maTran: '権限マトリクス',
    chucNang: '機能',
    soO: '権限セル数',
    cauHinh: '権限設定',
    taoVaCauHinh: '作成して権限を設定',
    themMoiGoiY: '先にグループ名を付けてください。次のステップで権限を選択します。役割テンプレートがあるため、一からチェックする必要はありません。',
    batDauTuMau: '役割テンプレートから開始',
    apMauTieuDe: '役割テンプレートを適用',
    apMauHoi: '現在選択中の権限をすべて「{{ten}}」の権限セット（{{so}}セル）に置き換えますか？その後も個別のセルを調整できます。',
    dangDung: '{{so}} 件のアカウントが使用中',
    tongDaChon: '{{so}} セルを選択済み',
    chiXem: '権限マトリクスの設定権限がないため、閲覧のみ可能です。修正が必要な場合はシステム管理者にお問い合わせください。',
    khongThayNhom: 'この権限グループが見つかりません。削除された可能性があります。',
    veDanhSach: '権限グループ一覧へ戻る',
    canNhac: {
      DiemDanh: {
        Chot: '出欠簿を締め切り、未申告の全員を欠席として記録します。後から修正できません。',
      },
      XepLop: {
        Duyet: '販売担当者に代わって決定を行い、その注文に影響します。取り消しできません。',
      },
      LopHoc: {
        HoanTat: 'クラスが下書き状態から外れ、関係者全員に表示されます。一方通行の操作です。',
        Huy: 'クラスとその全授業をキャンセルします。データは残りますが、クラスは稼働を停止します。',
      },
      BuoiHoc: {
        Huy: '授業をキャンセルします。受講生のカレンダーにキャンセル済みと表示されます。',
      },
      PhanQuyen: {
        CauHinhQuyen: 'この権限を持つ人は、自分のグループに他のあらゆる権限を自分で付与できます。管理者のみに付与してください。',
      },
      DoiMatKhauNguoiKhac: {
        Sua: '他人のパスワードを再設定できます。つまり、その人のアカウントにログインできるということです。',
      },
      DoanhThu: {
        ThuTien: '顧客からの入金を確認します。注文を作成した人とは分けることを推奨します。',
      },
      HocPhi: {
        ThuTien: '受講生が授業料を支払ったことを入金記録に記載します。',
      },
      ThietLapChung: {
        CauHinhTien: '顧客が送金する入金情報（振込用QRコード）を変更します。',
      },
      NhanXetBuoiHoc: {
        Xem: 'その授業の全員のコメントを閲覧できます。受講生には付与しないでください。クラスメイトの個別フィードバックまで読めてしまいます。',
      },
      LopHocToanTrungTam: {
        Xem: '自分の担当クラスだけでなく、センターの全クラスと、そこに在籍する受講生のプロフィールおよび連絡先を閲覧できます。',
        Sua: '自分が担当していないクラスも編集できます。',
      },
      chung: {
        Chot: '帳簿を締め切ります。その後は修正できません。',
        Duyet: '取り消しできない決定です。',
        ThuTien: '金銭に関わる操作です。',
        Huy: 'キャンセルしますが記録は保持します。',
      },
    },
    phamViDuLieu: 'データ範囲',
    phamViGoiY: 'これらの権限は機能を追加するものではなく、ユーザーが閲覧できるデータの範囲を広げるものです。付与しない場合は自分の担当クラスのみ閲覧できます。付与した場合はセンターの全クラスと、そこに在籍する受講生のプロフィールおよび連絡先を閲覧できます。',
    oCu: 'このグループには、現在の一覧に存在しない古い権限が残っています: {{ds}}。保存してもそのまま保持されますが、効力はありません。整理が必要な場合はシステム管理者にお問い合わせください。',
  },
  hanhDong: {
    Xem: '閲覧',
    Them: '追加',
    Sua: '編集',
    Xoa: '削除',
    Duyet: '承認 / 却下',
    Chot: '帳簿締め',
    Huy: 'キャンセル',
    SinhLich: '授業スケジュール生成',
    ThuTien: '入金処理',
    Cham: '採点',
    TuLam: '自分で行う（自分の分）',
    DocTep: '添付ファイル閲覧',
    QuanLyTep: 'ファイルのアップロード / 削除',
    CauHinhTien: '決済設定',
    CauHinhQuyen: '権限マトリクス設定',
    HoanTat: 'クラス作成の完了',
    XepNhanSu: '職員の部署配属',
    GuiXepLop: 'クラス分け依頼の送信',
    XuatBan: '公開',
    ChuyenCrm: 'CRM へ移行',
  },
  tieuChi: {
    them: '評価基準を追加',
    sua: '評価基準を編集',
    ten: '評価基準名',
    moTa: '評価者向けのヒント',
    nhomLabel: 'グループ',
    chuaCo: '評価基準がまだありません',
    soLanDaCham: '評価済み',
    hoiLuu: 'この評価基準を保存しますか？',
    giaiThich: '評価基準は5段階評価の採点に使用します。営業グループは管理者が月次で評価し、指導グループは受講生が各授業ごとに評価します。',
    khongDoiNhom: 'この評価基準には既に評価点があるため、グループを変更できません。',
    ngungDungGoiY: 'チェックを外すと使用を停止します。新しい評価票には表示されなくなりますが、過去の評価票は引き続き閲覧できます。既に評価に使用された基準は削除できません。削除すると評価済みの全期間の結果が不正確になるためです。',
    nhom: {
      KinhDoanh: '営業担当者',
      GiangDay: '講師 / アシスタント講師',
    },
    nhomMoTa: {
      KinhDoanh: '管理者が月次で評価',
      GiangDay: '受講生が各授業ごとに評価',
    },
  },
  thongKeNs: {
    tabKinhDoanh: '営業',
    tabGiaoVien: '講師',
    tabTroGiang: 'アシスタント講師',
    hoTen: '氏名',
    soHocVien: '受講生数',
    soLop: 'クラス数',
    soBuoiDayDu: '完全実施した授業数',
    soBuoiHuy: 'キャンセルした授業数',
    chatLuongChamSoc: '対応品質',
    chatLuongGiangDay: '指導品質',
    soPhieu: '{{so}} 件の評価票',
    soLopNgan: '{{so}} クラス',
    cham: '採点',
    chamTieuDe: '営業担当者の評価',
    ky: '評価期間',
    kyGoiY: '各職員につき各期間ごとに評価票は1枚です。再評価は既存の評価票の修正になります。',
    nhanXet: '管理者のコメント',
    hoiLuuPhieu: '{{ten}} の {{ky}} 期の評価票を保存しますか？',
    xepHangDoanhThu: '売上によるランキング',
    xepHangHocVien: '受講生数によるランキング',
    xepHangHocVienMoTa: 'この担当者が獲得し、実際に受講を開始した顧客です。',
    xepHangBuoiDay: '完全実施した授業数によるランキング',
    xepHangChatLuong: '指導品質によるランキング',
    xepHangChatLuongMoTa: '各授業について受講生が付けた評価の平均点です。',
    chuaCoNhanVienKd: '営業担当者がまだいません。',
    chuaCoNguoi: 'この役割の方がまだいません。',
    chuaCoHocVien: 'この期間に受講を開始した顧客がまだいません。',
    chuaCoBuoi: 'この期間に完了した授業がまだありません。',
    chuaCoDanhGia: 'この期間の評価がまだありません。',
    chuaCoTieuChiKd: '営業グループの評価基準がまだありません。「評価基準」タブで追加してから採点できます。',
    chuaCoTieuChiGd: '指導グループの評価基準がまだありません。受講生が詳細に評価できるよう、「評価基準」タブで追加してください。',
  },
  chucNang: {
    TaiKhoan: 'ログインアカウント',
    HoSoNguoiDung: 'ユーザープロフィール',
    LopHoc: 'クラス',
    GhiDanhLop: '受講生のクラス登録',
    XepLop: 'CRM からのクラス分け',
    BuoiHoc: '授業',
    DiemDanh: '出欠',
    NhanXetBuoiHoc: '授業へのコメント',
    BaiTap: '課題',
    BaiNopBaiTap: '受講生の提出物',
    BaiKiemTra: 'テスト',
    BaiLamKiemTra: '受講生の答案',
    KhoaOnline: 'オンラインコース（コンテンツ作成）',
    GhiDanhKhoaOnline: 'オンラインコースの受講権限付与',
    HocOnline: 'オンライン学習',
    TaiLieu: '教材',
    HocPhi: '授業料',
    ThongKe: '統計',
    LopHocToanTrungTam: 'センターの全クラス',
    NhatKyHeThong: 'システムログ',
    TrangDich: 'ランディングページ',
    LienHeLanding: 'ランディングページのお問い合わせ',
    PhanQuyen: '権限管理',
    ThietLapChung: '共通設定',
    Anh: '画像（ロゴ、カバー画像、QRコード）',
    DoiMatKhauNguoiKhac: '他のユーザーのパスワード変更',
    NhanSu: '職員',
    ChucVu: '役職',
    PhongBan: '部署',
    TieuChiDanhGia: '評価基準',
    ThongKeNhanSu: '職員統計',
    DoanhThu: '売上',
    ThongKeDoanhThu: '売上統計',
    KhachHang: '顧客',
    ChamSocKhachHang: '顧客フォロー',
    KhoaHoc: 'コース',
    SanPham: '商品',
  },
  ldp: {
    dangHienCongKhai: '公開中',
    chuaXuatBan: '未公開 — 訪問者はまだ見られません',
    xuatBan: '公開',
    goXuatBan: '公開を取り消す',
    seo: '検索タイトルと説明',
    tieuDeSeo: 'ページタイトル',
    tieuDeSeoGoiY: '空欄ならセンター名を使います',
    moTaSeo: '短い説明',
    dangTat: '非表示',
    leenTren: '上へ',
    xuongDuoi: '下へ',
    tatKhoi: 'このブロックを隠す',
    batKhoi: 'このブロックを表示',
    tieuDeKhoi: 'ブロックの見出し',
    moTaKhoi: '内容',
    nhanNut: 'ボタンの文言',
    nhanNutGoiY: '体験を申し込む',
    duongDanNut: 'ボタンのリンク先',
    danhSachMuc: '項目',
    chuaCoMuc: '項目がありません。',
    tenMucMoi: '新しい項目名',
    xacNhanXoaMuc: 'この項目を削除しますか？',
    xoaMucMatGi: '項目「{{ten}}」がランディングページから削除されます。元に戻せません。',
    tieuDeMuc: '見出し',
    phuDeMuc: 'サブ見出し',
    moTaMuc: '説明',
    giaNiemYet: '表示価格',
    danhSachLienHe: '受信したお問い合わせ',
    chuaCoLienHe: 'お問い合わせはありません。',
    hoTen: '氏名',
    soDienThoai: '電話番号',
    quanTam: '希望コース',
    loiNhan: 'メッセージ',
    ngayGui: '受信日',
    daChuyenCrm: 'CRM 登録済み',
    chuyenCrm: 'CRM へ移行',
    xacNhanXoaLienHe: 'このお問い合わせを削除しますか？',
    xoaLienHeMatGi: '「{{ten}}」さんのお問い合わせが削除されます。元に戻せません。',
    khoi: {
      Hero: 'ヒーローバナー',
      GioiThieu: '紹介',
      KhoaHoc: 'コース',
      GiaoVien: '講師陣',
      CamNhan: '受講者の声',
      TinTuc: 'お知らせ',
      LienHe: 'お問い合わせ',
    },
  },
  heThong: {
    Hrm: 'HRM — 人事',
    Crm: 'CRM — 顧客',
    Lms: 'LMS — 教育',
    Ldp: 'LDP — ランディングページ',
    DungChung: '全システム共通',
    chuyenHeThong: 'システム切り替え',
    dungChungGoiY: 'これらの管理機能は全システムで共通のため、すべてのタブに表示されます。',
  },
  hrm: {
    moTaNvkd: '営業担当者のプロフィール：目標、担当顧客、歩合。',
    moTaGiaoVien: '人事の視点から見た講師：契約、給与、勤怠。LMS側の講師と同一人物であり、管理する情報が異なるだけです。',
  },
  phuongThucThanhToan: {
    TienMat: '現金',
    ChuyenKhoan: '銀行振込',
    Khac: 'その他',
  },
  donViTien: {
    VND: 'VND — ベトナムドン',
    USD: 'USD — 米ドル',
    EUR: 'EUR — ユーロ',
    CAD: 'CAD — カナダドル',
  },
  crmLoc: {
    locThem: '絞り込み追加',
    xoaLoc: '絞り込み解除',
    doiNhom: 'チーム',
    chuaCoTag: '営業タグが付いた部署はまだありません。',
    denCoCau: '組織構成でタグを付ける →',
    nhanVien: '担当者',
    nguon: '顧客の流入元',
    nguonNhanVien: '作成した職員',
    nguonTuDangKy: '顧客の自己登録',
    taoTuNgay: 'プロフィール作成日（開始）',
    denNgay: '終了日',
    hinhThuc: '支払方法',
    sanPham: '商品',
    theoNguoiMangKhach: 'チームと職員は「顧客を獲得した人」を基準に集計します — 統計画面と同じ基準です。自己登録の顧客はどのチームにも属しません。',
  },
  khachHang: {
    them: '顧客を追加',
    sua: '顧客を編集',
    hoTen: '氏名',
    email: 'メールアドレス',
    soDienThoai: '電話番号',
    linkFacebook: 'Facebookリンク',
    lienHe: '連絡先',
    phuongThuc: '支払方法',
    phuongThucGoiY: 'この顧客の既定の支払方法です — 各申込には個別に記録されます。',
    tinhTrang: '状況',
    daMua: '購入済み',
    chuaMua: '未購入',
    soKhoa: 'コース数',
    tongMua: '購入合計',
    hocVien: '受講生プロフィール',
    capTaiKhoan: '受講生アカウントを発行',
    sdtDaCo: 'この番号はすでに{{ten}}のものです。',
    moHoSoNay: 'この顧客のプロフィールを開く',
    hoiCapTaiKhoan: '{{ten}}の受講生プロフィールとログインアカウントを作成しますか？プロフィールはこの顧客と固定で紐付けられます。',
    capTaiKhoanGoiY: '{{ten}}の受講生プロフィールとログインアカウントを作成します。プロフィールはこの顧客と自動的に紐付けられるため、同一人物が重複して作成されることはありません。',
    matKhauGoiY: 'このパスワードを受講生に伝えてください — 初回ログイン時にシステムが変更を求めます。',
    chuaVaoHoc: '未受講',
    noiHocVien: '受講生プロフィールと紐付ける',
    noiHocVienGoiY: '顧客が実際に受講を開始したときに選択してください。両者は同一人物ですが別々に保存されます：ここで名前を変更しても受講生の名前は変わらず、その逆も同様です。',
    timTheo: '氏名、電話番号またはメールアドレス',
    chuaCo: '顧客はまだ登録されていません',
    hoiLuu: '顧客情報を保存しますか？現在のデータは上書きされます。',
    hoiXoa: '顧客「{{ten}}」を削除しますか？元に戻すことはできません。',
  },
  hinhThucChamSoc: {
    GoiDien: '電話',
    ZaloFacebook: 'Zalo / Facebook',
    Email: 'メール',
    GapTrucTiep: '直接面談',
    Khac: 'その他',
  },
  trangThaiKhachHang: {
    Moi: '新規',
    DangTuVan: '相談対応中',
    DaMua: '購入済み',
    TuChoi: '辞退',
  },
  chiTietNhanSu: {
    tabThongTin: '基本情報',
    tabTep: '書類ファイル',
  },
  chiTietKhach: {
    tabThongTin: '基本情報',
    tabChamSoc: 'フォロー履歴',
    soLanMua: '購入{{so}}回',
    tongNhom: 'グループ合計',
    tongTatCa: '全体合計',
    boSungThanhToan: '支払いを追加',
    guiYeuCau: 'クラス作成依頼を送信',
    guiYeuCauXepLop: 'クラス作成依頼を送信',
    hoiGuiYeuCau: '「{{ten}}」のクラス分け依頼を送信しますか？教育部門の待機リストにこの受講生が表示されます。',
    dangChoXepLop: 'クラス分け待ち',
    daXepLop: '{{ten}}に配属済み',
    daHocLop: '受講済み：{{ten}}',
    guiLai: '依頼を再送信',
    guiLanThu: 'これは{{so}}回目の送信です',
    daGuiNLan: '{{so}}回送信済み',
    lanThu: '{{so}}回目',
    lichSuGuiYeuCau: 'クラス分け依頼の送信履歴',
    ghiChuYeuCau: '教育部門への備考',
    ghiChuYeuCauGoiY: 'レベル、希望する受講時間帯、受講生に関する注意事項など…',
    lyDoTuChoi: '却下理由',
    lyDoTuChoiTruoc: '前回却下された理由',
    nguoiGui: '送信者',
    nguoiXuLy: '対応者',
    suaThongTin: '情報を編集',
    soLanChamSoc: 'フォロー回数',
    tongCamKet: '約定額合計',
    tongDaThu: '入金額合計',
    conThieu: '残り{{so}}',
    themChamSoc: 'フォローを記録',
    ghiMuaHangMoTa: '注文を記録し、フォロー履歴を1件自動で追加します',
    chonMatHang: '品目を選択…',
    soLuong: '数量',
    ngayMua: '購入日',
    noiDungMuaGoiY: '空欄の場合、システムが自動的に「<品目名>を購入」と記録します',
    daThuDu: '全額受領済み',
    daThuDuGoiY: 'このチェックを入れると、上記の金額を全額受領したものとしてシステムが1件記録します。顧客が分割で支払う場合はチェックを外し、「入金済み金額」タブで各回を記録してください。',
    hoiMuaHang: 'この注文を記録しますか？システムが売上を1件とフォロー履歴を1件追加します。',
    suaChamSoc: 'フォロー内容を編集',
    chamSocGoiY: '顧客と連絡を取るたびに1件記録します — 最新のものが先頭に表示されます。',
    chuaChamSoc: 'フォロー記録はまだありません',
    thoiDiem: '連絡日',
    hinhThuc: '方法',
    noiDung: '内容',
    noiDungGoiY: '顧客の発言、送付した内容、次回の連絡予定など…',
    trangThaiSau: 'この対応後のステータス',
    trangThaiSauGoiY: '顧客の現在のステータスは、最新のフォロー記録のステータスそのものです — 両者が食い違うような専用の列はありません。',
    hoiLuuChamSoc: 'このフォロー記録を保存しますか？',
    hoiXoaChamSoc: 'このフォロー記録を削除しますか？元に戻すことはできません。',
    chuaDangKy: 'この顧客はまだどのコースにも申し込んでいません',
    camKet: '約定額',
    daThu: '入金済み',
    daDu: '全額納入済み',
    chuaDong: '未納',
    thieu: '不足{{so}}',
    ghiThu: '入金を記録',
    suaThu: '入金記録を編集',
    ngayThu: '入金日',
    nguoiThu: '受領者',
    chuaThu: 'この申込に対する入金はまだ1件もありません。',
    conThieuGoiY: '残り{{so}}です。実際に受領した金額を入力してください — 分割での納入も可能です。',
    hoiLuuThu: 'この入金記録を保存しますか？',
    hoiXoaThu: '入金記録{{so}}を削除しますか？これは金銭に関するデータです。',
  },
  loaiDonHang: {
    KhoaHoc: 'コース',
    SanPham: '商品',
  },
  sanPham: {
    them: '商品を追加',
    sua: '商品を編集',
    tenSp: '商品名',
    giaTien: '価格',
    donViTien: '通貨単位',
    donViTinh: '数量単位',
    donViTinhGoiY: '冊、セット、個…',
    soDonHang: '注文数',
    tongSoLuongBan: '販売済み',
    trangThaiBan: 'ステータス',
    dangBan: '販売中',
    ngungBan: '販売停止',
    conBan: 'この商品を引き続き販売する',
    ngungBanGoiY: '注文が発生している商品は削除できません。過去の注文には販売した商品名を残す必要があるためです。上のチェックを外すと、履歴を保持したまま販売を停止できます。',
    chuaCo: '商品がまだありません',
    hoiLuu: '商品を保存しますか？現在の情報は上書きされます。',
    hoiXoa: '商品「{{ten}}」を削除しますか？元に戻せません。',
  },
  trangThaiXepLop: {
    DangCho: '待機中',
    DaXep: 'クラス分け済み',
    DaHuy: '取消済み',
    TuChoi: '却下されました',
  },
  loaiMxh: {
    Facebook: 'Facebook',
    Zalo: 'Zalo',
    LinkedIn: 'LinkedIn',
    Telegram: 'Telegram',
    Khac: 'その他',
  },
  chucVu: {
    them: '役職を追加',
    sua: '役職を編集',
    ten: '役職名',
    thuTu: '表示順',
    soNhanSu: '在任者数',
    trangThai: 'ステータス',
    dangDung: '使用中',
    ngungDung: '使用停止',
    conDung: 'この役職を引き続き使用する',
    ngungDungGoiY: '在任者がいる役職は削除できません。過去の記録には登録済みの役職を残す必要があるためです。上のチェックを外すと、履歴を保持したまま使用を停止できます。',
    chuaCo: '役職がまだありません',
    giaiThich: '役職とは肩書き（経営陣、部長など）であり、業務上のロール（職員、講師、アシスタント講師、受講生）とは異なります。役職によって権限が追加されることはありません。権限はあくまでアカウントの権限管理に従います。',
    hoiLuu: '役職を保存しますか？現在の情報は上書きされます。',
    hoiXoa: '役職「{{ten}}」を削除しますか？在任者がいる役職は削除できません。',
  },
  tagVaiTro: {
    KinhDoanh: '営業グループ',
    GiaoVien: '講師グループ',
    TroGiang: 'アシスタント講師グループ',
    goiYKinhDoanh: 'この部署は顧客・売上・統計のチーム絞り込みに表示されます。',
    goiYGiaoVien: 'クラスを担当する講師グループを識別します。売上の絞り込みには表示されません。',
    goiYTroGiang: 'アシスタント講師グループを識別します。売上の絞り込みには表示されません。',
    KHAC: 'その他（タグ未設定の部署）',
  },
  coCau: {
    xemNhanSuPhong: 'この部署の職員一覧を表示',
    tagVaiTro: 'ロールタグ',
    khongTag: 'タグなし（組織の記述のみ）',
    khongTagGoiY: 'タグのない部署はこの組織ツリーにのみ表示され、どのモジュールの絞り込みにも表示されません。',
    themPhongGoc: '部署を追加',
    themPhongBan: '部署を追加',
    themPhongCon: '下位部署を追加',
    suaPhongBan: '部署を編集',
    tenPhongBan: '部署名',
    nguoiQuanLy: '管理者',
    chuaChonQuanLy: '管理者が未選択です',
    quanLy: '管理',
    quanLyChiLaThongTin: '組織上の情報にすぎず、権限が追加されることはありません。権限はあくまでアカウントの権限管理に従います。',
    thuTu: '表示順',
    moTa: '説明',
    phongGoc: '最上位の部署',
    duoiPhong: '{{ten}} の下位',
    chuaCoPhongBan: '部署がまだありません。「部署を追加」を押して始めてください',
    chuaXep: '部署未配属',
    themNhanSu: '部署に職員を追加',
    chonNhanSu: '職員を選択',
    goTenNhanSu: '職員名を入力して検索…',
    hocVienKhongVaoCoCau: '受講生は組織構成に属さないため、一覧には表示されません。',
    hoiLuu: '部署を保存しますか？現在の情報は上書きされます。',
    hoiXoa: '部署「{{ten}}」を削除しますか？職員が在籍している、または下位部署がある場合は削除できません。',
    hoiXepNhanSu: '{{soLuong}} 名の職員を「{{ten}}」に配属しますか？現在の部署からは外れます。',
  },
  xepLop: {
    dangCho: 'クラス分け待ちの受講生',
    khongCoAiCho: 'クラス分け待ちの受講生はいません',
    hocVien: '受講生',
    hocPhiTuDon: 'CRM 注文の金額',
    nguoiGui: '送信者',
    thoiDiemGui: '送信日',
    duyet: 'クラスへの承認',
    timHocVienCho: '氏名または電話番号で検索...',
    timKhongThayCho: '該当する受講生が見つかりません',
    canhBaoLechKhoa: 'コースが一致しません',
    hoiLechKhoa: 'この受講生の注文はコース「{{khoaDon}}」ですが、クラス {{lop}} で教えているのはコース「{{khoaLop}}」です。それでもこのクラスに受講生を入れますか？',
    vanDuyet: 'それでも承認',
    duyetVaoLop: '受講生のクラス参加を承認',
    chonLop: 'クラスを選択',
    khoaDaMua: '購入済みコース',
    hocPhiSeApDung: '適用される授業料は {{so}} です。クラスの価格ではなく、CRM 注文の金額が使われます。',
    hoiDuyet: '「{{ten}}」を授業料 {{hocPhi}} でクラス {{lop}} に入れますか？この受講生はクラスの入金記録に表示されるようになります。',
    huyYeuCau: 'リクエストを取り消す',
    tuChoi: '却下',
    tuChoiXepLop: 'クラス分けを却下',
    lyDo: '却下の理由',
    lyDoGoiY: 'このレベルに合うクラスがまだ開講されていないため、次の期をお待ちください…',
    lyDoBatBuoc: '販売担当者が顧客に回答できるよう理由を知る必要があります。理由を明確に記入してください。',
    hoiTuChoi: '「{{ten}}」のリクエストを却下しますか？販売担当者にはこの理由が表示され、再送信することができます。',
    lanGuiThu: '{{so}} 回目の送信',
    ghiChuNguoiGui: '送信者のメモ',
    hoiHuy: '「{{ten}}」のクラス分けリクエストを取り消しますか？リクエストは履歴として残ります。再度クラス分けするには、販売担当者が新しいリクエストを送信する必要があります。',
  },
  khoaHoc: {
    them: 'コースを追加',
    sua: 'コースを編集',
    tenKhoa: 'コース名',
    giaTien: '価格',
    donViTien: '通貨',
    soBuoi: '授業回数',
    soBuoiNgan: '{{so}} 回',
    soDangKy: '販売済み',
    trangThaiBan: 'ステータス',
    dangBan: '販売中',
    ngungBan: '販売停止',
    conBan: 'このコースを引き続き販売する',
    ngungBanGoiY: '申込のあるコースは削除できません。過去の注文には販売したコース名を残す必要があるためです。上のチェックを外すと、履歴を保持したまま販売を停止できます。',
    chuaCo: 'コースがまだありません',
    hoiLuu: 'コースを保存しますか？現在の情報は上書きされます。',
    hoiXoa: 'コース「{{ten}}」を削除しますか？元に戻せません。',
  },
  donHang: {
    ghiDon: '注文を記録',
    suaDon: '注文を編集',
    lichSu: '注文履歴',
    loaiMatHang: '顧客が購入したもの',
    soLuong: '数量',
    chonSanPham: '商品を選択',
    hoiLuu: 'この注文を保存しますか？',
    hoiLuuKemChamSoc: 'この注文を保存しますか？システムが売上を 1 件、フォロー履歴を 1 件追加します。',
    chuaCo: '注文がまだありません',
  },
  doanhThu: {
    them: '申込を追加',
    sua: '申込を編集',
    khachHang: '顧客',
    khoaHoc: 'コース',
    matHang: '商品',
    chonKhach: '顧客を選択…',
    chonKhoa: 'コースを選択…',
    giaGoc: '定価',
    soTien: '入金額',
    phanTram: '定価に対する%',
    tyGia: 'VND への為替レート',
    tyGiaNgan: '×{{ty}}',
    soLuongNgan: '数量 {{so}}',
    quyDoiVnd: 'VND 換算',
    ngayDangKy: '申込日',
    tuNgay: '開始日',
    denNgay: '終了日',
    tongDoanhThu: '売上合計（VND）',
    soDangKy: '申込件数',
    soKhachHang: '顧客数',
    giaNiemYet: '表示価格: {{gia}} · {{so}} 回。割引がある場合は金額を修正してください。',
    tyGiaGoiY: '為替レートは申込時点の値を記録し、動的に取得しません。そのため、レートが変動しても前月の売上金額は変わりません。',
    timTheo: '顧客名、コース名または電話番号',
    chuaCo: '申込がまだありません',
    hoiLuu: '申込を保存しますか？現在の情報は上書きされます。',
    hoiXoa: '{{ten}} のコース「{{khoa}}」の申込を削除しますか？これは売上データです。',
  },
  crm: {
    moTaDoanhThu: '期間別、クラス別、担当者別に集計した売上です。LMS の入金記録とは異なります。入金記録はあるクラスの個別の入金であり、売上は集計値です。',
  },
  thietLap: {
    hoiLuu: 'センターの設定を保存しますか？現在の情報は上書きされます。',
    tieuDe: '共通設定',
    tenTrungTam: 'センター名',
    tenVietTat: '略称',
    moTa: '説明',
    maTrungTam: 'センターコード',
    maTrungTamKhongDoi: 'センターコードはシステムが発行し、ログインに使用します — 変更できません',
    logo: 'センターのロゴ',
    anhBia: 'カバー画像',
    diaChi: '住所',
    diaChiGoiY: '例: 123 Nguyen Van Linh, Hai Chau, Da Nang',
    lienHe: '連絡先',
    lienHeGoiY: '電話番号またはメールアドレス',
    nhomChuyenKhoan: '振込情報',
    nhomChuyenKhoanMoTa: '受講生に振込先を知らせるために表示します。本システムは決済処理を行いません。',
    soTaiKhoan: '口座番号',
    soTaiKhoanGoiY: '例: 0123456789',
    tenNganHang: '銀行',
    tenNganHangGoiY: '例: Vietcombank',
    chuTaiKhoan: '口座名義',
    chuTaiKhoanGoiY: '銀行アプリに表示されるとおりの名義',
    chuTaiKhoanLuuY: '振込を誤らないよう、振込者は名義を一致させる必要があります。',
    anhQr: '振込用QRコード',
    anhQrGoiY: 'ご利用の銀行アプリから取得してください。',
  },
  loi: {
    KHONG_TIM_THAY_TRUNG_TAM: 'このコードのセンターは存在しません。センターコードをご確認ください（7文字、数字の0と1は含みません）。',
    MA_TRUNG_TAM_KHONG_HOP_LE: 'センターコードが正しくありません — 7文字で、0/O/1/I/L は含みません',
    BAI_TAP_DA_CO_BAI_NOP: 'この課題はすでに受講生が提出しています — 削除できません。提出物は受講生の学習成果です。',
    LOP_HOC_KHONG_HOP_LE: 'クラスが無効であるか、そのクラスに対する権限がありません',
    LOAI_DINH_KEM_KHONG_HO_TRO: '対応していない添付種別です',
    TAN_SUAT_TRONG: '曜日が1つも選択されていません',
    NGAY_KHONG_HOP_LE: '日付が正しくありません。スケジュール生成の開始日を選び直してください。',
    KHACH_HANG_TRUNG_SO_DIEN_THOAI: 'この電話番号は他の顧客がすでに使用しています。番号で検索し、既存の顧客を編集してください。',
    KHACH_HANG_DA_CO_DANG_KY: 'この顧客にはすでにコースの申込があります — 売上データのため削除できません。',
    KHACH_HANG_KHONG_HOP_LE: '顧客が無効です',
    KHOA_ONLINE_KHONG_HOP_LE: 'オンラインコースが無効です',
    KHOA_ONLINE_DA_CO_NGUOI_HOC: 'このコースにはすでに受講者がいるため削除できません。新規付与を止めるには「新規受付停止」に切り替えてください。',
    KHOA_ONLINE_KHONG_NHAN_GHI_DANH: '受講権限を付与できるのは公開中のコースのみです。下書きのコースにはまだ内容がなく、新規受付停止のコースは新たな受講者を受け付けません。',
    BAI_HOC_KHONG_DOI_DUOC_KHOA: 'レッスンを別のコースへ移動することはできません。',
    KHONG_XAC_DINH_DUOC_NGUOI_DUNG: '現在のユーザーを特定できません。',
    KHACH_HANG_DA_NOI_HO_SO_KHAC: 'この顧客はすでに別のプロフィールに紐づけられています。新しいプロフィールを作成せず、そのプロフィールを開いてください。',
    KHOA_HOC_TRUNG_TEN: '同じ名前のコースがすでに存在します',
    KHOA_HOC_DA_CO_DANG_KY: 'このコースにはすでに申込があるため削除できません。販売履歴を残したまま販売を停止するには「このコースを販売中」のチェックを外してください。',
    KHOA_HOC_KHONG_HOP_LE: 'コースが無効です',
    SAN_PHAM_KHONG_HOP_LE: '商品が無効です',
    SAN_PHAM_TRUNG_TEN: '同じ名前の商品がすでに存在します',
    SAN_PHAM_DA_CO_DON_HANG: 'この商品にはすでに注文があるため削除できません。注文履歴を残したまま販売を停止するには「この商品を販売中」のチェックを外してください。',
    PHAI_CHON_DUNG_MOT_MAT_HANG: 'コースまたは商品のいずれか1点のみを選択してください。',
    TY_GIA_KHONG_HOP_LE: '為替レートは0より大きい値を入力してください',
    THU_VUOT_CAM_KET: '入金合計額が顧客の支払い約定額を超えています。金額をご確認ください — 0を1つ多く入力しているケースがよくあります。',
    DANG_KY_KHONG_HOP_LE: '申込が無効です',
    SO_TIEN_KHONG_HOP_LE: '金額が正しくありません',
    GIO_KET_THUC_KHONG_HOP_LE: '終了時刻は開始時刻より後にしてください（日をまたぐクラスには対応していません）',
    SO_BUOI_KHONG_HOP_LE: '授業回数は1〜500の範囲で入力してください',
    NGAY_KET_THUC_TRUOC_KHAI_GIANG: '終了日は開講日より後にしてください',
    DIEU_KIEN_DUNG_KHONG_HOP_LE: '終了条件は授業回数または日付のいずれか1つを選択してください',
    KHONG_SINH_DUOC_BUOI_NAO: '授業を1件も生成できませんでした — 曜日と日付の範囲をご確認ください',
    CHAN_TREN_SINH_BUOI: '指定された期間内では必要な授業回数を確保できません',
    GIO_KHONG_TON_TAI_DO_DOI_GIO: 'サマータイムの切り替えにより、この時刻は存在しません',
    LICH_DA_CO_DIEM_DANH: 'このクラスにはすでに出欠が記録された授業があります — スケジュールを再生成するとデータが失われます。再生成せず、授業を個別に修正してください。',
    BUOI_DA_HUY: 'この授業は中止されています',
    HOC_VIEN_KHONG_THUOC_LOP: 'この受講生はこのクラスに所属していません',
    KHONG_THUOC_LOP_NAY: 'あなたはこのクラスに所属していません',
    NGOAI_KHUNG_GIO_DIEM_DANH: '出欠受付時間外です（授業開始15分前から授業終了時刻まで受け付けます）',
    THIEU_LY_DO_VANG: '欠席には理由の入力が必要です',
    NHAN_SU_KHONG_HOP_LE: '無効な職員が含まれています（退職済みまたは存在しません）',
    GIAO_VIEN_TRUNG_TRO_GIANG: 'メイン講師が同じクラスのアシスタント講師を兼任することはできません',
    CHUA_CHON_HINH_THUC_HOC: '受講形式が選択されていません',
    HOC_PHI_AM: '授業料に負の値は入力できません',
    SUC_CHUA_KHONG_HOP_LE: '定員は0より大きい値を入力してください',
    LOP_DA_HOAN_TAT: 'このクラスはすでに完了しているため、再度完了する必要はありません',
    CHUA_NHAP_HOC_PHI: 'クラスを完了する前に授業料を入力してください',
    CHI_XOA_DUOC_LOP_NHAP: '削除できるのは下書き状態のクラスのみです。開講済みのクラスは、履歴を残すためクラス中止をご利用ください。',
    CHUA_CHON_HOC_VIEN: '受講生が1人も選択されていません',
    HOC_VIEN_KHONG_HOP_LE: '受講生が無効です（退会済みまたは存在しません）',
    HOC_VIEN_DA_TRONG_LOP: 'この受講生はすでにこのクラスに在籍しています',
    KHOA_HOC_KHONG_KHOP_LOP: '注文のコースが、このクラスで教えるコースと一致しません',
    VUOT_SO_KHOA_HOC_CUA_LOP: '1つのクラスに割り当てられるコースは最大3件までです',
    VUOT_SUC_CHUA: 'クラスの定員を超えています',
    CHI_KHOA_HOC_MOI_XEP_LOP: 'クラス分けの申請を送信できるのはコース購入の注文のみです',
    DA_GUI_YEU_CAU_XEP_LOP: 'この注文はすでにクラス分けの申請を送信済みです',
    YEU_CAU_KHONG_HOP_LE: 'クラス分けの申請が無効であるか、すでに削除されています',
    YEU_CAU_DA_XU_LY: 'この申請はすでに処理済みです。一覧を再読み込みしてください',
    CHUA_NHAP_LY_DO_TU_CHOI: '却下の理由を入力してください',
    PHONG_BAN_TRUNG_TEN: 'この階層には同じ名前の部門がすでに存在します',
    CHUC_VU_TRUNG_TEN: 'センター内に同じ名前の役職がすでに存在します',
    CHUC_VU_CON_NGUOI_GIU: 'この役職には現在就いている人がいます — 履歴を残したまま使用を停止するには「使用中」のチェックを外してください',
    CHUC_VU_KHONG_HOP_LE: '役職が存在しません',
    PHONG_BAN_CON_NGUOI: 'この部門にはまだ職員が所属しています — 削除する前に他の部門へ異動させてください',
    PHONG_BAN_CON_CAP_DUOI: 'この部門には下位部門が残っています — 下位から順に削除してください',
    PHONG_BAN_CHU_TRINH: 'この部門を自分自身の下位部門に設定することはできません',
    PHONG_BAN_KHONG_HOP_LE: '部門が存在しません',
    NGUOI_QUAN_LY_KHONG_HOP_LE: '管理者が無効です（退職済み、または受講生です）',
    HOC_VIEN_KHONG_VAO_CO_CAU: '受講生は組織構造に含まれません',
    CHUA_CHON_NHAN_SU: '職員が1人も選択されていません',
    LOAI_TEP_KHONG_HO_TRO: 'PDF、Word、Excel、PowerPoint、画像、圧縮ファイルのみ受け付けます',
    LOAI_TEP_HO_SO_KHONG_HO_TRO: '職員の書類はPDF、Word、Excelのみ受け付けます',
    VUOT_SO_TEP_HO_SO: '1つのプロフィールに保存できるファイルは最大10件です — 古いファイルを削除してから再度お試しください。',
    TIEU_CHI_THIEU_TEN: '評価基準には名称が必要です。',
    TIEU_CHI_TEN_QUA_DAI: '評価基準の名称が長すぎます（最大200文字）。',
    TIEU_CHI_TRUNG_TEN: 'このグループには同じ名前の評価基準がすでに存在します。',
    TIEU_CHI_NHOM_KHONG_HOP_LE: '評価基準のグループが無効です。',
    TIEU_CHI_DA_CHAM_KHONG_DOI_NHOM: 'この評価基準はすでに採点に使われているため、グループを変更できません — 変更すると採点済みのすべての期間が不正確になります。この基準の使用を停止し、別のグループに新しい基準を作成してください。',
    TIEU_CHI_KHONG_THUOC_NHOM: '営業グループに属さない評価基準が含まれています。',
    DIEM_TIEU_CHI_KHONG_HOP_LE: '点数は1〜5の範囲で入力してください。',
    KY_DANH_GIA_KHONG_HOP_LE: '評価期間は yyyy-MM 形式で入力してください（例: 2026-09）。',
    KHONG_PHAI_NHAN_VIEN_KINH_DOANH: '採点できるのは営業担当者のみです。',
    TEN_TEP_KHONG_HOP_LE: 'ファイル名が正しくありません — 1文字以上入力してください。',
    TEP_QUA_LON: 'ファイルが大きすぎます。最大20 MBです',
    TEP_RONG: 'ファイルが空です',
    LOAI_ANH_KHONG_HO_TRO: '画像はJPG、PNG、WebP、GIFのみ受け付けます',
    ANH_QUA_LON: '画像が大きすぎます。最大5 MBです',
    ANH_RONG: '画像ファイルが空です',
    DANG_NHAP_THAT_BAI: 'センターコード、ユーザー名、またはパスワードが正しくありません',
    TAI_KHOAN_BI_VO_HIEU_HOA: 'このアカウントは無効化されています',
    TAI_KHOAN_BI_KHOA_TAM: 'パスワードの誤入力が続いたため、アカウントを一時的にロックしました。しばらくしてから再度お試しいただくか、「パスワードをお忘れの方」をご利用ください。',
    PHAI_DOI_MAT_KHAU: '続行する前にパスワードを変更してください',
    MAT_KHAU_CU_KHONG_DUNG: '現在のパスワードが正しくありません',
    TOKEN_DAT_LAI_KHONG_HOP_LE: '再設定用のコードが無効か、有効期限が切れています',
    PHIEN_DA_BI_DAY_RA: 'このアカウントは別の場所でログインされたため、お客様のセッションは終了しました。心当たりがない場合は、再度ログインしてパスワードを変更してください。',
    CHUA_XAC_THUC: 'ログインが必要です',
    KHONG_DU_QUYEN: 'この操作を実行する権限がありません',
    TOKEN_THIEU_TENANT: 'ログインセッションが無効です。再度ログインしてください',
    KHONG_TIM_THAY: 'データが見つかりません',
    DU_LIEU_KHONG_HOP_LE: '入力されたデータが正しくありません',
    TRUNG_TAM_PHAI_CON_NGUOI_PHAN_QUYEN: 'センターには権限管理の権限を持つ人が少なくとも1人必要です。先に他の人へその権限を付与してから、再度お試しください。',
    KHONG_TU_KHOA_TAI_KHOAN_CHINH_MINH: 'ログイン中の自分のアカウントをロックすることはできません。チェックを外してから再度お試しください。',
    QUA_NHIEU_YEU_CAU: '操作が速すぎます。少し時間をおいてから再度お試しください。',
    LOI_HE_THONG: 'エラーが発生しました。再度お試しください',
    USERNAME_DA_TON_TAI: 'このユーザー名はセンター内ですでに使用されています',
    QUYEN_KHONG_HOP_LE: '権限グループが無効です',
    QUYEN_DANG_DUOC_GAN: '削除できません: この権限グループはアカウントに割り当てられています',
    KHONG_TU_XOA_TAI_KHOAN_CUA_MINH: '自分自身のアカウントを削除することはできません',
    KHONG_TU_VO_HIEU_HOA_MINH: '自分自身のアカウントを無効化することはできません',
    CHUC_NANG_KHONG_HOP_LE: '機能が無効です',
    MAT_KHAU_QUA_NGAN: 'パスワードは12文字以上で入力してください',
    MAT_KHAU_QUA_DAI: 'パスワードが長すぎます（最大128文字）',
    MAT_KHAU_MOI_TRUNG_CU: '新しいパスワードは現在のパスワードと異なるものにしてください',
    USERNAME_KY_TU_KHONG_HOP_LE: 'ユーザー名に使用できるのは英字、数字、および . _ - のみです',
    ID_KHONG_KHOP: 'データが一致しません',
    NGUOI_DUOC_CHAM_KHONG_DUNG_LOP: '採点対象者はこの授業を担当していません。ページを再読み込みしてから再度お試しください。',
    TRANG_THAI_KHONG_HOP_LE: '授業のステータスが正しくありません。',
    BUOI_HOC_DA_KHOA: 'この授業は確定済みのため、編集・中止・削除はできません。確定済みの授業の出欠は出席状況の証跡となります。',
    BUOI_HOC_DA_CO_DIEM_DANH: 'この授業にはすでに出欠が記録されています。データを残すため、削除ではなく中止にしてください。',
    BUOI_HOC_DA_CO_NHAN_XET: 'この授業にはすでに受講生のコメントがあります。フィードバックを残すため、削除ではなく中止にしてください。',
    BUOI_HOC_TRUNG_GIO: '現在のスケジュールと時間が重複する授業があります。最後の授業より後の日付を開始日に選んでください。',
    NGUOI_DUNG_KHONG_HOP_LE: 'ユーザーが無効です',
    KHONG_PHAI_NHAN_SU: '職員画面で管理できるのは一般職員、講師、アシスタント講師のみです。受講生はLMS側の受講生画面で管理します。',
    KHONG_PHAI_HOC_VIEN: '受講生画面で管理できるのは受講生のみです。一般職員、講師、アシスタント講師はHRM側の職員画面で管理します。',
    NGUOI_DUNG_DA_CO_TAI_KHOAN: 'この方はすでにアカウントをお持ちです。1人につきログインアカウントは1つのみです。',
    NGUOI_DUNG_DANG_CO_DU_LIEU: '削除できません: この方にはクラス、出欠、または授業料のデータがあります。データを残すため、削除ではなく「退会・退職済み」に設定してください。',
    SO_TIEN_PHAI_DUONG: '金額は0より大きい値を入力してください',
  },
}

export default ja
