/**
 * **한국어 (tiếng Hàn) — dịch từ `vi.ts`** (23/09/2026).
 *
 * Sinh bằng `scripts/sinh-tep-ngon-ngu.py` để cấu trúc khoá **luôn khớp `vi.ts`**.
 * Sửa tay được, nhưng đừng thêm/bớt khoá ở đây — thêm ở `vi.ts` trước, vì
 * `check-i18n-keys.py` so mọi ngôn ngữ với tệp đó.
 *
 * Chỉ dịch GIAO DIỆN. Dữ liệu người dùng nhập (tên lớp, tên học viên, ghi chú)
 * giữ nguyên — xem `danhSach.ts`.
 */
const ko = {
  chung: {
    tieuDeTab: 'LangCenter — 어학 센터 관리',
    xacNhanLuu: '저장 확인',
    xemChiTiet: '상세 보기',
    ghiChu: '비고',
    dangPhatTrien: '개발 중인 모듈입니다',
    dangPhatTrienGoiY: '이 모듈의 권한 관리와 메뉴 이동은 이미 작동합니다 — 지금부터 그룹에 권한을 부여할 수 있어요. 세부 업무 기능은 추후 추가됩니다.',
    xacNhanThem: '추가 확인',
    hoiLuu: '"{{ten}}"의 변경 사항을 저장할까요? 현재 정보는 덮어쓰여집니다.',
    hoiThem: '"{{ten}}"을(를) 새로 추가할까요?',
    hoiLuuChung: '변경 사항을 저장할까요?',
    hoiThemChung: '이 항목을 새로 추가할까요?',
    dangTai: '불러오는 중…',
    tatCa: '전체',
    dongY: '확인',
    luu: '저장',
    huy: '취소',
    them: '추가',
    sua: '수정',
    xoa: '삭제',
    timKiem: '검색',
    thaoTac: '작업',
    khongCoDuLieu: '데이터가 없습니다',
    xacNhanXoa: '정말 삭제할까요?',
    dangXuat: '로그아웃',
    quayLai: '뒤로',
    dong: '닫기',
    moMenu: '메뉴 열기',
    moSidebar: '사이드바 펼치기',
    thuGonSidebar: '사이드바 접기',
    daLuu: '저장되었습니다',
    taiVe: '다운로드',
    xem: '보기',
  },
  dangKy: {
    tieuDe: '센터 등록',
    moTa: '센터 이름을 입력하면 시스템이 센터 코드를 발급해 드려요',
    nut: '센터 만들기',
    thanhCong: '센터를 만들었습니다',
    maTrungTamCuaBan: '내 센터 코드',
    saoChep: '복사',
    giaiThichMa: '센터 코드는 시스템이 발급하는 7자리 문자이며, 로그인할 때 사용합니다.',
    canhBaoLuuMa: '센터 코드를 꼭 적어 두세요. 로그인할 때마다 필요하며, 직접 다시 조회할 수 없습니다.',
    luuYDoiMatKhau: '첫 로그인 시 비밀번호를 변경해야 합니다.',
    chuaMo: '등록이 열려 있지 않습니다',
    chuaMoMoTa: '이 시스템은 아직 자유 등록을 열지 않았습니다. 센터 개설은 관리자에게 문의하세요.',
    veDangNhap: '← 로그인 화면으로',
  },
  ngonNgu: {
    doi: '언어 변경',
    nhan: '언어',
  },
  linhVat: {
    tat: '캐릭터 숨기기',
    thoai: [
      '오늘도 즐겁게 가르치고 배우는 하루 되세요!',
      '페이지를 닫기 전에 저장하는 거 잊지 마세요.',
      '커피 한잔 하셨어요? 잠깐 쉬는 것도 좋아요.',
      '오늘 수업은 어땠나요?',
      '저는 잠깐 산책 좀 할게요, 하던 일 계속하세요.',
      '데이터가 깔끔하면 월말이 훨씬 편해져요.',
      '어려운 게 있으면 관리자에게 물어보세요!',
      '한 글자를 배워도 스승이래요 — 오늘도 좋은 수업 하세요!',
    ],
  },
  dangNhap: {
    tieuDe: '로그인',
    moTa: '센터 코드, 아이디, 비밀번호를 입력하세요',
    maTrungTam: '센터 코드',
    tenPhanMem: 'LangCenter',
    bannerTieuDe: '어학 센터 관리 시스템',
    bannerMoTa: '센터 코드를 입력해 시작하세요. 반, 수강생, 출석, 수강료를 하나의 시스템에서 관리합니다.',
    banQuyen: '© {{nam}} LangCenter · GiapTex가 개발한 소프트웨어입니다',
    banQuyenCoTen: '© {{nam}} {{ten}} · GiapTex가 개발한 소프트웨어입니다',
    maTrungTamGoiY: '7자리, 대소문자 구분 없음',
    dangTraTenTrungTam: '센터 코드를 조회하는 중…',
    khongTimThayTrungTam: '해당하는 센터를 찾을 수 없습니다',
    chuaCoTrungTam: '아직 센터가 없으신가요?',
    username: '아이디',
    matKhau: '비밀번호',
    nut: '로그인',
    nhoDangNhap: '센터 코드와 아이디 기억하기',
    quenMatKhau: '비밀번호를 잊으셨나요?',
    doiMatKhauTieuDe: '비밀번호 변경',
    doiMatKhauMoTa: '시스템에 들어가기 전에 계정 비밀번호를 변경해야 합니다',
    matKhauCu: '현재 비밀번호',
    matKhauMoi: '새 비밀번호',
    xacNhanMatKhau: '새 비밀번호 확인',
    quenTieuDe: '비밀번호 찾기',
    quenMoTa: '등록된 이메일을 입력하면 비밀번호 재설정 코드를 보내드립니다',
    email: '이메일',
    guiYeuCau: '요청 보내기',
    daGuiEmail: '시스템에 해당 이메일이 있다면 재설정 코드를 메일함으로 보냈습니다.',
    maDatLai: '재설정 코드',
    datLaiMatKhau: '비밀번호 재설정',
  },
  menu: {
    tongQuan: '대시보드',
    daoTao: '교육',
    nhanSu: '인사',
    khachHang: '고객',
    nhanVienKinhDoanh: '영업 담당자',
    giaoVienNhanSu: '강사',
    nhanSuNguoiDung: '직원 인사 정보',
    coCauToChuc: '조직도',
    chucVu: '직위',
    hocVien: '수강생',
    doanhThu: '매출',
    khachHangDs: '고객',
    khoaHoc: '과정',
    sanPham: '상품',
    lopHoc: '반',
    choXepLop: '반 배정 대기',
    taiLieu: '자료',
    khoaOnline: '온라인 과정',
    thongKeCrm: '통계',
    hocPhi: '수강료',
    quanTri: '시스템 관리',
    taiKhoan: '계정',
    nguoiDung: '사용자',
    phanQuyen: '권한 관리',
    thietLap: '일반 설정',
    nhatKy: '시스템 로그',
  },
  hocPhi: {
    hoiThu: '{{soTien}} 수납을 기록할까요? 수강생의 미납금이 그만큼 줄어듭니다.',
    hoiSua: '수납 금액을 {{soTien}}(으)로 수정할까요? 미납금은 새 금액으로 다시 계산됩니다.',
    tabCongNo: '미납금',
    tabSoThu: '수납 내역',
    thuTien: '수납',
    suaKhoanThu: '수납 내역 수정',
    xoaKhoanThu: '수납 내역 삭제',
    xacNhanXoa: '{{hocVien}}의 {{soTien}} 수납 내역을 삭제할까요? 미납금이 그만큼 다시 늘어납니다.',
    lop: '반',
    tatCaLop: '전체 반',
    chonLop: '반 선택',
    hocVien: '수강생',
    chonHocVien: '수강생 선택',
    hocPhi: '수강료',
    daThu: '수납액',
    tongPhaiThu: '총 청구액',
    tienDoThu: '수납 진행률',
    khongCoQuyenXem: '수강료 정보를 볼 권한이 없습니다. 반 전체의 수강료는 관리자만 조회할 수 있으며, 수강생은 본인의 미납금만 볼 수 있습니다.',
    conNo: '미납',
    conNoNhan: '미납',
    daDuUpper: '완납',
    quaHan: '기한 초과',
    chiConNo: '미납자만 보기',
    khongCoCongNo: '필터 조건에 맞는 미납금이 없습니다',
    chuaCoKhoanThu: '기록된 수납 내역이 없습니다',
    soTien: '금액',
    ngayThu: '수납일',
    phuongThuc: '수납 방식',
    soPhieu: '전표 번호',
    ghiChu: '비고',
    nguoiThu: '수납자',
    pt: {
      TienMat: '현금',
      ChuyenKhoan: '계좌 이체',
      Khac: '기타',
    },
  },
  nguoiDung: {
    gomPhongCon: '하위 부서 포함',
    themNguoiDung: '사용자 추가',
    suaNguoiDung: '사용자 수정',
    timTheo: '이름, 이메일, 전화번호',
    trangThaiNhanSu: '재직 상태',
    DangLamViec: '재직 중',
    DaNghi: '퇴사',
    hoSo: '인적 정보',
    hoSo_GiaoVien: '강사 정보',
    hoSo_HocVien: '수강생 정보',
    hoSo_NhanVien: '직원 정보',
    bangCap: '학위 및 자격',
    chuyenMon: '전공 분야',
    ngayVaoLam: '입사일',
    truongLop: '학교 / 학년',
    khachHangCrm: '고객 (CRM)',
    khachHangCrmChon: '기존 고객 선택…',
    khachHangCrmGoiY: '선택 사항 — CRM에서 이미 구매한 고객과 이 정보를 연결하면 같은 사람이 중복 등록되지 않습니다.',
    tenPhuHuynh: '보호자 이름',
    sdtPhuHuynh: '보호자 연락처',
    chucVu: '직위',
    chuaGanChucVu: '직위 미지정',
    ngaySinh: '생년월일',
    diaChi: '주소',
    cccd: '주민등록증 / 신분증 번호',
    soTaiKhoan: '계좌번호',
    tenNganHang: '은행',
    lienKetMxh: '소셜 미디어 링크',
    duongDanMxh: '링크 또는 전화번호…',
    themMxh: '링크 추가',
    tepHoSo: '첨부 서류',
    taiTep: '파일 업로드',
    chuaCoTep: '아직 파일이 없습니다 — 근로 계약서, 자격증 스캔본, 신분증 스캔본 등',
    gioiHanTep: 'PDF, Word, Excel만 가능 · 파일당 최대 20 MB',
    soTepDaDung: '{{so}}/{{toiDa}}개 파일 사용 중',
    datTenTep: '파일 이름 지정',
    doiTenTep: '파일 이름 변경',
    tenHienThi: '표시 이름',
    viDuTenTep: '예: 2026년 근로 계약서',
    giuDuoiTep: '확장자는 입력하지 않아도 됩니다 — 시스템이 자동으로 유지합니다 (.pdf, .docx 등)',
    hoiXoaTep: '"{{ten}}" 파일을 삭제할까요? 복구할 수 없습니다.',
    phongBan: '부서',
    chuaXepPhongBan: '조직도에 미배치',
    taiKhoan: '계정',
    chuaCoTaiKhoan: '없음',
    nguoiSoHuu: '사용자',
    khongGanAi: '연결 안 함',
    taoTaiKhoanDangNhap: '로그인 계정 만들기',
    khongCanDangNhap: '이 사람은 로그인할 수 없습니다. 계정 탭에서 나중에 계정을 만들어 줄 수 있어요.',
    giaiThichGanNguoi: '특정인에게 속하지 않는 기술용 계정이라면 비워 두세요.',
    hoiXoa: '사용자 "{{ten}}"을(를) 삭제할까요? 복구할 수 없습니다. 이미 데이터가 쌓인 사람이라면 삭제 대신 "퇴사"로 표시하세요.',
    giaiThichVoHieuHoa: '비활성화는 로그인만 막습니다. 이 사람의 인적 정보와 모든 데이터는 그대로 유지됩니다.',
  },
  nhatKy: {
    timTheo: '명령 이름, 수행자',
    module: '모듈',
    hanhDong: '동작',
    thoiDiem: '시각',
    nguoiThucHien: '수행자',
    thaoTac: '명령',
    soBanGhi: '건수',
    ketQua: '결과',
    thanhCong: '성공',
    thatBai: '실패',
    chiThatBai: '실패한 작업만 보기',
    khongCoBanGhi: '기록된 작업이 없습니다',
    xemChiTiet: '상세 보기',
    truongDaDoi: '변경된 항목',
    thamSo: '명령 매개변수',
    diaChiIp: 'IP',
  },
  hanhDongNhatKy: {
    Them: '추가',
    Sua: '수정',
    Xoa: '삭제',
    XacThuc: '인증',
    Khac: '기타',
  },
  thongKe: {
    loaiThongKe: '통계 기준',
    kyMacDinh: '기본 기간',
    khoangSai: '시작일은 종료일보다 앞서거나 같아야 합니다.',
    loai: {
      KhoaHoc: '과정',
      SanPham: '상품',
      Elearning: '온라인 학습',
      DoiNhom: '팀',
    },
    loaiMoTa: {
      KhoaHoc: '판매된 과정별 매출입니다.',
      SanPham: '상품별 매출 — 교재, 학습 도구 등.',
      Elearning: '',
      DoiNhom: '고객 정보를 등록한 사람을 기준으로 한 부서별 매출입니다.',
    },
    locTheo: {
      KhoaHoc: '선택한 과정만',
      SanPham: '선택한 상품만',
      Elearning: '',
      DoiNhom: '선택한 팀만',
    },
    boLoc: '필터 해제',
    dangLoc: '{{so}}개 항목으로 필터링 중 — 이 화면의 모든 수치는 선택한 항목만 계산합니다.',
    elearningMoTa: '금액이 아닌 건수만 측정합니다: 온라인 과정은 주문과 연결되지 않고, 관리자가 수동으로 수강 권한을 부여합니다.',
    chuaCoKhoaMo: '열려 있는 온라인 과정이 없습니다. 임시저장 상태의 과정은 여기에 집계되지 않습니다 — 강의 작성을 마치면 "공개 중"으로 바꾸세요.',
    elearningGoiY: '학습 관련 수치는 위쪽 줄에 있습니다. 온라인 학습 매출은 설계상 존재하지 않습니다.',
    soKhoaOnline: '공개 중인 과정',
    soNguoiHoc: '수강 중인 인원',
    soLuotGhiDanh: '등록 건수',
    tyLeHoanThanh: '수료율',
    baiTrenTong: '{{da}}/{{tong}}강',
    tongDoanhThu: '총 매출',
    soDon: '주문 수',
    giaTriDonTb: '평균 주문 금액',
    daThu: '수납액',
    conThieu: '{{so}} 부족',
    thuDu: '전액 수납',
    soKyTruoc: '이전 기간 대비',
    chuaCoKyTruoc: '비교할 이전 기간이 없습니다',
    soDonNgan: '{{so}}건',
    khongXacDinh: '미지정',
    chuaCoDon: '이 기간에 주문이 없습니다',
    chuaCoKhach: '고객이 없습니다',
    doanhThuTheoThang: '월별 매출',
    doanhThuTheoThangMoTa: '등록 시점에 저장된 환율로 VND 환산 — 과거 보고서의 수치는 바뀌지 않습니다.',
    theoCaNhan: '담당자별 매출',
    theoCaNhanMoTa: '고객 정보를 등록한 사람 기준으로 계산합니다. 등록자가 없는 과거 주문은 "미지정"으로 묶입니다.',
    theoDoiNhom: '팀별 매출',
    theoDoiNhomMoTa: '고객 정보를 등록한 사람의 부서 기준입니다.',
    theoSanPham: '품목별 매출',
    theoSanPhamMoTa: '과정과 기타 상품을 모두 포함합니다.',
    theoNguon: '고객 유입 경로별 매출',
    theoNguonMoTa: '고객이 직접 등록한 경우는 누구의 개인 실적에도 포함되지 않습니다.',
    pheu: '영업 퍼널',
    pheuMoTa: '각 단계에 머무는 고객 수와 전체 고객 대비 비율입니다.',
  },
  nguonKhachHang: {
    NhanVienTao: '직원 등록',
    TuDangKy: '고객 직접 등록',
  },
  khoaOnline: {
    ten: '과정명',
    trangThai: '상태',
    moTa: '설명',
    chuaCo: '온라인 과정이 없습니다',
    chuaCoBai: '이 과정에는 아직 강의가 없습니다',
    chuaCoHocVien: '수강 권한을 부여받은 사람이 없습니다',
    themKhoa: '온라인 과정 추가',
    suaKhoa: '과정 수정',
    soBaiHoc: '강의 수',
    soHocVien: '수강생',
    tienDo: '진도',
    taoRaLaNhap: '새 과정은 항상 임시저장 상태로 생성됩니다 — 강의 작성을 마치면 공개 중으로 바꾸세요.',
    dangNhapGoiY: '이 과정은 임시저장 상태라 수강생에게 보이지 않고, 수강 권한도 부여할 수 없습니다. 강의 작성을 마쳤다면 과정을 수정해 공개 중으로 바꾸세요.',
    tabBaiHoc: '강의',
    tabHocVien: '수강생',
    themBai: '강의 추가',
    suaBai: '강의 수정',
    xoaBai: '강의 삭제',
    xoaBaiHoi: '"{{ten}}" 강의를 삭제할까요? 이 강의에 대한 수강생의 학습 진도도 함께 사라집니다.',
    tieuDeBai: '강의 제목',
    thuTu: '순서',
    noiDung: '내용',
    baiTrong: '이 강의에는 아직 내용이 없습니다.',
    congKhai: '공개',
    congKhaiGoiY: '로그인한 사람은 등록하지 않아도 모두 볼 수 있습니다 — 기한이 지난 뒤에도 마찬가지입니다. 소개 강의나 맛보기 강의에 사용하세요.',
    danhDauDaHoc: '수강 완료로 표시',
    capQuyen: '수강 권한 부여',
    hoiTaoKhoa: '이 온라인 과정을 만들까요? 새 과정은 임시저장 상태라 아직 아무에게도 보이지 않습니다.',
    hoiLuuKhoa: '이 과정의 변경 사항을 저장할까요?',
    hoiLuuBai: '이 강의를 저장할까요?',
    hoiCapQuyen: '선택한 수강생에게 이 과정의 수강 권한을 부여할까요?',
    thuQuyen: '수강 권한 회수',
    thuQuyenHoi: '{{ten}}의 수강 권한을 회수할까요? 학습 진도는 그대로 남아 있어 다시 부여하면 이어서 학습할 수 있습니다.',
    hocVien: '수강생',
    hetHan: '만료일',
    hetHanGoiY: '비워 두면 = 무기한 수강.',
    ghiChuCap: '비고',
    ghiChuVd: '예: 주문 #123 구매, 체험 수강, IELTS 반 사은품',
    nguoiCap: '부여한 사람',
    vinhVien: '무기한',
  },
  trangThaiKhoaOnline: {
    Nhap: '임시저장',
    DangMo: '공개 중',
    NgungCapMoi: '신규 부여 중단',
  },
  tongQuan: {
    viecCanLam: '할 일',
    khongCoViec: '처리할 일이 없습니다',
    buoiHomNay: '오늘 수업',
    buoiSapToi: '다가오는 수업',
    buoiThu: '{{so}}차시',
    lopDangHoatDong: '운영 중인 반',
    buoiQuaHan: '출석이 확정되지 않은 지난 수업',
    baiChuaCham: '채점하지 않은 제출물',
    choXepLop: '반 배정 대기 수강생',
    chuaCoNoiDung: '시스템이 기본 상태입니다 — 아직 설정된 업무 기능이 없습니다. 센터의 계정과 권한 그룹을 만드는 것부터 시작하세요.',
  },
  phanTrang: {
    dangXem: '전체 {{tong}}건 중 {{tu}}–{{den}} 표시',
    soDong: '행 수',
    trangTruoc: '이전 페이지',
    trangSau: '다음 페이지',
  },
  anh: {
    chonAnh: '이미지 선택',
    doiAnh: '이미지 변경',
    goAnh: '이미지 제거',
    goiY: 'JPG, PNG, WebP 또는 GIF · 최대 5 MB',
  },
  loaiNguoiDung: {
    NhanVien: '기타 직원',
    NhanVienKinhDoanh: '영업 담당자',
    GiaoVien: '강사',
    TroGiang: '보조강사',
    HocVien: '수강생',
  },
  lopHoc: {
    hoiThemHocVien: '이 반에 수강생 {{soLuong}}명을 등록할까요?',
    hoiGoHocVien: '"{{ten}}"을(를) 반에서 제외할까요? 이미 기록된 출석과 수강료는 그대로 유지됩니다.',
    tieuDe: '반',
    themMoi: '반 추가',
    ten: '반 이름',
    giaoVienChinh: '담당 강사',
    troGiang: '보조강사',
    hinhThuc: '수업 형태',
    phongHoc: '강의실',
    linkHoc: '온라인 수업 링크',
    hocPhi: '수강료',
    sucChuaToiDa: '최대 정원',
    khongGioiHan: '제한 없음',
    ngayKhaiGiang: '개강일',
    ngayKetThuc: '종강일',
    trangThai: '상태',
    ghiChu: '비고',
    soHocVien: '수강생',
    hocVien: '반 수강생',
    xemThongTin: '정보 보기',
    hocVienCuaLop: '{{lop}} 반 수강생',
    nhanVienKinhDoanh: '영업 담당자',
    themTrucTiep: '또는 기존 수강생 추가',
    themTrucTiepGiaLop: '적용 수강료는 반의 기준 금액을 따릅니다',
    themHocVien: '수강생 추가',
    goHocVien: '반에서 제외',
    hocPhiApDung: '적용 수강료',
    ngayVaoLop: '반 배정일',
    hoanTat: '반 확정',
    huyLop: '반 취소',
    xacNhanHuy: '이 반을 취소할까요? 출석 이력과 수강료는 그대로 유지됩니다.',
    chuaCoLop: '개설된 반이 없습니다',
    chonGiaoVien: '강사 선택…',
    timGiaoVien: '강사 이름을 입력해 검색…',
    khoaHocCuaLop: '이 반이 가르치는 과정',
    chuaGanKhoa: '지정된 과정 없음',
    toiDaNKhoa: '(최대 {{so}}개)',
    chonKhoaHoc: '과정 선택...',
    timKhoaHoc: '과정 검색',
    daDatToiDaKhoa: '최대 {{so}}개 과정에 도달했습니다',
    chonTroGiang: '보조강사 선택…',
    timTroGiang: '보조강사 이름을 입력해 검색…',
    timHocVien: '수강생 이름을 입력해 검색…',
    locTrangThai: '상태로 필터',
    nhapGoiY: '임시저장 반은 본인에게만 보입니다. "반 확정"을 눌러 공개하세요.',
    xemChiTiet: '상세 보기',
    siSo: '인원',
    buoiDaHoc: '진행한 수업',
    thoiGian: '시간',
    tabLichTatCa: '수업 일정',
    locTheoLop: '반으로 필터',
    lichTuNgay: '시작일',
    lichDenNgay: '종료일',
    lichXoaLoc: '필터 해제',
    dangLocKhoangNgay: '기간으로 필터링 중 — 달력의 월 이동 버튼으로는 데이터가 바뀌지 않습니다. 월별로 보려면 필터를 해제하세요.',
    tabDanhSach: '반 목록',
    tabTongQuan: '개요',
    tabHocVien: '수강생',
    tabLich: '일정 및 출석',
    tabBaiTap: '과제',
    tabHocPhi: '수강료',
    tabTaiLieu: '자료',
    suaThongTin: '반 정보 수정',
    luuThongTin: '반 정보 저장',
    daChon: '{{soLuong}}명 선택됨',
    sucChuaConLai: '{{daChon}}명 선택 / 최대 {{toiDa}}명',
  },
  hinhThucHoc: {
    ChuaChon: '— 선택 —',
    Online: '온라인',
    Offline: '대면',
    KetHop: '혼합',
  },
  trangThaiLopHoc: {
    Nhap: '임시저장',
    SapKhaiGiang: '개강 예정',
    DangHoc: '수업 중',
    DaKetThuc: '종료됨',
    DaHuy: '취소됨',
  },
  trangThaiHocVien: {
    DangHoc: '수강 중',
    BaoLuu: '휴학',
    ChuyenLop: '반 이동',
    DaNghi: '중도 포기',
  },
  lich: {
    thang: '월',
    tuan: '주',
    danhSach: '목록',
    homNay: '오늘',
    truoc: '이전',
    sau: '다음',
    kieuBang: '표',
    kieuLich: '달력',
  },
  chiTietBuoi: {
    tabThongTin: '수업 정보',
    tabDiemDanh: '출석',
    tabNhanXet: '후기',
    tabBaiTap: '과제',
    tabTaiLieu: '자료',
    quayLaiLich: '수업 일정으로',
    buoiTruoc: '이전 수업',
    buoiSau: '다음 수업',
    chonBuoi: '다른 수업 선택',
    khongTimThayBuoi: '수업을 찾을 수 없습니다',
    taiLieuTheoLop: '자료는 개별 수업이 아니라 반 전체에 연결됩니다 — 이것은 반 공용 자료입니다.',
  },
  nhanXetBuoi: {
    tieuDe: '수업에 대한 수강생 후기',
    cuaToi: '내 후기',
    noiDung: '내용',
    noiDungGoiY: '오늘 수업은 어땠나요? 개선할 점이 있나요?',
    mucHaiLong: '전반적인 만족도',
    theoTieuChi: '평가 기준별 채점 (5점 만점)',
    khongChon: '평가 안 함',
    chamNguoiDungLop: '수업 진행자 평가',
    vaiTro: {
      GiaoVien: '강사',
      TroGiang: '보조강사',
    },
    chuaChonDiem: '미채점',
    boChon: '선택한 점수를 다시 누르면 채점이 취소됩니다',
    khongCoTieuChi: '센터에 강의 평가 기준이 설정되어 있지 않습니다. 평가 기준(HRM) 메뉴에서 추가하도록 관리자에게 문의하세요.',
    diemDaCham: '부여한 점수',
    chamChung: '수업 전체 평가',
    gui: '후기 보내기',
    capNhat: '후기 수정',
    hoiGui: '이 수업에 대한 후기를 보낼까요?',
    hoiCapNhat: '이미 보낸 후기를 수정할까요? 기존 내용은 덮어쓰여집니다.',
    daGui: '후기를 보냈습니다',
    chuaCo: '이 수업에 대한 후기가 없습니다',
    nhanXetHocVien: '수강생 후기',
    nhanXetGiaoVien: '수강생에 대한 강사 평가',
    chuaCoNhanXetGv: '이 수업에서 강사가 평가한 수강생이 없습니다',
    ghiONhanXetGv: '강사의 평가는 출석 탭에서 수강생별로 기록합니다.',
    giaiThichChoGv: '여기의 후기 항목은 수강생이 수업에 대해 의견을 남기는 전용 창구라서, 해당 반에서 수강 중인 수강생만 보낼 수 있습니다. 수강생 개개인을 평가하려면 출석 탭을 여세요 — 수강생마다 평가 입력란이 따로 있습니다.',
  },
  buoiHoc: {
    hoiSinhLich: '선택한 주기로 일정을 생성할까요?',
    hoiSinhThem: '현재 일정에 수업을 추가할까요? 기존 수업은 삭제되지 않습니다.',
    hoiSinhLai: '다시 생성하면 아직 진행하지 않은 수업이 삭제되고 새 일정이 만들어집니다. 확정된 수업은 그대로 유지됩니다. 계속할까요?',
    hoiChotBuoi: '이 수업을 확정할까요? 출석하지 않은 사람은 결석으로 기록되며, 확정한 뒤에는 시간 수정, 취소, 삭제를 할 수 없습니다.',
    thuTuNgan: '{{n}}차시',
    sinhThemBuoi: '수업 추가',
    xoaBuoi: '수업 삭제',
    doiTrangThai: '상태 변경',
    moTaDoiTrangThai: '{{thuTu}}차시 — {{gio}}. 새 상태를 선택하세요:',
    dangApDung: '적용 중',
    laHocBu: '보충 수업',
    macDinhTheoLop: '비워 두면 = 반 설정을 따름',
    tuNgay: '생성 시작일',
    daChot: '확정된 수업 {{soLuong}}회',
    goiYSinhThem: '현재 일정에 수업을 추가합니다 — 기존 수업은 삭제되지 않고, 새 수업은 이어서 번호가 매겨집니다. 한 회만 추가한다면(보충, 복습) 수업 수를 1로 두세요.',
    canhBaoSinhLai: '다시 생성하면 아직 진행하지 않은 수업이 삭제되고 새 일정이 만들어집니다. 확정된 수업은 그대로 유지됩니다.',
    xacNhanSinhLai: '진행하지 않은 수업 {{soLuong}}회를 삭제하고 새 일정을 생성할까요? 확정된 {{daChot}}회는 그대로 유지됩니다. 기존 일정을 잃지 않고 수업을 추가하려면 "수업 추가"를 사용하세요.',
    xacNhanHuyBuoi: '{{thuTu}}차시({{gio}})를 취소할까요? 이력이 남도록 기록은 그대로 보존됩니다.',
    xacNhanXoaBuoi: '{{thuTu}}차시({{gio}})를 완전히 삭제할까요? 복구할 수 없습니다. 이미 진행된 수업이라면 삭제보다 취소를 권합니다.',
    tieuDe: '수업',
    lich: '수업 일정',
    thuTu: '차시',
    thoiGian: '시간',
    giaoVien: '강사',
    giaoVienRieng: '개별 강사',
    phongHoc: '강의실',
    linkHoc: '온라인 수업 링크',
    ghiChu: '비고',
    troGiang: '보조강사',
    troGiangTheoLop: '반의 보조강사 — 이 수업에는 별도 보조강사가 배정되지 않았습니다.',
    theoLop: '(반 설정)',
    khongCoTroGiang: '이 반에는 보조강사가 없습니다',
    hocBu: '보충',
    hocOnline: '온라인 수업',
    nhom: {
      sapToi: '예정',
      daQua: '지난 수업',
    },
    trangThai: '상태',
    diemDanh: '출석',
    chuaCoLich: '이 반에는 수업 일정이 없습니다',
    sinhLich: '수업 일정 생성',
    sinhLaiLich: '일정 다시 생성',
    thuTrongTuan: '수업 요일',
    gioBatDau: '시작 시각',
    gioKetThuc: '종료 시각',
    ketThucTheo: '종료 기준',
    theoSoBuoi: '수업 횟수',
    theoNgay: '종료일',
    ngayLoaiTru: '휴강일 (수업 없음)',
    ngayLoaiTruGoiY: '한 줄에 하루씩, 2026-04-30 형식',
    xemTruoc: '일정 미리보기',
    daSinh: '{{soLuong}}회 수업이 생성됩니다',
    huyBuoi: '이 수업 취소',
    chotBuoi: '수업 확정',
    chotBuoiGoiY: '출석하지 않은 사람은 결석으로 기록됩니다.',
    tuDiemDanh: '빠른 출석',
  },
  diemDanh: {
    hoiLuu: '수강생 {{soLuong}}명의 출석을 저장할까요?',
    tieuDe: '출석',
    hocVien: '수강생',
    tuKhai: '수강생 자가 체크',
    chinhThuc: '확정',
    lyDoVang: '결석 사유',
    thieuLyDoVang: '수강생 {{soLuong}}명의 결석 사유가 입력되지 않았습니다: {{ten}}. 사유를 입력한 뒤 저장하거나, "수업 확정"으로 "미출석 처리"하세요.',
    thieuLyDoNgan: '사유가 없는 결석자가 있습니다',
    nguon: '출처',
    chuaGhiNhan: '미기록',
    khacTuKhai: '자가 체크와 다름',
    luu: '출석 저장',
    daLuu: '출석을 저장했습니다',
    chiXem: '이 출석부는 조회 권한만 있습니다.',
    nhanXetGv: '강사 평가',
    nhanXetGoiY: '발음, 참여도, 과제 등…',
    buoiDaChot: '확정된 수업 — 출석과 평가는 계속 수정할 수 있지만, 수업 시간은 수정할 수 없습니다.',
  },
  trangThaiDiemDanh: {
    CoMat: '출석',
    Vang: '결석',
    DiMuon: '지각',
    VangCoPhep: '사유 결석',
  },
  nguonDiemDanh: {
    HocVienTuKhai: '수강생 자가 체크',
    GiaoVien: '강사',
    QuanTri: '관리자',
  },
  trangThaiBuoiHoc: {
    DaLenLich: '일정 등록됨',
    DaHoanThanh: '완료됨',
    DaHuy: '취소됨',
    ChuyenLich: '일정 변경',
  },
  tinhTrangBuoi: {
    ChuaBatDau: '시작 전',
    DangDienRa: '진행 중',
    ChuaChot: '미확정',
    DaXong: '완료',
    ChuyenLich: '일정 변경',
    DaHuy: '취소됨',
  },
  thu: {
    Monday: '월',
    Tuesday: '화',
    Wednesday: '수',
    Thursday: '목',
    Friday: '금',
    Saturday: '토',
    Sunday: '일',
  },
  hocLieu: {
    luuDiem: '점수 저장',
    daSuaChuaLuu: '{{soLuong}}건 수정됨, 저장 전',
    hoiLuuDiem: '제출물 {{soLuong}}건의 점수와 평가를 저장할까요?',
    hoiXoaBaiTap: '"{{ten}}" 과제를 삭제할까요? 수강생의 제출물도 함께 사라집니다.',
    baiTap: '과제',
    taiLieu: '자료',
    themBaiTap: '과제 내기',
    themTaiLieu: '자료 추가',
    tieuDe: '제목',
    moTa: '설명',
    hanNop: '제출 기한',
    buoiHoc: '수업',
    loai: '분류',
    ganLop: '반에 연결',
    ganLopGoiY: '비워 두면 = 센터 전체 공용 자료',
    lopChung: '공용',
    tep: '첨부 파일',
    themTep: '파일 추가',
    keoThaTep: '파일 선택 (PDF, Word, Excel, 이미지 — 최대 20MB)',
    daNop: '제출됨',
    chuaCoBaiTap: '등록된 과제가 없습니다',
    chuaCoTaiLieu: '등록된 자료가 없습니다',
    xemBaiNop: '제출물 보기',
    lanNop: '제출 회차',
    thoiDiemNop: '제출 시각',
    diem: '점수',
    nhanXet: '평가',
    cham: '채점',
    nguoiTaiLen: '업로드한 사람',
  },
  trangThaiBaiNop: {
    DaNop: '제출됨',
    NopMuon: '지각 제출',
    DaCham: '채점 완료',
  },
  loaiTaiLieu: {
    GiaoTrinh: '교재',
    BaiGiang: '강의 자료',
    ThamKhao: '참고 자료',
    DeThi: '시험지',
    Khac: '기타',
  },
  taiKhoan: {
    tieuDe: '사용자 계정',
    username: '아이디',
    hoTen: '성명',
    ngaySinh: '생년월일',
    loaiNguoiDung: '역할',
    email: '이메일',
    soDienThoai: '전화번호',
    diaChi: '주소',
    quyen: '권한 그룹',
    trangThai: '상태',
    hoatDong: '활성',
    voHieuHoa: '비활성',
    themMoi: '계정 추가',
    suaTieuDe: '계정 수정',
    datLaiMatKhau: '비밀번호 재설정',
    canDoiMatKhau: '비밀번호 변경 필요',
    wizardGoiY: '이미 있는 권한 그룹이 있으면 선택하세요',
    chonQuyen: '권한 그룹 선택…',
    timQuyen: '권한 그룹 이름을 입력해 검색…',
    buocDoiMk: '첫 로그인 시 비밀번호 변경 강제',
    buocDoiMkGoiY: '켜는 것을 권합니다: 대신 정해 준 비밀번호는 본인도 알고 있으니까요.',
    datLaiGoiY: '해당 사용자는 다음 로그인 때 비밀번호를 다시 변경해야 합니다.',
    matKhau: '비밀번호',
    matKhauMoi: '새 비밀번호',
    themTaiKhoan: '계정 추가',
    suaTaiKhoan: '계정 수정',
    buocDoiMatKhau: '첫 로그인 시 비밀번호 변경 강제',
    phaiDoiMatKhau: '비밀번호 변경 필요',
    hoiXoa: '계정 "{{ten}}"을(를) 삭제할까요? 사용자 정보는 그대로 유지되고, 로그인 수단만 사라집니다.',
    hoiDatLaiMatKhau: '"{{ten}}"의 비밀번호를 재설정할까요? 해당 사용자는 다음 로그인 때 다시 변경해야 하며, 기존 비밀번호는 즉시 무효가 됩니다.',
    HoatDong: '활성',
    VoHieuHoa: '비활성',
  },
  quyen: {
    hoiLuu: '권한 그룹 "{{ten}}"을(를) 저장할까요? 이 그룹에 속한 모든 계정의 권한이 즉시 바뀝니다.',
    tieuDe: '접근 권한 관리',
    tenQuyen: '권한 그룹 이름',
    moTa: '설명',
    soTaiKhoan: '계정 수',
    themMoi: '권한 그룹 추가',
    suaTieuDe: '권한 그룹 수정',
    maTran: '권한 매트릭스',
    chucNang: '기능',
    soO: '권한 항목 수',
    cauHinh: '권한 설정',
    taoVaCauHinh: '생성 후 권한 설정',
    themMoiGoiY: '먼저 그룹 이름을 정하세요; 다음 단계에서 권한을 고르며, 역할 템플릿이 있어 처음부터 일일이 체크할 필요가 없습니다.',
    batDauTuMau: '역할 템플릿으로 시작',
    apMauTieuDe: '역할 템플릿 적용',
    apMauHoi: '현재 선택한 권한을 전부 "{{ten}}"의 권한 세트({{so}}개 항목)로 바꿀까요? 적용한 뒤에도 항목별로 조정할 수 있습니다.',
    dangDung: '{{so}}개 계정이 사용 중',
    tongDaChon: '{{so}}개 항목 선택됨',
    chiXem: '권한 매트릭스 설정 권한이 없어 조회만 가능합니다. 수정이 필요하면 시스템 관리자에게 문의하세요.',
    khongThayNhom: '이 권한 그룹을 찾을 수 없습니다. 이미 삭제되었을 수 있습니다.',
    veDanhSach: '권한 그룹 목록으로',
    canNhac: {
      DiemDanh: {
        Chot: '출석부를 마감하고, 체크하지 않은 사람을 모두 결석으로 기록합니다. 되돌릴 수 없습니다.',
      },
      XepLop: {
        Duyet: '판매 담당자를 대신해 결정하며, 그들의 주문에 영향을 줍니다. 되돌릴 수 없습니다.',
      },
      LopHoc: {
        HoanTat: '반이 임시저장 상태에서 벗어나 관련된 모든 사람에게 보입니다. 되돌릴 수 없습니다.',
        Huy: '반과 그 반의 모든 수업을 취소합니다. 데이터는 남지만 반은 운영이 중단됩니다.',
      },
      BuoiHoc: {
        Huy: '수업을 취소하며, 수강생의 일정에 취소된 것으로 표시됩니다.',
      },
      PhanQuyen: {
        CauHinhQuyen: '이 권한을 가진 사람은 자기 그룹에 다른 모든 권한을 스스로 부여할 수 있습니다. 관리자에게만 부여하세요.',
      },
      DoiMatKhauNguoiKhac: {
        Sua: '다른 사람의 비밀번호를 재설정합니다 — 즉 그 계정으로 로그인할 수 있게 됩니다.',
      },
      DoanhThu: {
        ThuTien: '고객에게서 돈을 받았음을 확인합니다. 주문을 작성하는 사람과 분리하는 것이 좋습니다.',
      },
      HocPhi: {
        ThuTien: '수강생이 납부한 금액을 수강료 장부에 기록합니다.',
      },
      ThietLapChung: {
        CauHinhTien: '고객이 송금할 수취 정보(계좌 이체 QR)를 변경합니다.',
      },
      NhanXetBuoiHoc: {
        Xem: '그 수업에 참여한 모든 사람의 후기를 읽습니다. 수강생에게는 부여하지 마세요 — 같은 반 친구의 비공개 피드백까지 읽게 됩니다.',
      },
      LopHocToanTrungTam: {
        Xem: '자기가 맡은 반뿐 아니라 센터의 모든 반과 그 안의 수강생 정보 및 연락처까지 볼 수 있습니다.',
        Sua: '자기가 맡지 않은 반도 수정할 수 있습니다.',
      },
      chung: {
        Chot: '장부 마감 — 이후에는 수정할 수 없습니다.',
        Duyet: '되돌릴 수 없는 결정입니다.',
        ThuTien: '돈과 관련된 작업입니다.',
        Huy: '취소하되 기록은 남깁니다.',
      },
    },
    phamViDuLieu: '데이터 범위',
    phamViGoiY: '이 권한들은 기능을 추가로 열어 주는 것이 아니라, 사용자가 볼 수 있는 데이터의 범위를 넓힙니다. 부여하지 않으면 자기가 맡은 반만 보이고, 부여하면 센터의 모든 반과 그 안의 수강생 정보 및 연락처까지 보입니다.',
    oCu: '이 그룹에는 현재 목록에 없는 예전 권한이 남아 있습니다: {{ds}}. 저장해도 그대로 유지되지만 아무 효력이 없습니다 — 정리가 필요하면 시스템 관리자에게 문의하세요.',
  },
  hanhDong: {
    Xem: '조회',
    Them: '추가',
    Sua: '수정',
    Xoa: '삭제',
    Duyet: '승인 / 거절',
    Chot: '장부 마감',
    Huy: '취소',
    SinhLich: '수업 일정 생성',
    ThuTien: '수납',
    Cham: '채점',
    TuLam: '본인 작업 (본인 것)',
    DocTep: '첨부 파일 열람',
    QuanLyTep: '파일 업로드 / 삭제',
    CauHinhTien: '결제 설정',
    CauHinhQuyen: '권한 매트릭스 설정',
    HoanTat: '반 개설 확정',
    XepNhanSu: '부서에 직원 배치',
    GuiXepLop: '반 배정 요청 보내기',
    XuatBan: '게시',
    ChuyenCrm: 'CRM으로 이관',
  },
  tieuChi: {
    them: '평가 기준 추가',
    sua: '평가 기준 수정',
    ten: '평가 기준 이름',
    moTa: '평가자를 위한 안내',
    nhomLabel: '구분',
    chuaCo: '등록된 평가 기준이 없습니다',
    soLanDaCham: '평가 횟수',
    hoiLuu: '이 평가 기준을 저장할까요?',
    giaiThich: '평가 기준은 5점 척도 채점에 사용합니다. 영업 그룹은 관리자가 월 단위로 채점하고, 강의 그룹은 수강생이 각 수업마다 채점합니다.',
    khongDoiNhom: '이 평가 기준은 이미 채점 기록이 있어 구분을 변경할 수 없습니다.',
    ngungDungGoiY: '체크를 해제하면 사용이 중단됩니다 — 새 평가지에는 더 이상 나타나지 않지만 기존 평가지는 계속 볼 수 있습니다. 이미 채점된 기준은 삭제할 수 없는데, 평가가 끝난 모든 기간의 수치가 틀어지기 때문입니다.',
    nhom: {
      KinhDoanh: '영업 담당자',
      GiangDay: '강사 / 보조강사',
    },
    nhomMoTa: {
      KinhDoanh: '관리자가 월 단위로 채점',
      GiangDay: '수강생이 각 수업마다 채점',
    },
  },
  thongKeNs: {
    tabKinhDoanh: '영업',
    tabGiaoVien: '강사',
    tabTroGiang: '보조강사',
    hoTen: '성명',
    soHocVien: '수강생 수',
    soLop: '반 수',
    soBuoiDayDu: '정상 진행 수업',
    soBuoiHuy: '취소된 수업',
    chatLuongChamSoc: '고객 관리 품질',
    chatLuongGiangDay: '강의 품질',
    soPhieu: '평가지 {{so}}건',
    soLopNgan: '{{so}}개 반',
    cham: '채점',
    chamTieuDe: '영업 담당자 평가',
    ky: '평가 기간',
    kyGoiY: '직원 한 명당 기간별로 평가지 한 장 — 다시 채점하면 기존 평가지가 수정됩니다.',
    nhanXet: '관리자 의견',
    hoiLuuPhieu: '{{ten}}의 {{ky}} 기간 평가지를 저장할까요?',
    xepHangDoanhThu: '매출 순위',
    xepHangHocVien: '수강생 수 순위',
    xepHangHocVienMoTa: '이 사람이 유치해 실제로 수강까지 이어진 고객입니다.',
    xepHangBuoiDay: '정상 진행 수업 수 순위',
    xepHangChatLuong: '강의 품질 순위',
    xepHangChatLuongMoTa: '수강생이 각 수업마다 매긴 점수의 평균입니다.',
    chuaCoNhanVienKd: '영업 담당자가 없습니다.',
    chuaCoNguoi: '이 역할에 해당하는 사람이 없습니다.',
    chuaCoHocVien: '이 기간에 수강을 시작한 고객이 없습니다.',
    chuaCoBuoi: '이 기간에 완료된 수업이 없습니다.',
    chuaCoDanhGia: '이 기간에 등록된 평가가 없습니다.',
    chuaCoTieuChiKd: '영업 그룹 평가 기준이 없습니다 — 평가 기준 탭에서 추가해야 채점할 수 있습니다.',
    chuaCoTieuChiGd: '강의 그룹 평가 기준이 없습니다 — 수강생이 세부 항목을 채점할 수 있도록 평가 기준 탭에서 추가하세요.',
  },
  chucNang: {
    TaiKhoan: '로그인 계정',
    HoSoNguoiDung: '사용자 정보',
    LopHoc: '반',
    GhiDanhLop: '반에 수강생 등록',
    XepLop: 'CRM에서 반 배정',
    BuoiHoc: '수업',
    DiemDanh: '출석',
    NhanXetBuoiHoc: '수업 후기',
    BaiTap: '과제',
    BaiNopBaiTap: '수강생 제출물',
    BaiKiemTra: '시험',
    BaiLamKiemTra: '수강생 답안',
    KhoaOnline: '온라인 과정 (콘텐츠 작성)',
    GhiDanhKhoaOnline: '온라인 과정 수강 권한 부여',
    HocOnline: '온라인 학습',
    TaiLieu: '자료',
    HocPhi: '수강료',
    ThongKe: '통계',
    LopHocToanTrungTam: '센터의 모든 반',
    NhatKyHeThong: '시스템 로그',
    TrangDich: '랜딩 페이지',
    LienHeLanding: '랜딩 페이지 문의',
    PhanQuyen: '권한 관리',
    ThietLapChung: '일반 설정',
    Anh: '이미지 (로고, 커버 이미지, QR)',
    DoiMatKhauNguoiKhac: '타인 비밀번호 변경',
    NhanSu: '직원',
    ChucVu: '직위',
    PhongBan: '부서',
    TieuChiDanhGia: '평가 기준',
    ThongKeNhanSu: '인사 통계',
    DoanhThu: '매출',
    ThongKeDoanhThu: '매출 통계',
    KhachHang: '고객',
    ChamSocKhachHang: '고객 관리',
    KhoaHoc: '과정',
    SanPham: '상품',
  },
  heThong: {
    Hrm: 'HRM — 인사',
    Crm: 'CRM — 고객',
    Lms: 'LMS — 교육',
    DungChung: '세 시스템 공통',
    chuyenHeThong: '시스템 전환',
    dungChungGoiY: '이 관리 기능들은 세 시스템이 함께 사용하므로 모든 탭에 표시됩니다.',
  },
  hrm: {
    moTaNvkd: '영업 담당자 인사 정보: 목표, 담당 고객, 수당.',
    moTaGiaoVien: '인사 관점에서 본 강사: 계약, 급여, 근태. LMS의 강사와 동일한 사람이며, 관리하는 정보만 다릅니다.',
  },
  phuongThucThanhToan: {
    TienMat: '현금',
    ChuyenKhoan: '계좌 이체',
    Khac: '기타',
  },
  donViTien: {
    VND: 'VND — 베트남 동',
    USD: 'USD — 미국 달러',
    EUR: 'EUR — 유로',
    CAD: 'CAD — 캐나다 달러',
  },
  crmLoc: {
    locThem: '상세 필터',
    xoaLoc: '필터 해제',
    doiNhom: '팀',
    chuaCoTag: '영업 태그가 지정된 부서가 없습니다.',
    denCoCau: '조직도에서 태그 지정하기 →',
    nhanVien: '담당 직원',
    nguon: '유입 경로',
    nguonNhanVien: '직원 등록',
    nguonTuDangKy: '고객 직접 등록',
    taoTuNgay: '등록일 시작',
    denNgay: '종료일',
    hinhThuc: '결제 방식',
    sanPham: '상품',
    theoNguoiMangKhach: '팀과 담당자는 고객을 유치한 사람을 기준으로 집계합니다 — 통계 화면과 같은 기준입니다. 고객이 직접 등록한 경우는 어느 팀에도 속하지 않습니다.',
  },
  khachHang: {
    them: '고객 추가',
    sua: '고객 수정',
    hoTen: '이름',
    email: '이메일',
    soDienThoai: '전화번호',
    linkFacebook: 'Facebook 링크',
    lienHe: '연락처',
    phuongThuc: '결제 방식',
    phuongThucGoiY: '이 고객의 기본 결제 방식입니다 — 등록 건별로 따로 기록됩니다.',
    tinhTrang: '상태',
    daMua: '구매함',
    chuaMua: '미구매',
    soKhoa: '과정 수',
    tongMua: '총 구매액',
    hocVien: '수강생 정보',
    capTaiKhoan: '수강생 계정 발급',
    sdtDaCo: '이 번호는 이미 {{ten}}의 번호입니다.',
    moHoSoNay: '이 고객 정보 열기',
    hoiCapTaiKhoan: '{{ten}}의 수강생 정보와 로그인 계정을 만들까요? 해당 정보는 이 고객과 직접 연결됩니다.',
    capTaiKhoanGoiY: '{{ten}}의 수강생 정보와 로그인 계정을 만듭니다. 이 고객과 자동으로 연결되므로 같은 사람이 중복 등록되지 않습니다.',
    matKhauGoiY: '이 비밀번호를 수강생에게 알려 주세요 — 첫 로그인 시 시스템이 변경을 요구합니다.',
    chuaVaoHoc: '수강 시작 전',
    noiHocVien: '수강생 정보와 연결',
    noiHocVienGoiY: '고객이 실제로 수강을 시작했을 때 선택하세요. 양쪽은 동일 인물이지만 별도로 저장됩니다: 여기서 이름을 바꿔도 수강생 이름은 바뀌지 않으며, 반대도 마찬가지입니다.',
    timTheo: '이름, 전화번호 또는 이메일',
    chuaCo: '등록된 고객이 없습니다',
    hoiLuu: '고객 정보를 저장할까요? 현재 데이터는 덮어쓰여집니다.',
    hoiXoa: '고객 "{{ten}}"을(를) 삭제할까요? 복구할 수 없습니다.',
  },
  hinhThucChamSoc: {
    GoiDien: '전화',
    ZaloFacebook: 'Zalo / Facebook',
    Email: '이메일',
    GapTrucTiep: '대면 상담',
    Khac: '기타',
  },
  trangThaiKhachHang: {
    Moi: '신규',
    DangTuVan: '상담 중',
    DaMua: '구매 완료',
    TuChoi: '거절',
  },
  chiTietNhanSu: {
    tabThongTin: '기본 정보',
    tabTep: '첨부 서류',
  },
  chiTietKhach: {
    tabThongTin: '기본 정보',
    tabChamSoc: '응대 이력',
    soLanMua: '{{so}}회 구매',
    tongNhom: '그룹 합계',
    tongTatCa: '전체 합계',
    boSungThanhToan: '추가 결제',
    guiYeuCau: '반 개설 요청 보내기',
    guiYeuCauXepLop: '반 개설 요청 보내기',
    hoiGuiYeuCau: '"{{ten}}"의 반 배정을 요청할까요? 교육 부서의 대기 목록에 이 수강생이 표시됩니다.',
    dangChoXepLop: '반 배정 대기 중',
    daXepLop: '{{ten}} 반에 배정됨',
    daHocLop: '수강 이력: {{ten}}',
    guiLai: '요청 다시 보내기',
    guiLanThu: '이번이 {{so}}번째 요청입니다',
    daGuiNLan: '{{so}}회 요청함',
    lanThu: '{{so}}회차',
    lichSuGuiYeuCau: '반 배정 요청 이력',
    ghiChuYeuCau: '교육 부서에 전달할 메모',
    ghiChuYeuCauGoiY: '수준, 희망 수업 시간, 수강생 관련 참고 사항 등…',
    lyDoTuChoi: '거절 사유',
    lyDoTuChoiTruoc: '지난번 거절 사유',
    nguoiGui: '요청자',
    nguoiXuLy: '처리자',
    suaThongTin: '정보 수정',
    soLanChamSoc: '응대 횟수',
    tongCamKet: '총 약정액',
    tongDaThu: '총 수납액',
    conThieu: '{{so}} 부족',
    themChamSoc: '응대 기록 추가',
    ghiMuaHangMoTa: '주문을 기록하고 응대 이력을 한 줄 자동으로 추가합니다',
    chonMatHang: '품목 선택…',
    soLuong: '수량',
    ngayMua: '구매일',
    noiDungMuaGoiY: '비워 두면 시스템이 "<품목명> 구매"로 자동 기록합니다',
    daThuDu: '전액 수령함',
    daThuDuGoiY: '이 항목을 체크하면 위 금액이 전액 수납된 것으로 함께 기록됩니다. 고객이 여러 차례 나눠 낸다면 체크를 해제하고 "납부 금액" 탭에서 회차별로 기록하세요.',
    hoiMuaHang: '이 주문을 기록할까요? 매출 한 건과 응대 이력 한 줄이 추가됩니다.',
    suaChamSoc: '응대 기록 수정',
    chamSocGoiY: '고객과 연락할 때마다 한 줄씩 기록하세요 — 최신 기록이 위에 표시됩니다.',
    chuaChamSoc: '응대 기록이 없습니다',
    thoiDiem: '연락일',
    hinhThuc: '방식',
    noiDung: '내용',
    noiDungGoiY: '고객이 한 말, 보낸 자료, 다시 연락하기로 한 시점 등…',
    trangThaiSau: '응대 후 상태',
    trangThaiSauGoiY: '고객의 현재 상태는 곧 가장 최근 응대 기록의 상태입니다 — 두 값이 어긋날 수 있는 별도 칼럼은 없습니다.',
    hoiLuuChamSoc: '이 응대 기록을 저장할까요?',
    hoiXoaChamSoc: '이 응대 기록을 삭제할까요? 복구할 수 없습니다.',
    chuaDangKy: '이 고객은 아직 등록한 과정이 없습니다',
    camKet: '약정액',
    daThu: '수납액',
    daDu: '완납',
    chuaDong: '미납',
    thieu: '{{so}} 부족',
    ghiThu: '수납 기록',
    suaThu: '수납 기록 수정',
    ngayThu: '수납일',
    nguoiThu: '수납자',
    chuaThu: '이 등록 건은 아직 한 푼도 수납되지 않았습니다.',
    conThieuGoiY: '{{so}} 부족합니다. 실제로 받은 금액을 입력하세요 — 여러 차례 나눠 받을 수 있습니다.',
    hoiLuuThu: '이 수납 기록을 저장할까요?',
    hoiXoaThu: '{{so}} 수납 기록을 삭제할까요? 금액 관련 데이터입니다.',
  },
  loaiDonHang: {
    KhoaHoc: '과정',
    SanPham: '상품',
  },
  sanPham: {
    them: '상품 추가',
    sua: '상품 수정',
    tenSp: '상품명',
    giaTien: '가격',
    donViTien: '통화',
    donViTinh: '단위',
    donViTinhGoiY: '권, 세트, 개…',
    soDonHang: '주문 수',
    tongSoLuongBan: '판매량',
    trangThaiBan: '상태',
    dangBan: '판매 중',
    ngungBan: '판매 중지',
    conBan: '이 상품을 계속 판매',
    ngungBanGoiY: '이미 주문이 있는 상품은 삭제할 수 없습니다 — 과거 주문에 판매한 상품명이 남아 있어야 하기 때문입니다. 위 항목의 체크를 해제하면 이력은 유지한 채 판매만 중지됩니다.',
    chuaCo: '등록된 상품이 없습니다',
    hoiLuu: '상품을 저장할까요? 현재 정보는 덮어쓰여집니다.',
    hoiXoa: '상품 "{{ten}}"을(를) 삭제할까요? 복구할 수 없습니다.',
  },
  trangThaiXepLop: {
    DangCho: '대기 중',
    DaXep: '반 배정 완료',
    DaHuy: '취소됨',
    TuChoi: '거절됨',
  },
  loaiMxh: {
    Facebook: 'Facebook',
    Zalo: 'Zalo',
    LinkedIn: 'LinkedIn',
    Telegram: 'Telegram',
    Khac: '기타',
  },
  chucVu: {
    them: '직위 추가',
    sua: '직위 수정',
    ten: '직위명',
    thuTu: '표시 순서',
    soNhanSu: '현재 인원',
    trangThai: '상태',
    dangDung: '사용 중',
    ngungDung: '사용 중지',
    conDung: '이 직위를 계속 사용',
    ngungDungGoiY: '현재 이 직위를 가진 사람이 있으면 삭제할 수 없습니다 — 과거 인사 정보에 기록된 직위가 남아 있어야 하기 때문입니다. 위 항목의 체크를 해제하면 이력은 유지한 채 사용만 중지됩니다.',
    chuaCo: '등록된 직위가 없습니다',
    giaiThich: '직위는 직함(경영진, 팀장 등)으로, 업무 역할(직원, 강사, 보조강사, 수강생)과는 다릅니다. 직위는 어떤 권한도 추가로 부여하지 않으며, 권한은 계정의 권한 관리 설정을 따릅니다.',
    hoiLuu: '직위를 저장할까요? 현재 정보는 덮어쓰여집니다.',
    hoiXoa: '직위 "{{ten}}"을(를) 삭제할까요? 현재 이 직위를 가진 사람이 있으면 삭제할 수 없습니다.',
  },
  tagVaiTro: {
    KinhDoanh: '영업 그룹',
    GiaoVien: '강사 그룹',
    TroGiang: '보조강사 그룹',
    goiYKinhDoanh: '이 부서는 고객, 매출, 통계 화면의 팀 필터에 표시됩니다.',
    goiYGiaoVien: '수업을 진행하는 강사 그룹으로 식별합니다. 매출 필터에는 표시되지 않습니다.',
    goiYTroGiang: '보조강사 그룹으로 식별합니다. 매출 필터에는 표시되지 않습니다.',
    KHAC: '기타 (태그가 없는 부서)',
  },
  coCau: {
    xemNhanSuPhong: '이 부서의 직원 목록 보기',
    tagVaiTro: '역할 태그',
    khongTag: '태그 없음 (조직 구조 표시용)',
    khongTagGoiY: '태그가 없는 부서는 이 조직도에만 표시되고, 어떤 모듈의 필터에도 나타나지 않습니다.',
    themPhongGoc: '부서 추가',
    themPhongBan: '부서 추가',
    themPhongCon: '하위 부서 추가',
    suaPhongBan: '부서 수정',
    tenPhongBan: '부서명',
    nguoiQuanLy: '관리자',
    chuaChonQuanLy: '관리자 미지정',
    quanLy: '관리자',
    quanLyChiLaThongTin: '조직 정보일 뿐이며 어떤 권한도 추가로 부여하지 않습니다. 권한은 계정의 권한 관리 설정을 따릅니다.',
    thuTu: '표시 순서',
    moTa: '설명',
    phongGoc: '최상위 부서',
    duoiPhong: '{{ten}}의 하위 부서',
    chuaCoPhongBan: '등록된 부서가 없습니다 — "부서 추가"를 눌러 시작하세요',
    chuaXep: '부서 미배치',
    themNhanSu: '부서에 직원 추가',
    chonNhanSu: '직원 선택',
    goTenNhanSu: '직원 이름을 입력해 검색…',
    hocVienKhongVaoCoCau: '수강생은 조직 구조에 포함되지 않으므로 목록에 나오지 않습니다.',
    hoiLuu: '부서를 저장할까요? 현재 정보는 덮어쓰여집니다.',
    hoiXoa: '부서 "{{ten}}"을(를) 삭제할까요? 소속 직원이나 하위 부서가 남아 있으면 삭제할 수 없습니다.',
    hoiXepNhanSu: '직원 {{soLuong}}명을 "{{ten}}"에 배치할까요? 해당 직원들은 현재 부서에서 빠집니다.',
  },
  xepLop: {
    dangCho: '반 배정 대기 수강생',
    khongCoAiCho: '반 배정을 기다리는 수강생이 없습니다',
    hocVien: '수강생',
    hocPhiTuDon: 'CRM 주문 금액',
    nguoiGui: '요청자',
    thoiDiemGui: '요청일',
    duyet: '반 배정 승인',
    timHocVienCho: '이름 또는 전화번호로 검색...',
    timKhongThayCho: '조건에 맞는 수강생을 찾을 수 없습니다',
    canhBaoLechKhoa: '과정이 일치하지 않습니다',
    hoiLechKhoa: '이 수강생의 주문은 "{{khoaDon}}" 과정이지만, {{lop}} 반은 "{{khoaLop}}" 과정을 가르칩니다. 그래도 이 반에 배정할까요?',
    vanDuyet: '그래도 승인',
    duyetVaoLop: '반 배정 승인',
    chonLop: '반 선택',
    khoaDaMua: '구매한 과정',
    hocPhiSeApDung: '적용 수강료는 {{so}}이(가) 됩니다 — 반 가격이 아니라 CRM 주문 금액을 따릅니다.',
    hoiDuyet: '"{{ten}}"을(를) 수강료 {{hocPhi}}(으)로 {{lop}} 반에 배정할까요? 이 수강생이 반의 수강료 장부에 나타납니다.',
    huyYeuCau: '요청 취소',
    tuChoi: '거절',
    tuChoiXepLop: '반 배정 거절',
    lyDo: '거절 사유',
    lyDoGoiY: '이 수준에 맞는 반이 아직 개설되지 않았습니다, 다음 기수를 기다려 주세요…',
    lyDoBatBuoc: '판매 담당자가 고객에게 답하려면 이유를 알아야 합니다 — 사유를 분명히 적어 주세요.',
    hoiTuChoi: '"{{ten}}"의 요청을 거절할까요? 판매 담당자는 이 사유를 보게 되며 다시 요청할 수 있습니다.',
    lanGuiThu: '{{so}}번째 요청',
    ghiChuNguoiGui: '요청자 메모',
    hoiHuy: '"{{ten}}"의 반 배정 요청을 취소할까요? 요청은 이력으로 남으며, 다시 배정하려면 판매 담당자가 새로 요청해야 합니다.',
  },
  khoaHoc: {
    them: '과정 추가',
    sua: '과정 수정',
    tenKhoa: '과정명',
    giaTien: '가격',
    donViTien: '통화',
    soBuoi: '수업 횟수',
    soBuoiNgan: '{{so}}회',
    soDangKy: '판매량',
    trangThaiBan: '상태',
    dangBan: '판매 중',
    ngungBan: '판매 중지',
    conBan: '이 과정을 계속 판매',
    ngungBanGoiY: '이미 등록이 있는 과정은 삭제할 수 없습니다 — 과거 주문에 판매한 과정명이 남아 있어야 하기 때문입니다. 위 항목의 체크를 해제하면 이력은 유지한 채 판매만 중지됩니다.',
    chuaCo: '등록된 과정이 없습니다',
    hoiLuu: '과정을 저장할까요? 현재 정보는 덮어쓰여집니다.',
    hoiXoa: '과정 "{{ten}}"을(를) 삭제할까요? 복구할 수 없습니다.',
  },
  donHang: {
    ghiDon: '주문 기록',
    suaDon: '주문 수정',
    lichSu: '주문 이력',
    loaiMatHang: '고객이 구매한 항목',
    soLuong: '수량',
    chonSanPham: '상품 선택',
    hoiLuu: '이 주문을 저장할까요?',
    hoiLuuKemChamSoc: '이 주문을 저장할까요? 매출 한 건과 응대 이력 한 줄이 추가됩니다.',
    chuaCo: '등록된 주문이 없습니다',
  },
  doanhThu: {
    them: '등록 추가',
    sua: '등록 수정',
    khachHang: '고객',
    khoaHoc: '과정',
    matHang: '품목',
    chonKhach: '고객 선택…',
    chonKhoa: '과정 선택…',
    giaGoc: '정가',
    soTien: '수납 금액',
    phanTram: '정가 대비 %',
    tyGia: 'VND 환율',
    tyGiaNgan: '×{{ty}}',
    soLuongNgan: '수량 {{so}}',
    quyDoiVnd: 'VND 환산액',
    ngayDangKy: '등록일',
    tuNgay: '시작일',
    denNgay: '종료일',
    tongDoanhThu: '총 매출 (VND)',
    soDangKy: '등록 건수',
    soKhachHang: '고객 수',
    giaNiemYet: '표시 가격: {{gia}} · {{so}}회. 할인이 있으면 금액을 수정하세요.',
    tyGiaGoiY: '환율은 등록 시점에 저장되며 실시간으로 조회하지 않습니다 — 덕분에 환율이 변동해도 지난달 매출 수치는 바뀌지 않습니다.',
    timTheo: '고객명, 과정명 또는 전화번호',
    chuaCo: '등록된 건이 없습니다',
    hoiLuu: '등록을 저장할까요? 현재 정보는 덮어쓰여집니다.',
    hoiXoa: '{{ten}}의 "{{khoa}}" 과정 등록을 삭제할까요? 매출 관련 데이터입니다.',
  },
  crm: {
    moTaDoanhThu: '기간별, 반별, 담당자별로 집계한 매출입니다. LMS의 수강료 장부와는 다릅니다: 수강료 장부는 한 반의 개별 수납 내역이고, 매출은 집계된 수치입니다.',
  },
  thietLap: {
    hoiLuu: '센터 설정을 저장할까요? 현재 정보는 덮어쓰여집니다.',
    tieuDe: '일반 설정',
    tenTrungTam: '센터 이름',
    tenVietTat: '약칭',
    moTa: '설명',
    maTrungTam: '센터 코드',
    maTrungTamKhongDoi: '센터 코드는 시스템이 발급하며 로그인에 사용합니다 — 변경할 수 없습니다',
    logo: '센터 로고',
    anhBia: '커버 이미지',
    diaChi: '주소',
    diaChiGoiY: '예: 123 Nguyen Van Linh, Hai Chau, Da Nang',
    lienHe: '연락처',
    lienHeGoiY: '전화번호 또는 이메일',
    nhomChuyenKhoan: '계좌 이체 정보',
    nhomChuyenKhoanMoTa: '수강생에게 어디로 송금해야 하는지 안내하는 용도입니다. 시스템이 결제를 처리하지는 않습니다.',
    soTaiKhoan: '계좌번호',
    soTaiKhoanGoiY: '예: 0123456789',
    tenNganHang: '은행',
    tenNganHangGoiY: '예: Vietcombank',
    chuTaiKhoan: '예금주',
    chuTaiKhoanGoiY: '은행 앱에 표시되는 이름과 동일하게',
    chuTaiKhoanLuuY: '송금하는 사람이 잘못 보내지 않도록 이름이 일치해야 합니다.',
    anhQr: '계좌 이체 QR 코드',
    anhQrGoiY: '사용하시는 은행 앱에서 캡처하세요.',
  },
  loi: {
    KHONG_TIM_THAY_TRUNG_TAM: '이 코드를 사용하는 센터가 없습니다. 센터 코드를 다시 확인하세요 (7자리, 숫자 0과 1은 포함되지 않음).',
    MA_TRUNG_TAM_KHONG_HOP_LE: '센터 코드가 올바르지 않습니다 — 7자리이며 0/O/1/I/L은 포함되지 않습니다',
    BAI_TAP_DA_CO_BAI_NOP: '수강생이 제출한 과제라 삭제할 수 없습니다. 제출물은 그들의 학습 결과입니다.',
    LOP_HOC_KHONG_HOP_LE: '반이 올바르지 않거나 해당 반에 대한 권한이 없습니다',
    LOAI_DINH_KEM_KHONG_HO_TRO: '지원하지 않는 첨부 유형입니다',
    TAN_SUAT_TRONG: '수업 요일이 선택되지 않았습니다',
    NGAY_KHONG_HOP_LE: '날짜가 올바르지 않습니다. 일정 생성 시작일을 다시 선택하세요.',
    KHACH_HANG_TRUNG_SO_DIEN_THOAI: '이 전화번호는 다른 고객이 이미 사용 중입니다. 번호로 다시 검색해 기존 고객 정보를 수정하세요.',
    KHACH_HANG_DA_CO_DANG_KY: '이 고객은 이미 과정 등록 이력이 있습니다 — 매출 데이터이므로 삭제할 수 없습니다.',
    KHACH_HANG_KHONG_HOP_LE: '고객 정보가 올바르지 않습니다',
    KHOA_ONLINE_KHONG_HOP_LE: '온라인 과정이 올바르지 않습니다',
    KHOA_ONLINE_DA_CO_NGUOI_HOC: '이 과정은 이미 수강생이 있어 삭제할 수 없습니다. 더 이상 권한을 부여하지 않으려면 "신규 부여 중단"으로 바꾸세요.',
    KHOA_ONLINE_KHONG_NHAN_GHI_DANH: '공개 중인 과정에만 수강 권한을 부여할 수 있습니다. 임시저장 과정은 아직 내용이 없고, 신규 부여를 중단한 과정은 더 이상 수강생을 받지 않습니다.',
    BAI_HOC_KHONG_DOI_DUOC_KHOA: '강의를 다른 과정으로 옮길 수 없습니다.',
    KHONG_XAC_DINH_DUOC_NGUOI_DUNG: '현재 사용자를 확인할 수 없습니다.',
    KHACH_HANG_DA_NOI_HO_SO_KHAC: '이 고객은 이미 다른 정보와 연결되어 있습니다. 새로 만들지 말고 해당 정보를 여세요.',
    KHOA_HOC_TRUNG_TEN: '이미 존재하는 과정명입니다',
    KHOA_HOC_DA_CO_DANG_KY: '이 과정은 이미 등록 건이 있어 삭제할 수 없습니다. "이 과정을 계속 판매" 체크를 해제하면 주문 이력은 유지한 채 판매만 중지됩니다.',
    KHOA_HOC_KHONG_HOP_LE: '과정이 올바르지 않습니다',
    SAN_PHAM_KHONG_HOP_LE: '상품이 올바르지 않습니다',
    SAN_PHAM_TRUNG_TEN: '이미 존재하는 상품명입니다',
    SAN_PHAM_DA_CO_DON_HANG: '이 상품은 이미 주문 건이 있어 삭제할 수 없습니다. "이 상품을 계속 판매" 체크를 해제하면 주문 이력은 유지한 채 판매만 중지됩니다.',
    PHAI_CHON_DUNG_MOT_MAT_HANG: '과정 또는 상품 중 정확히 하나만 선택해야 합니다.',
    TY_GIA_KHONG_HOP_LE: '환율은 0보다 커야 합니다',
    THU_VUOT_CAM_KET: '수납 총액이 고객이 약정한 금액을 초과합니다. 금액을 다시 확인하세요 — 보통 0을 하나 더 입력한 경우입니다.',
    DANG_KY_KHONG_HOP_LE: '등록 정보가 올바르지 않습니다',
    SO_TIEN_KHONG_HOP_LE: '금액이 올바르지 않습니다',
    GIO_KET_THUC_KHONG_HOP_LE: '종료 시각은 시작 시각보다 뒤여야 합니다 (자정을 넘기는 수업은 지원하지 않습니다)',
    SO_BUOI_KHONG_HOP_LE: '수업 횟수는 1회에서 500회 사이여야 합니다',
    NGAY_KET_THUC_TRUOC_KHAI_GIANG: '종강일은 개강일보다 뒤여야 합니다',
    DIEU_KIEN_DUNG_KHONG_HOP_LE: '종료 기준을 하나만 선택하세요: 수업 횟수 또는 종료일',
    KHONG_SINH_DUOC_BUOI_NAO: '생성된 수업이 없습니다 — 수업 요일과 기간을 다시 확인하세요',
    CHAN_TREN_SINH_BUOI: '허용된 기간 안에 요청한 수업 횟수를 채울 수 없습니다',
    GIO_KHONG_TON_TAI_DO_DOI_GIO: '서머타임 전환으로 존재하지 않는 시각입니다',
    LICH_DA_CO_DIEM_DANH: '이 반에는 이미 출석이 기록된 수업이 있습니다 — 일정을 다시 생성하면 데이터가 사라집니다. 다시 생성하지 말고 수업을 하나씩 수정하세요.',
    BUOI_DA_HUY: '취소된 수업입니다',
    HOC_VIEN_KHONG_THUOC_LOP: '이 반에 속한 수강생이 아닙니다',
    KHONG_THUOC_LOP_NAY: '이 반에 속해 있지 않습니다',
    NGOAI_KHUNG_GIO_DIEM_DANH: '출석 가능 시간이 아닙니다 (수업 시작 15분 전부터 수업 종료 시각까지)',
    THIEU_LY_DO_VANG: '결석에는 사유가 필요합니다',
    NHAN_SU_KHONG_HOP_LE: '올바르지 않은 직원이 포함되어 있습니다 (퇴사했거나 존재하지 않음)',
    GIAO_VIEN_TRUNG_TRO_GIANG: '담당 강사는 같은 반의 보조강사를 겸할 수 없습니다',
    CHUA_CHON_HINH_THUC_HOC: '수업 형태가 선택되지 않았습니다',
    HOC_PHI_AM: '수강료는 음수일 수 없습니다',
    SUC_CHUA_KHONG_HOP_LE: '정원은 0보다 커야 합니다',
    LOP_DA_HOAN_TAT: '이 반은 이미 확정되어 다시 확정할 필요가 없습니다',
    CHUA_NHAP_HOC_PHI: '반을 확정하기 전에 수강료를 입력해야 합니다',
    CHI_XOA_DUOC_LOP_NHAP: '임시저장 상태의 반만 삭제할 수 있습니다. 이미 운영을 시작한 반은 이력을 남기도록 반 취소를 사용하세요.',
    CHUA_CHON_HOC_VIEN: '선택된 수강생이 없습니다',
    HOC_VIEN_KHONG_HOP_LE: '올바르지 않은 수강생입니다 (중도 포기했거나 존재하지 않음)',
    HOC_VIEN_DA_TRONG_LOP: '이미 이 반에 있는 수강생입니다',
    KHOA_HOC_KHONG_KHOP_LOP: '주문의 과정이 이 반이 가르치는 과정과 일치하지 않습니다',
    VUOT_SO_KHOA_HOC_CUA_LOP: '한 반에는 최대 3개 과정까지만 지정할 수 있습니다',
    VUOT_SUC_CHUA: '반의 최대 정원을 초과합니다',
    CHI_KHOA_HOC_MOI_XEP_LOP: '과정을 구매한 주문만 반 배정을 요청할 수 있습니다',
    DA_GUI_YEU_CAU_XEP_LOP: '이 주문은 이미 반 배정을 요청했습니다',
    YEU_CAU_KHONG_HOP_LE: '반 배정 요청이 올바르지 않거나 이미 삭제되었습니다',
    YEU_CAU_DA_XU_LY: '이미 처리된 요청입니다. 목록을 새로 불러오세요',
    CHUA_NHAP_LY_DO_TU_CHOI: '거절 사유를 입력해야 합니다',
    PHONG_BAN_TRUNG_TEN: '이 단계에 같은 이름의 부서가 이미 있습니다',
    CHUC_VU_TRUNG_TEN: '센터에 같은 이름의 직위가 이미 있습니다',
    CHUC_VU_CON_NGUOI_GIU: '현재 이 직위를 가진 사람이 있습니다 — "사용 중" 체크를 해제하면 이력은 유지한 채 사용만 중지됩니다',
    CHUC_VU_KHONG_HOP_LE: '존재하지 않는 직위입니다',
    PHONG_BAN_CON_NGUOI: '이 부서에 아직 직원이 있습니다 — 삭제하기 전에 다른 부서로 옮기세요',
    PHONG_BAN_CON_CAP_DUOI: '이 부서에 아직 하위 부서가 있습니다 — 아래에서부터 삭제하세요',
    PHONG_BAN_CHU_TRINH: '이 부서를 자기 자신의 하위 부서로 지정할 수 없습니다',
    PHONG_BAN_KHONG_HOP_LE: '존재하지 않는 부서입니다',
    NGUOI_QUAN_LY_KHONG_HOP_LE: '관리자로 지정할 수 없는 사람입니다 (퇴사했거나 수강생입니다)',
    HOC_VIEN_KHONG_VAO_CO_CAU: '수강생은 조직 구조에 포함되지 않습니다',
    CHUA_CHON_NHAN_SU: '선택된 직원이 없습니다',
    LOAI_TEP_KHONG_HO_TRO: 'PDF, Word, Excel, PowerPoint, 이미지 또는 압축 파일만 가능합니다',
    LOAI_TEP_HO_SO_KHONG_HO_TRO: '직원 인사 서류는 PDF, Word 또는 Excel만 가능합니다',
    VUOT_SO_TEP_HO_SO: '인사 정보 하나당 파일은 최대 10개까지 저장됩니다 — 오래된 파일을 지운 뒤 다시 시도하세요.',
    TIEU_CHI_THIEU_TEN: '평가 기준에는 이름이 필요합니다.',
    TIEU_CHI_TEN_QUA_DAI: '평가 기준 이름이 너무 깁니다 (최대 200자).',
    TIEU_CHI_TRUNG_TEN: '이 그룹에 같은 이름의 평가 기준이 이미 있습니다.',
    TIEU_CHI_NHOM_KHONG_HOP_LE: '평가 기준 구분이 올바르지 않습니다.',
    TIEU_CHI_DA_CHAM_KHONG_DOI_NHOM: '이 평가 기준은 이미 채점되어 구분을 변경할 수 없습니다 — 구분을 바꾸면 이미 채점된 모든 기간의 수치가 틀어집니다. 이 기준은 사용을 중지하고 다른 구분에 새 기준을 만드세요.',
    TIEU_CHI_KHONG_THUOC_NHOM: '영업 그룹에 속하지 않은 평가 기준이 있습니다.',
    DIEM_TIEU_CHI_KHONG_HOP_LE: '점수는 1점에서 5점 사이여야 합니다.',
    KY_DANH_GIA_KHONG_HOP_LE: '평가 기간은 yyyy-MM 형식이어야 합니다. 예: 2026-09.',
    KHONG_PHAI_NHAN_VIEN_KINH_DOANH: '영업 담당자만 채점할 수 있습니다.',
    TEN_TEP_KHONG_HOP_LE: '파일 이름이 올바르지 않습니다 — 최소 한 글자 이상 입력하세요.',
    TEP_QUA_LON: '파일이 너무 큽니다. 최대 20 MB입니다',
    TEP_RONG: '빈 파일입니다',
    LOAI_ANH_KHONG_HO_TRO: 'JPG, PNG, WebP 또는 GIF 이미지만 가능합니다',
    ANH_QUA_LON: '이미지가 너무 큽니다. 최대 5 MB입니다',
    ANH_RONG: '빈 이미지 파일입니다',
    DANG_NHAP_THAT_BAI: '센터 코드, 아이디 또는 비밀번호가 올바르지 않습니다',
    TAI_KHOAN_BI_VO_HIEU_HOA: '비활성화된 계정입니다',
    TAI_KHOAN_BI_KHOA_TAM: '비밀번호를 여러 번 틀렸습니다. 계정이 일시적으로 잠겼으니 몇 분 뒤에 다시 시도하거나 "비밀번호 찾기"를 이용하세요.',
    PHAI_DOI_MAT_KHAU: '계속하려면 비밀번호를 변경해야 합니다',
    MAT_KHAU_CU_KHONG_DUNG: '현재 비밀번호가 올바르지 않습니다',
    TOKEN_DAT_LAI_KHONG_HOP_LE: '재설정 코드가 올바르지 않거나 만료되었습니다',
    PHIEN_DA_BI_DAY_RA: '이 계정이 방금 다른 곳에서 로그인하여 현재 세션이 종료되었습니다. 본인이 아니라면 다시 로그인한 뒤 비밀번호를 변경하세요.',
    CHUA_XAC_THUC: '로그인이 필요합니다',
    KHONG_DU_QUYEN: '이 작업을 수행할 권한이 없습니다',
    TOKEN_THIEU_TENANT: '로그인 세션이 올바르지 않습니다. 다시 로그인하세요',
    KHONG_TIM_THAY: '데이터를 찾을 수 없습니다',
    DU_LIEU_KHONG_HOP_LE: '입력한 데이터가 올바르지 않습니다',
    TRUNG_TAM_PHAI_CON_NGUOI_PHAN_QUYEN: '센터에는 권한 관리 권한을 가진 사람이 최소 한 명은 있어야 합니다. 다른 사람에게 그 권한을 먼저 부여한 뒤 다시 시도하세요.',
    KHONG_TU_KHOA_TAI_KHOAN_CHINH_MINH: '현재 로그인한 계정은 스스로 잠글 수 없습니다. 체크를 해제한 뒤 다시 시도하세요.',
    QUA_NHIEU_YEU_CAU: '너무 빠르게 조작하고 있습니다. 잠시 기다린 뒤 다시 시도하세요.',
    LOI_HE_THONG: '오류가 발생했습니다. 다시 시도해 주세요',
    USERNAME_DA_TON_TAI: '이 센터에 이미 존재하는 아이디입니다',
    QUYEN_KHONG_HOP_LE: '권한 그룹이 올바르지 않습니다',
    QUYEN_DANG_DUOC_GAN: '삭제할 수 없습니다: 이 권한 그룹이 계정에 지정되어 있습니다',
    KHONG_TU_XOA_TAI_KHOAN_CUA_MINH: '자신의 계정은 스스로 삭제할 수 없습니다',
    KHONG_TU_VO_HIEU_HOA_MINH: '자신의 계정은 스스로 비활성화할 수 없습니다',
    CHUC_NANG_KHONG_HOP_LE: '기능이 올바르지 않습니다',
    MAT_KHAU_QUA_NGAN: '비밀번호는 12자 이상이어야 합니다',
    MAT_KHAU_QUA_DAI: '비밀번호가 너무 깁니다 (최대 128자)',
    MAT_KHAU_MOI_TRUNG_CU: '새 비밀번호는 현재 비밀번호와 달라야 합니다',
    USERNAME_KY_TU_KHONG_HOP_LE: '아이디는 영문, 숫자와 . _ - 만 사용할 수 있습니다',
    ID_KHONG_KHOP: '데이터가 일치하지 않습니다',
    NGUOI_DUOC_CHAM_KHONG_DUNG_LOP: '평가 대상자가 이 수업을 진행하지 않았습니다. 페이지를 새로 고친 뒤 다시 시도하세요.',
    TRANG_THAI_KHONG_HOP_LE: '수업 상태가 올바르지 않습니다.',
    BUOI_HOC_DA_KHOA: '이미 확정된 수업이라 수정, 취소, 삭제할 수 없습니다. 확정된 수업의 출석은 출결 증빙이 됩니다.',
    BUOI_HOC_DA_CO_DIEM_DANH: '이 수업에는 이미 출석 기록이 있습니다. 데이터를 남기려면 삭제 대신 수업을 취소하세요.',
    BUOI_HOC_DA_CO_NHAN_XET: '이 수업에는 이미 수강생 후기가 있습니다. 피드백을 남기려면 삭제 대신 수업을 취소하세요.',
    BUOI_HOC_TRUNG_GIO: '현재 일정과 시간이 겹치는 수업이 있습니다. 마지막 수업 이후의 날짜를 시작일로 선택하세요.',
    NGUOI_DUNG_KHONG_HOP_LE: '사용자가 올바르지 않습니다',
    KHONG_PHAI_NHAN_SU: '직원 화면은 직원, 강사, 보조강사만 관리합니다. 수강생은 LMS의 수강생 화면에서 관리합니다.',
    KHONG_PHAI_HOC_VIEN: '수강생 화면은 수강생만 관리합니다. 직원, 강사, 보조강사는 HRM의 직원 화면에서 관리합니다.',
    NGUOI_DUNG_DA_CO_TAI_KHOAN: '이 사람은 이미 계정이 있습니다. 한 사람당 로그인 계정은 하나만 가질 수 있습니다.',
    NGUOI_DUNG_DANG_CO_DU_LIEU: '삭제할 수 없습니다: 이 사람에게 반, 출석 또는 수강료 기록이 있습니다. 데이터를 남기려면 삭제 대신 "퇴사"로 표시하세요.',
    SO_TIEN_PHAI_DUONG: '금액은 0보다 커야 합니다',
  },
}

export default ko
