/**
 * **简体中文 (tiếng Trung giản thể) — dịch từ `vi.ts`** (23/09/2026).
 *
 * Sinh bằng `scripts/sinh-tep-ngon-ngu.py` để cấu trúc khoá **luôn khớp `vi.ts`**.
 * Sửa tay được, nhưng đừng thêm/bớt khoá ở đây — thêm ở `vi.ts` trước, vì
 * `check-i18n-keys.py` so mọi ngôn ngữ với tệp đó.
 *
 * Chỉ dịch GIAO DIỆN. Dữ liệu người dùng nhập (tên lớp, tên học viên, ghi chú)
 * giữ nguyên — xem `danhSach.ts`.
 */
const zh = {
  chung: {
    tieuDeTab: 'LangCenter — 语言中心管理系统',
    xacNhanLuu: '确认保存',
    xemChiTiet: '查看详情',
    ghiChu: '备注',
    dangPhatTrien: '模块开发中',
    dangPhatTrienGoiY: '该模块的权限管理与导航部分已可用——您现在就可以为权限组授权。详细业务功能将后续补充。',
    xacNhanThem: '确认新增',
    hoiLuu: '保存对「{{ten}}」的修改？当前信息将被覆盖。',
    hoiThem: '新增「{{ten}}」？',
    hoiLuuChung: '保存修改？',
    hoiThemChung: '新增这条记录？',
    dangTai: '加载中…',
    tatCa: '全部',
    dongY: '确定',
    luu: '保存',
    huy: '取消',
    them: '新增',
    sua: '编辑',
    xoa: '删除',
    timKiem: '搜索',
    thaoTac: '操作',
    khongCoDuLieu: '暂无数据',
    xacNhanXoa: '确定要删除吗？',
    dangXuat: '退出登录',
    quayLai: '返回',
    dong: '关闭',
    moMenu: '打开菜单',
    moSidebar: '展开侧边栏',
    thuGonSidebar: '收起侧边栏',
    daLuu: '已保存',
    taiVe: '下载',
    xem: '查看',
  },
  dangKy: {
    tieuDe: '注册中心',
    moTa: '输入中心名称，系统将为您分配中心代码',
    nut: '创建中心',
    thanhCong: '中心创建成功',
    maTrungTamCuaBan: '您的中心代码',
    saoChep: '复制',
    giaiThichMa: '中心代码由系统分配，共 7 个字符，用于登录。',
    canhBaoLuuMa: '请记下中心代码。每次登录都需要它，且无法自行查回。',
    luuYDoiMatKhau: '首次登录时系统会要求您修改密码。',
    chuaMo: '尚未开放注册',
    chuaMoMoTa: '本系统尚未开放自由注册。请联系管理员创建中心。',
    veDangNhap: '← 返回登录页',
  },
  ngonNgu: {
    doi: '切换语言',
    nhan: '语言',
  },
  linhVat: {
    tat: '隐藏形象',
    thoai: [
      '祝你教学和学习都愉快！',
      '关闭页面前记得保存哦。',
      '喝咖啡了吗？歇一会儿也挺好的。',
      '今天的班级怎么样啦？',
      '我出去溜达一圈，你继续忙。',
      '数据整理清楚，月底就轻松多啦。',
      '有什么难题就问管理员吧！',
      '一字之师也是师——好好教哦！',
    ],
  },
  dangNhap: {
    tieuDe: '登录',
    moTa: '请输入中心代码、用户名和密码',
    maTrungTam: '中心代码',
    tenPhanMem: 'LangCenter',
    bannerTieuDe: '外语中心管理系统',
    bannerMoTa: '输入中心代码即可开始。班级、学员、考勤与学费，尽在同一套系统中管理。',
    banQuyen: '© {{nam}} LangCenter · 本软件由 GiapTex 开发',
    banQuyenCoTen: '© {{nam}} {{ten}} · 本软件由 GiapTex 开发',
    maTrungTamGoiY: '7 个字符，不区分大小写',
    dangTraTenTrungTam: '正在查询中心代码…',
    khongTimThayTrungTam: '未找到对应的中心',
    chuaCoTrungTam: '还没有中心？',
    username: '用户名',
    matKhau: '密码',
    nut: '登录',
    nhoDangNhap: '记住中心代码和用户名',
    quenMatKhau: '忘记密码？',
    doiMatKhauTieuDe: '修改密码',
    doiMatKhauMoTa: '您的账号需要先修改密码才能进入系统',
    matKhauCu: '当前密码',
    matKhauMoi: '新密码',
    xacNhanMatKhau: '确认新密码',
    quenTieuDe: '忘记密码',
    quenMoTa: '输入已注册的邮箱以接收密码重置码',
    email: '邮箱',
    guiYeuCau: '提交请求',
    daGuiEmail: '如果该邮箱在系统中存在，重置码已发送至您的邮箱。',
    maDatLai: '重置码',
    datLaiMatKhau: '重置密码',
  },
  menu: {
    tongQuan: '总览',
    daoTao: '教学培训',
    nhanSu: '人事',
    khachHang: '客户',
    nhanVienKinhDoanh: '销售人员',
    giaoVienNhanSu: '教师',
    nhanSuNguoiDung: '员工档案',
    coCauToChuc: '组织架构',
    chucVu: '职务',
    hocVien: '学员',
    doanhThu: '营收',
    khachHangDs: '客户',
    khoaHoc: '课程',
    sanPham: '产品',
    lopHoc: '班级',
    choXepLop: '待分班',
    taiLieu: '资料',
    khoaOnline: '线上课程',
    thongKeCrm: '统计',
    hocPhi: '学费',
    quanTri: '系统管理',
    taiKhoan: '账号',
    nguoiDung: '用户',
    phanQuyen: '权限管理',
    thietLap: '通用设置',
    nhatKy: '系统日志',
  },
  hocPhi: {
    hoiThu: '登记一笔 {{soTien}} 的收款？学员的欠款将相应减少。',
    hoiSua: '将该笔收款改为 {{soTien}}？欠款将按新金额重新计算。',
    tabCongNo: '欠款',
    tabSoThu: '收款记录',
    thuTien: '收款',
    suaKhoanThu: '编辑收款',
    xoaKhoanThu: '删除收款',
    xacNhanXoa: '删除 {{hocVien}} 的 {{soTien}} 收款记录？欠款将相应增加。',
    lop: '班级',
    tatCaLop: '全部班级',
    chonLop: '选择班级',
    hocVien: '学员',
    chonHocVien: '选择学员',
    hocPhi: '学费',
    daThu: '已收',
    tongPhaiThu: '应收总额',
    tienDoThu: '收款进度',
    khongCoQuyenXem: '您无权查看学费信息。只有管理员才能跟踪全班的学费；学员只能查看自己的欠款。',
    conNo: '尚欠',
    conNoNhan: '尚欠',
    daDuUpper: '已缴清',
    quaHan: '已逾期',
    chiConNo: '仅显示尚欠的人',
    khongCoCongNo: '没有符合筛选条件的欠款',
    chuaCoKhoanThu: '尚未登记任何收款',
    soTien: '金额',
    ngayThu: '收款日期',
    phuongThuc: '方式',
    soPhieu: '单据号',
    ghiChu: '备注',
    nguoiThu: '收款人',
    pt: {
      TienMat: '现金',
      ChuyenKhoan: '转账',
      Khac: '其他',
    },
  },
  nguoiDung: {
    gomPhongCon: '包含下级部门',
    themNguoiDung: '新增用户',
    suaNguoiDung: '编辑用户',
    timTheo: '姓名、邮箱、手机号',
    trangThaiNhanSu: '员工',
    DangLamViec: '在职',
    DaNghi: '已离职',
    hoSo: '档案',
    hoSo_GiaoVien: '教师档案',
    hoSo_HocVien: '学员档案',
    hoSo_NhanVien: '员工档案',
    bangCap: '学历证书',
    chuyenMon: '专业方向',
    ngayVaoLam: '入职日期',
    truongLop: '学校 / 年级',
    khachHangCrm: '客户（CRM）',
    khachHangCrmChon: '选择已有客户…',
    khachHangCrmGoiY: '可选——将此档案与 CRM 中已购买的客户关联，避免同一个人重复建档。',
    tenPhuHuynh: '家长姓名',
    sdtPhuHuynh: '家长手机号',
    chucVu: '职务',
    chuaGanChucVu: '尚未指定职务',
    ngaySinh: '出生日期',
    diaChi: '地址',
    cccd: '身份证号',
    soTaiKhoan: '银行账号',
    tenNganHang: '开户银行',
    lienKetMxh: '社交媒体链接',
    duongDanMxh: '链接或电话号码…',
    themMxh: '添加链接',
    tepHoSo: '档案文件',
    taiTep: '上传文件',
    chuaCoTep: '暂无文件——合同、学历证书扫描件、身份证扫描件…',
    gioiHanTep: '仅支持 PDF、Word、Excel · 每个文件最大 20 MB',
    soTepDaDung: '已使用 {{so}}/{{toiDa}} 个文件',
    datTenTep: '为文件命名',
    doiTenTep: '重命名文件',
    tenHienThi: '显示名称',
    viDuTenTep: '例如：2026 年劳动合同',
    giuDuoiTep: '无需输入扩展名——系统会自动保留（.pdf、.docx…）',
    hoiXoaTep: '删除文件「{{ten}}」？删除后无法恢复。',
    phongBan: '部门',
    chuaXepPhongBan: '尚未编入组织架构',
    taiKhoan: '账号',
    chuaCoTaiKhoan: '暂无',
    nguoiSoHuu: '用户',
    khongGanAi: '不关联任何人',
    taoTaiKhoanDangNhap: '创建登录账号',
    khongCanDangNhap: '此人将无法登录。可以稍后在「账号」标签页为其创建账号。',
    giaiThichGanNguoi: '如果这是不属于任何人的技术账号，请留空。',
    hoiXoa: '删除用户「{{ten}}」？删除后无法恢复。如果他已有数据，请标记为「已离职」而不是删除。',
    giaiThichVoHieuHoa: '停用仅会阻止登录。此人的档案及全部数据均保持不变。',
  },
  nhatKy: {
    timTheo: '操作名称、操作人',
    module: '模块',
    hanhDong: '操作',
    thoiDiem: '时间',
    nguoiThucHien: '操作人',
    thaoTac: '指令',
    soBanGhi: '记录数',
    ketQua: '结果',
    thanhCong: '成功',
    thatBai: '失败',
    chiThatBai: '仅显示失败的操作',
    khongCoBanGhi: '尚未记录任何操作',
    xemChiTiet: '查看详情',
    truongDaDoi: '已变更字段',
    thamSo: '指令参数',
    diaChiIp: 'IP',
  },
  hanhDongNhatKy: {
    Them: '新增',
    Sua: '修改',
    Xoa: '删除',
    XacThuc: '认证',
    Khac: '其他',
  },
  thongKe: {
    loaiThongKe: '统计维度',
    kyMacDinh: '默认周期',
    khoangSai: '开始日期必须早于或等于结束日期。',
    loai: {
      KhoaHoc: '课程',
      SanPham: '产品',
      Elearning: '线上学习',
      DoiNhom: '团队',
    },
    loaiMoTa: {
      KhoaHoc: '各门课程的销售营收。',
      SanPham: '各件产品的营收——书籍、教具。',
      Elearning: '',
      DoiNhom: '各部门的营收，按客户档案创建人统计。',
    },
    locTheo: {
      KhoaHoc: '仅限这些课程',
      SanPham: '仅限这些产品',
      Elearning: '',
      DoiNhom: '仅限这些团队',
    },
    boLoc: '清除筛选',
    dangLoc: '正在筛选 {{so}} 项——本页所有数字仅统计已选部分。',
    elearningMoTa: '只统计数量，不统计金额：线上课程不与订单关联——由管理员手动授予学习权限。',
    chuaCoKhoaMo: '目前没有开放中的线上课程。草稿状态的课程不计入此处——课程编写完成后请改为「开放中」。',
    elearningGoiY: '学习数据在上方一行。线上学习的营收按设计并不存在。',
    soKhoaOnline: '开放中的课程',
    soNguoiHoc: '在学人数',
    soLuotGhiDanh: '报名人次',
    tyLeHoanThanh: '完成率',
    baiTrenTong: '{{da}}/{{tong}} 课',
    tongDoanhThu: '营收总额',
    soDon: '订单数',
    giaTriDonTb: '平均订单金额',
    daThu: '已收',
    conThieu: '尚缺 {{so}}',
    thuDu: '已收齐',
    soKyTruoc: '与上期相比',
    chuaCoKyTruoc: '暂无上期可比较',
    soDonNgan: '{{so}} 单',
    khongXacDinh: '未确定',
    chuaCoDon: '本期尚无任何订单',
    chuaCoKhach: '尚无任何客户',
    doanhThuTheoThang: '各月营收',
    doanhThuTheoThangMoTa: '按登记时锁定的汇率折算为 VND——历史报表数字不会变动。',
    theoCaNhan: '按个人统计营收',
    theoCaNhanMoTa: '按客户档案创建人统计。没有创建人的旧订单归入「未确定」。',
    theoDoiNhom: '按团队统计营收',
    theoDoiNhomMoTa: '按客户档案创建人所属部门统计。',
    theoSanPham: '按商品统计营收',
    theoSanPhamMoTa: '包含课程和其他产品。',
    theoNguon: '按客户来源统计营收',
    theoNguonMoTa: '客户自行注册的不计入任何人的个人业绩。',
    pheu: '销售漏斗',
    pheuMoTa: '各环节的客户数量，以及占客户总数的比例。',
  },
  nguonKhachHang: {
    NhanVienTao: '员工创建',
    TuDangKy: '客户自行注册',
  },
  khoaOnline: {
    ten: '课程名称',
    trangThai: '状态',
    moTa: '说明',
    chuaCo: '尚无任何线上课程',
    chuaCoBai: '本课程尚无任何课时',
    chuaCoHocVien: '尚未为任何人授予学习权限',
    themKhoa: '新增线上课程',
    suaKhoa: '编辑课程',
    soBaiHoc: '课时数',
    soHocVien: '学员',
    tienDo: '进度',
    taoRaLaNhap: '新建课程始终为草稿状态——内容编写完成后请改为开放中。',
    dangNhapGoiY: '课程处于草稿状态，学员尚看不到，也无法授予学习权限。内容编写完成后请编辑课程并改为开放中。',
    tabBaiHoc: '课时',
    tabHocVien: '学员',
    themBai: '新增课时',
    suaBai: '编辑课时',
    xoaBai: '删除课时',
    xoaBaiHoi: '删除课时「{{ten}}」？学员在该课时的学习进度也会一并丢失。',
    tieuDeBai: '课时标题',
    thuTu: '排序',
    noiDung: '内容',
    baiTrong: '该课时尚无内容。',
    congKhai: '公开',
    congKhaiGoiY: '任何登录用户都可阅读，无需报名——即使已过期也能看。适用于介绍课、试听课。',
    danhDauDaHoc: '标记为已学',
    capQuyen: '授予学习权限',
    hoiTaoKhoa: '创建这门线上课程？新课程为草稿状态，暂时无人可见。',
    hoiLuuKhoa: '保存对该课程的修改？',
    hoiLuuBai: '保存这个课时？',
    hoiCapQuyen: '为已选学员授予本课程的学习权限？',
    thuQuyen: '收回学习权限',
    thuQuyenHoi: '收回 {{ten}} 的学习权限？已有学习进度仍会保留，重新授权后可继续学习。',
    hocVien: '学员',
    hetHan: '到期',
    hetHanGoiY: '留空 = 永久有效。',
    ghiChuCap: '备注',
    ghiChuVd: '例如：订单 #123、试听、IELTS 班赠送',
    nguoiCap: '授权人',
    vinhVien: '永久',
  },
  trangThaiKhoaOnline: {
    Nhap: '草稿',
    DangMo: '开放中',
    NgungCapMoi: '停止新增授权',
  },
  tongQuan: {
    viecCanLam: '待办事项',
    khongCoViec: '没有需要处理的事项',
    buoiHomNay: '今日课次',
    buoiSapToi: '即将开始的课次',
    buoiThu: '第 {{so}} 次课',
    lopDangHoatDong: '进行中的班级',
    buoiQuaHan: '已过期但未确认考勤的课次',
    baiChuaCham: '待批改的作业',
    choXepLop: '待分班的学员',
    chuaCoNoiDung: '系统处于初始状态——尚未配置任何业务。请先为您的中心创建账号和权限组。',
  },
  phanTrang: {
    dangXem: '显示第 {{tu}}–{{den}} 条，共 {{tong}} 条',
    soDong: '每页行数',
    trangTruoc: '上一页',
    trangSau: '下一页',
  },
  anh: {
    chonAnh: '选择图片',
    doiAnh: '更换图片',
    goAnh: '移除图片',
    goiY: 'JPG、PNG、WebP 或 GIF · 最大 5 MB',
  },
  loaiNguoiDung: {
    NhanVien: '其他员工',
    NhanVienKinhDoanh: '销售人员',
    GiaoVien: '教师',
    TroGiang: '助教',
    HocVien: '学员',
  },
  lopHoc: {
    hoiThemHocVien: '将 {{soLuong}} 名学员报名到本班级？',
    hoiGoHocVien: '将「{{ten}}」移出班级？已记录的考勤和学费仍会保留。',
    tieuDe: '班级',
    themMoi: '新增班级',
    ten: '班级名称',
    giaoVienChinh: '主讲教师',
    troGiang: '助教',
    hinhThuc: '上课形式',
    phongHoc: '教室',
    linkHoc: '线上上课链接',
    hocPhi: '学费',
    sucChuaToiDa: '最大容量',
    khongGioiHan: '不限',
    ngayKhaiGiang: '开班日期',
    ngayKetThuc: '结课日期',
    trangThai: '状态',
    ghiChu: '备注',
    soHocVien: '学员',
    hocVien: '班级学员',
    xemThongTin: '查看信息',
    hocVienCuaLop: '{{lop}} 班的学员',
    nhanVienKinhDoanh: '销售人员',
    themTrucTiep: '或添加已有学员',
    themTrucTiepGiaLop: '适用学费取自班级的标准价',
    themHocVien: '添加学员',
    goHocVien: '移出班级',
    hocPhiApDung: '适用学费',
    ngayVaoLop: '入班日期',
    hoanTat: '完成建班',
    huyLop: '取消班级',
    xacNhanHuy: '取消这个班级？考勤和学费历史仍会保留。',
    chuaCoLop: '尚无任何班级',
    chonGiaoVien: '选择教师…',
    timGiaoVien: '输入教师姓名搜索…',
    khoaHocCuaLop: '本班所授课程',
    chuaGanKhoa: '尚未指定课程',
    toiDaNKhoa: '（最多 {{so}} 门）',
    chonKhoaHoc: '选择课程...',
    timKhoaHoc: '搜索课程',
    daDatToiDaKhoa: '已达到最多 {{so}} 门课程',
    chonTroGiang: '选择助教…',
    timTroGiang: '输入助教姓名搜索…',
    timHocVien: '输入学员姓名搜索…',
    locTrangThai: '按状态筛选',
    nhapGoiY: '草稿班级只有您自己能看到。点击「完成建班」即可公开。',
    xemChiTiet: '查看详情',
    siSo: '班额',
    buoiDaHoc: '已上课次',
    thoiGian: '时间',
    tabLichTatCa: '课表',
    locTheoLop: '按班级筛选',
    lichTuNgay: '开始日期',
    lichDenNgay: '结束日期',
    lichXoaLoc: '清除筛选',
    dangLocKhoangNgay: '正在按日期区间筛选——日历的切换月份按钮不会改变数据。清除筛选后可恢复按月查看。',
    tabDanhSach: '班级列表',
    tabTongQuan: '总览',
    tabHocVien: '学员',
    tabLich: '课表与考勤',
    tabBaiTap: '作业',
    tabHocPhi: '学费',
    tabTaiLieu: '资料',
    suaThongTin: '编辑班级信息',
    luuThongTin: '保存班级信息',
    daChon: '已选 {{soLuong}}',
    sucChuaConLai: '已选 {{daChon}} / 上限 {{toiDa}}',
  },
  hinhThucHoc: {
    ChuaChon: '— 请选择 —',
    Online: '线上',
    Offline: '线下',
    KetHop: '混合',
  },
  trangThaiLopHoc: {
    Nhap: '草稿',
    SapKhaiGiang: '即将开班',
    DangHoc: '在读中',
    DaKetThuc: '已结课',
    DaHuy: '已取消',
  },
  trangThaiHocVien: {
    DangHoc: '在读',
    BaoLuu: '休学保留',
    ChuyenLop: '已转班',
    DaNghi: '已退学',
  },
  lich: {
    thang: '月',
    tuan: '周',
    danhSach: '列表',
    homNay: '今天',
    truoc: '上一期',
    sau: '下一期',
    kieuBang: '表格',
    kieuLich: '日历',
  },
  chiTietBuoi: {
    tabThongTin: '课次信息',
    tabDiemDanh: '考勤',
    tabNhanXet: '评价',
    tabBaiTap: '作业',
    tabTaiLieu: '资料',
    quayLaiLich: '返回课表',
    buoiTruoc: '上一课次',
    buoiSau: '下一课次',
    chonBuoi: '选择其他课次',
    khongTimThayBuoi: '未找到该课次',
    taiLieuTheoLop: '资料关联到整个班级，不按单个课次关联——这是班级的公共资料。',
  },
  nhanXetBuoi: {
    tieuDe: '学员对本课次的评价',
    cuaToi: '我的评价',
    noiDung: '内容',
    noiDungGoiY: '今天的课上得怎么样？有什么需要改进的？',
    mucHaiLong: '总体满意度',
    theoTieuChi: '按评价标准打分（5 分制）',
    khongChon: '不评价',
    chamNguoiDungLop: '评价授课人员',
    vaiTro: {
      GiaoVien: '教师',
      TroGiang: '助教',
    },
    chuaChonDiem: '未打分',
    boChon: '再次点击已选分值即可取消打分',
    khongCoTieuChi: '中心尚未配置教学评价标准。请联系管理员在「评价标准」（HRM）中添加。',
    diemDaCham: '已打分数',
    chamChung: '对本课次整体打分',
    gui: '提交评价',
    capNhat: '更新评价',
    hoiGui: '提交对本课次的评价？',
    hoiCapNhat: '更新已提交的评价？原有内容将被覆盖。',
    daGui: '评价已提交',
    chuaCo: '本课次尚无任何评价',
    nhanXetHocVien: '学员评价',
    nhanXetGiaoVien: '教师对学员的评价',
    chuaCoNhanXetGv: '本课次教师尚未评价任何学员',
    ghiONhanXetGv: '教师的评价记录在「考勤」标签页，按每位学员分别填写。',
    giaiThichChoGv: '此处的评价栏是学员对本课次提出意见的专属渠道，因此只有本班在读学员才能提交。若要评价某位学员，请打开「考勤」标签页——每位学员都有独立的评价栏。',
  },
  buoiHoc: {
    hoiSinhLich: '按所选频率生成课表？',
    hoiSinhThem: '在现有课表中追加课次？不会删除任何课次。',
    hoiSinhLai: '重新生成将删除尚未上课的课次并创建新课表。已确认的课次保持不变。是否继续？',
    hoiChotBuoi: '确认本课次？未考勤的人将被记为缺席，确认后课次时间不可修改、不可取消、不可删除。',
    thuTuNgan: '第 {{n}} 次课',
    sinhThemBuoi: '追加课次',
    xoaBuoi: '删除课次',
    doiTrangThai: '更改状态',
    moTaDoiTrangThai: '第 {{thuTu}} 次课 — {{gio}}。请选择新状态：',
    dangApDung: '当前状态',
    laHocBu: '为补课课次',
    macDinhTheoLop: '留空 = 跟随班级',
    tuNgay: '生成起始日',
    daChot: '已确认 {{soLuong}} 个课次',
    goiYSinhThem: '在现有课表中追加课次——不会删除任何课次，新课次继续往后编号。若只追加一次课（补课、复习），课次数量填 1。',
    canhBaoSinhLai: '重新生成将删除尚未上课的课次并创建新课表。已确认的课次保持不变。',
    xacNhanSinhLai: '删除 {{soLuong}} 个未上课的课次并生成新课表？已确认的 {{daChot}} 个课次仍会保留。若想在不丢失原课表的情况下追加课次，请使用「追加课次」或「追加生成课次」。',
    xacNhanHuyBuoi: '取消第 {{thuTu}} 次课（{{gio}}）？记录仍会保留，以便历史完整。',
    xacNhanXoaBuoi: '彻底删除第 {{thuTu}} 次课（{{gio}}）？删除后无法恢复。如果该课次已经上过，建议取消而不是删除。',
    tieuDe: '课次',
    lich: '课表',
    thuTu: '课次',
    thoiGian: '时间',
    giaoVien: '教师',
    giaoVienRieng: '单独教师',
    phongHoc: '教室',
    linkHoc: '线上上课链接',
    ghiChu: '备注',
    troGiang: '助教',
    troGiangTheoLop: '班级的助教——本课次未单独指派助教。',
    theoLop: '（跟随班级）',
    khongCoTroGiang: '本班尚无助教',
    hocBu: '补课',
    hocOnline: '线上上课',
    nhom: {
      sapToi: '即将开始',
      daQua: '已结束',
    },
    trangThai: '状态',
    diemDanh: '考勤',
    chuaCoLich: '本班尚无课表',
    sinhLich: '生成课表',
    sinhLaiLich: '重新生成课表',
    thuTrongTuan: '上课星期',
    gioBatDau: '开始时间',
    gioKetThuc: '结束时间',
    ketThucTheo: '结束依据',
    theoSoBuoi: '课次数量',
    theoNgay: '结课日期',
    ngayLoaiTru: '休息日（不上课）',
    ngayLoaiTruGoiY: '每行一个日期，格式为 2026-04-30',
    xemTruoc: '预览课表',
    daSinh: '将生成 {{soLuong}} 个课次',
    huyBuoi: '取消本课次',
    chotBuoi: '确认课次',
    chotBuoiGoiY: '未考勤的人将被记为缺席。',
    tuDiemDanh: '快速考勤',
  },
  diemDanh: {
    hoiLuu: '保存 {{soLuong}} 名学员的考勤？',
    tieuDe: '考勤',
    hocVien: '学员',
    tuKhai: '学员自报',
    chinhThuc: '正式',
    lyDoVang: '缺席原因',
    thieuLyDoVang: '尚有 {{soLuong}} 名学员未填写缺席原因：{{ten}}。请填写原因后保存，或使用「确认课次」将其记为「未考勤」。',
    thieuLyDoNgan: '仍有缺席学员未填原因',
    nguon: '来源',
    chuaGhiNhan: '未记录',
    khacTuKhai: '与自报不符',
    luu: '保存考勤',
    daLuu: '考勤已保存',
    chiXem: '您只有查看本考勤表的权限。',
    nhanXetGv: '教师评语',
    nhanXetGoiY: '发音、参与度、家庭作业…',
    buoiDaChot: '课次已确认——仍可修改考勤和评语，但不能修改课次时间。',
  },
  trangThaiDiemDanh: {
    CoMat: '出勤',
    Vang: '缺席',
    DiMuon: '迟到',
    VangCoPhep: '请假',
  },
  nguonDiemDanh: {
    HocVienTuKhai: '学员自报',
    GiaoVien: '教师',
    QuanTri: '管理员',
  },
  trangThaiBuoiHoc: {
    DaLenLich: '已排课',
    DaHoanThanh: '已完成',
    DaHuy: '已取消',
    ChuyenLich: '已改期',
  },
  tinhTrangBuoi: {
    ChuaBatDau: '未开始',
    DangDienRa: '进行中',
    ChuaChot: '未确认',
    DaXong: '已完成',
    ChuyenLich: '已改期',
    DaHuy: '已取消',
  },
  thu: {
    Monday: '周一',
    Tuesday: '周二',
    Wednesday: '周三',
    Thursday: '周四',
    Friday: '周五',
    Saturday: '周六',
    Sunday: '周日',
  },
  hocLieu: {
    luuDiem: '保存分数',
    daSuaChuaLuu: '已修改 {{soLuong}} 份作业，尚未保存',
    hoiLuuDiem: '保存 {{soLuong}} 份提交作业的分数和评语？',
    hoiXoaBaiTap: '删除作业「{{ten}}」？学员已提交的内容也会一并丢失。',
    baiTap: '作业',
    taiLieu: '资料',
    themBaiTap: '布置作业',
    themTaiLieu: '新增资料',
    tieuDe: '标题',
    moTa: '说明',
    hanNop: '提交截止',
    buoiHoc: '课次',
    loai: '分类',
    ganLop: '关联班级',
    ganLopGoiY: '留空 = 全中心通用资料',
    lopChung: '通用',
    tep: '附件',
    themTep: '添加文件',
    keoThaTep: '选择文件（PDF、Word、Excel、图片 — 最大 20MB）',
    daNop: '已提交',
    chuaCoBaiTap: '尚无任何作业',
    chuaCoTaiLieu: '尚无任何资料',
    xemBaiNop: '查看提交内容',
    lanNop: '提交次数',
    thoiDiemNop: '提交时间',
    diem: '分数',
    nhanXet: '评语',
    cham: '批改打分',
    nguoiTaiLen: '上传人',
  },
  trangThaiBaiNop: {
    DaNop: '已提交',
    NopMuon: '逾期提交',
    DaCham: '已批改',
  },
  loaiTaiLieu: {
    GiaoTrinh: '教材',
    BaiGiang: '讲义',
    ThamKhao: '参考资料',
    DeThi: '试卷',
    Khac: '其他',
  },
  taiKhoan: {
    tieuDe: '用户账号',
    username: '用户名',
    hoTen: '姓名',
    ngaySinh: '出生日期',
    loaiNguoiDung: '角色',
    email: '邮箱',
    soDienThoai: '电话号码',
    diaChi: '地址',
    quyen: '权限组',
    trangThai: '状态',
    hoatDong: '启用',
    voHieuHoa: '停用',
    themMoi: '新增账号',
    suaTieuDe: '更新账号',
    datLaiMatKhau: '重置密码',
    canDoiMatKhau: '需修改密码',
    wizardGoiY: '如已有权限组，请选择',
    chonQuyen: '选择权限组…',
    timQuyen: '输入权限组名称搜索…',
    buocDoiMk: '首次登录时强制修改密码',
    buocDoiMkGoiY: '建议开启：由您代设的密码，您也知道。',
    datLaiGoiY: '用户将在下次登录时被要求重新设置密码。',
    matKhau: '密码',
    matKhauMoi: '新密码',
    themTaiKhoan: '新增账号',
    suaTaiKhoan: '更新账号',
    buocDoiMatKhau: '首次登录时强制修改密码',
    phaiDoiMatKhau: '需修改密码',
    hoiXoa: '删除账号「{{ten}}」？用户档案仍会保留，只是失去登录通道。',
    hoiDatLaiMatKhau: '为「{{ten}}」重置密码？他们下次登录时须重新设置密码，原密码立即失效。',
    HoatDong: '启用',
    VoHieuHoa: '停用',
  },
  quyen: {
    hoiLuu: '保存权限组「{{ten}}」？该组中所有账号的权限将立即随之变更。',
    tieuDe: '访问权限管理',
    tenQuyen: '权限组名称',
    moTa: '说明',
    soTaiKhoan: '账号数',
    themMoi: '新增权限组',
    suaTieuDe: '编辑权限组',
    maTran: '权限矩阵',
    chucNang: '功能',
    soO: '权限项数',
    cauHinh: '配置权限',
    taoVaCauHinh: '创建并配置权限',
    themMoiGoiY: '先给权限组命名；下一步再选权限，有角色模板可用，不必从头逐项勾选。',
    batDauTuMau: '从角色模板开始',
    apMauTieuDe: '应用角色模板',
    apMauHoi: '用「{{ten}}」的权限集（{{so}} 项）替换当前已选的全部权限？之后仍可逐项微调。',
    dangDung: '{{so}} 个账号正在使用',
    tongDaChon: '已选 {{so}} 项',
    chiXem: '您没有「配置权限矩阵」的权限，因此只能查看。如需修改请联系系统管理员。',
    khongThayNhom: '未找到该权限组。它可能已被删除。',
    veDanhSach: '返回权限组列表',
    canNhac: {
      DiemDanh: {
        Chot: '封存考勤表，并将所有未申报的人记为缺席。不可再修改。',
      },
      XepLop: {
        Duyet: '代替销售方做决定，会影响他们的订单。不可撤销。',
      },
      LopHoc: {
        HoanTat: '班级脱离草稿状态并对所有相关人员可见。不可逆。',
        Huy: '取消班级及其全部课次。数据仍在，但班级停止运作。',
      },
      BuoiHoc: {
        Huy: '取消课次，学员会在课表上看到该课次已取消。',
      },
      PhanQuyen: {
        CauHinhQuyen: '拥有此权限的人可以自行为所在权限组授予任何其他权限。仅授予管理员。',
      },
      DoiMatKhauNguoiKhac: {
        Sua: '重置他人密码，等同于能登录他们的账号。',
      },
      DoanhThu: {
        ThuTien: '确认已收到客户款项。建议与开单人员分开。',
      },
      HocPhi: {
        ThuTien: '将学员已缴费登记入学费账簿。',
      },
      ThietLapChung: {
        CauHinhTien: '修改客户将要汇款的收款信息（转账二维码）。',
      },
      NhanXetBuoiHoc: {
        Xem: '阅读课次中所有人的评价。不要授予学员——他们会看到同班同学的私下反馈。',
      },
      LopHocToanTrungTam: {
        Xem: '查看中心的所有班级，含其中学员的档案和联系方式——不限于自己负责的班级。',
        Sua: '可以编辑并非自己负责的班级。',
      },
      chung: {
        Chot: '结账封存——之后不可再修改。',
        Duyet: '不可撤销的决定。',
        ThuTien: '涉及资金的操作。',
        Huy: '取消但保留记录。',
      },
    },
    phamViDuLieu: '数据范围',
    phamViGoiY: '这些权限不会开放更多功能，而是扩大用户可见的数据范围。不授予：只能看到自己负责的班级。授予：可看到中心的所有班级，含其中学员的档案和联系方式。',
    oCu: '该组仍保留着目录中已不存在的旧权限：{{ds}}。保存后仍会原样保留，但它们不起作用——如需清理请联系系统管理员。',
  },
  hanhDong: {
    Xem: '查看',
    Them: '新增',
    Sua: '修改',
    Xoa: '删除',
    Duyet: '批准 / 拒绝',
    Chot: '结账封存',
    Huy: '取消',
    SinhLich: '生成课表',
    ThuTien: '收款',
    Cham: '批改打分',
    TuLam: '自行操作（本人的）',
    DocTep: '阅读附件',
    QuanLyTep: '上传 / 删除文件',
    CauHinhTien: '配置收款方式',
    CauHinhQuyen: '配置权限矩阵',
    HoanTat: '完成建班',
    XepNhanSu: '将员工编入部门',
    GuiXepLop: '提交分班申请',
    XuatBan: '发布',
    ChuyenCrm: '转入 CRM',
  },
  tieuChi: {
    them: '新增标准',
    sua: '编辑标准',
    ten: '标准名称',
    moTa: '给评分人的提示',
    nhomLabel: '分组',
    chuaCo: '尚无任何评价标准',
    soLanDaCham: '已评分',
    hoiLuu: '保存这条标准？',
    giaiThich: '评价标准用于 5 分制打分。销售组由管理者按月度周期评分；教学组由学员在每次课中评分。',
    khongDoiNhom: '该标准已有评分，因此无法更改分组。',
    ngungDungGoiY: '取消勾选即停用——新表单中不再显示，旧表单仍可查看。已评过分的标准无法删除，否则会使所有已评价周期的数据失真。',
    nhom: {
      KinhDoanh: '销售人员',
      GiangDay: '教师 / 助教',
    },
    nhomMoTa: {
      KinhDoanh: '由管理者按月度周期评分',
      GiangDay: '由学员在每次课中评分',
    },
  },
  thongKeNs: {
    tabKinhDoanh: '销售',
    tabGiaoVien: '教师',
    tabTroGiang: '助教',
    hoTen: '姓名',
    soHocVien: '学员数',
    soLop: '班级数',
    soBuoiDayDu: '足额授课次数',
    soBuoiHuy: '取消课次数',
    chatLuongChamSoc: '服务质量',
    chatLuongGiangDay: '教学质量',
    soPhieu: '{{so}} 份评价表',
    soLopNgan: '{{so}} 个班',
    cham: '评分',
    chamTieuDe: '为销售人员评分',
    ky: '评价周期',
    kyGoiY: '每名员工每个周期一份评价表——重新评分即是修改原表。',
    nhanXet: '管理者评语',
    hoiLuuPhieu: '保存 {{ten}} 在 {{ky}} 周期的评价表？',
    xepHangDoanhThu: '按营收排名',
    xepHangHocVien: '按学员数排名',
    xepHangHocVienMoTa: '由此人带来并且确实入学的客户。',
    xepHangBuoiDay: '按足额授课次数排名',
    xepHangChatLuong: '按教学质量排名',
    xepHangChatLuongMoTa: '学员在每次课中评分的平均值。',
    chuaCoNhanVienKd: '尚无任何销售人员。',
    chuaCoNguoi: '该角色下尚无任何人员。',
    chuaCoHocVien: '本周期尚无客户入学。',
    chuaCoBuoi: '本周期尚无已完成的授课课次。',
    chuaCoDanhGia: '本周期尚无任何评价。',
    chuaCoTieuChiKd: '尚无销售组的评价标准——请先在「评价标准」标签页中添加，然后才能评分。',
    chuaCoTieuChiGd: '尚无教学组的评价标准——请在「评价标准」标签页中添加，以便学员进行细项评分。',
  },
  chucNang: {
    TaiKhoan: '登录账号',
    HoSoNguoiDung: '用户档案',
    LopHoc: '班级',
    GhiDanhLop: '学员报名入班',
    XepLop: '从 CRM 分班',
    BuoiHoc: '课次',
    DiemDanh: '考勤',
    NhanXetBuoiHoc: '课次评价',
    BaiTap: '作业',
    BaiNopBaiTap: '学员提交的作业',
    BaiKiemTra: '测验',
    BaiLamKiemTra: '学员的答卷',
    KhoaOnline: '线上课程（内容编写）',
    GhiDanhKhoaOnline: '授予线上课程学习权限',
    HocOnline: '线上学习',
    TaiLieu: '资料',
    HocPhi: '学费',
    ThongKe: '统计',
    LopHocToanTrungTam: '中心的所有班级',
    NhatKyHeThong: '系统日志',
    TrangDich: '着陆页',
    LienHeLanding: '着陆页咨询',
    PhanQuyen: '权限管理',
    ThietLapChung: '通用设置',
    Anh: '图片（logo、封面图、二维码）',
    DoiMatKhauNguoiKhac: '修改他人密码',
    NhanSu: '员工',
    ChucVu: '职务',
    PhongBan: '部门',
    TieuChiDanhGia: '评价标准',
    ThongKeNhanSu: '员工统计',
    DoanhThu: '营收',
    ThongKeDoanhThu: '营收统计',
    KhachHang: '客户',
    ChamSocKhachHang: '客户维护',
    KhoaHoc: '课程',
    SanPham: '产品',
  },
  heThong: {
    Hrm: 'HRM — 人事',
    Crm: 'CRM — 客户',
    Lms: 'LMS — 教学培训',
    DungChung: '三大系统通用',
    chuyenHeThong: '切换系统',
    dungChungGoiY: '这些管理功能为三大系统所共用，因此在所有标签页中都会显示。',
  },
  hrm: {
    moTaNvkd: '销售人员档案：业绩指标、负责的客户、提成。',
    moTaGiaoVien: '人事视角下的教师：合同、薪资、考勤。与 LMS 中的教师是同一个人，只是跟踪的信息不同。',
  },
  phuongThucThanhToan: {
    TienMat: '现金',
    ChuyenKhoan: '转账',
    Khac: '其他',
  },
  donViTien: {
    VND: 'VND — 越南盾',
    USD: 'USD — 美元',
    EUR: 'EUR — 欧元',
    CAD: 'CAD — 加拿大元',
  },
  crmLoc: {
    locThem: '更多筛选',
    xoaLoc: '清除筛选',
    doiNhom: '团队',
    chuaCoTag: '尚无部门被标记为「销售」。',
    denCoCau: '前往组织架构添加标记 →',
    nhanVien: '负责员工',
    nguon: '客户来源',
    nguonNhanVien: '员工创建',
    nguonTuDangKy: '客户自行注册',
    taoTuNgay: '建档起始日',
    denNgay: '截止日期',
    hinhThuc: '付款方式',
    sanPham: '产品',
    theoNguoiMangKhach: '团队和员工均按「带来客户的人」统计——与统计页面口径一致。客户自行注册的不归属任何团队。',
  },
  khachHang: {
    them: '新增客户',
    sua: '编辑客户',
    hoTen: '姓名',
    email: '邮箱',
    soDienThoai: '电话号码',
    linkFacebook: 'Facebook 链接',
    lienHe: '联系方式',
    phuongThuc: '付款方式',
    phuongThucGoiY: '该客户的默认付款方式——每次登记仍会单独记录。',
    tinhTrang: '状况',
    daMua: '已购买',
    chuaMua: '未购买',
    soKhoa: '课程数',
    tongMua: '购买总额',
    hocVien: '学员档案',
    capTaiKhoan: '开通学员账号',
    sdtDaCo: '该号码已属于 {{ten}}。',
    moHoSoNay: '打开该客户档案',
    hoiCapTaiKhoan: '为 {{ten}} 创建学员档案和登录账号？档案将与该客户硬性关联。',
    capTaiKhoanGoiY: '为 {{ten}} 创建学员档案和登录账号。档案会自动与该客户关联，因此不会同一个人重复建档。',
    matKhauGoiY: '请把此密码告知学员——系统会强制他们在首次登录时修改。',
    chuaVaoHoc: '尚未入学',
    noiHocVien: '关联学员档案',
    noiHocVienGoiY: '客户确实入学后再选择。两边是同一个人但分开存储：在此处改名不会改学员姓名，反之亦然。',
    timTheo: '姓名、电话号码或邮箱',
    chuaCo: '尚无任何客户',
    hoiLuu: '保存客户信息？当前数据将被覆盖。',
    hoiXoa: '删除客户「{{ten}}」？删除后无法恢复。',
  },
  hinhThucChamSoc: {
    GoiDien: '电话',
    ZaloFacebook: 'Zalo / Facebook',
    Email: '邮件',
    GapTrucTiep: '当面会谈',
    Khac: '其他',
  },
  trangThaiKhachHang: {
    Moi: '新客户',
    DangTuVan: '咨询中',
    DaMua: '已购买',
    TuChoi: '已拒绝',
  },
  chiTietNhanSu: {
    tabThongTin: '基本信息',
    tabTep: '档案文件',
  },
  chiTietKhach: {
    tabThongTin: '基本信息',
    tabChamSoc: '维护记录',
    soLanMua: '购买 {{so}} 次',
    tongNhom: '分组合计',
    tongTatCa: '全部合计',
    boSungThanhToan: '补充付款',
    guiYeuCau: '提交建班申请',
    guiYeuCauXepLop: '提交建班申请',
    hoiGuiYeuCau: '为「{{ten}}」提交分班申请？教学部门会在待处理列表中看到该学员。',
    dangChoXepLop: '等待分班中',
    daXepLop: '已进入 {{ten}} 班',
    daHocLop: '已就读：{{ten}}',
    guiLai: '重新提交申请',
    guiLanThu: '这是第 {{so}} 次提交',
    daGuiNLan: '已提交 {{so}} 次',
    lanThu: '第 {{so}} 次',
    lichSuGuiYeuCau: '分班申请提交记录',
    ghiChuYeuCau: '给教学部门的备注',
    ghiChuYeuCauGoiY: '水平、期望上课时间、关于学员的注意事项…',
    lyDoTuChoi: '拒绝原因',
    lyDoTuChoiTruoc: '上次被拒绝的原因',
    nguoiGui: '提交人',
    nguoiXuLy: '处理人',
    suaThongTin: '编辑信息',
    soLanChamSoc: '维护次数',
    tongCamKet: '承诺总额',
    tongDaThu: '已收总额',
    conThieu: '尚缺 {{so}}',
    themChamSoc: '记录一次维护',
    ghiMuaHangMoTa: '登记订单并自动添加一条维护记录',
    chonMatHang: '选择商品…',
    soLuong: '数量',
    ngayMua: '购买日期',
    noiDungMuaGoiY: '留空则系统自动记为「购买 <商品名称>」',
    daThuDu: '已全额收款',
    daThuDuGoiY: '勾选此项，系统会直接记录一笔金额为上述全额的收款。如果客户分期缴纳，请取消勾选——到「已缴金额」标签页逐笔登记。',
    hoiMuaHang: '登记这笔订单？系统将添加一条营收记录和一条维护记录。',
    suaChamSoc: '编辑维护记录',
    chamSocGoiY: '每次联系客户记录一条——最新的显示在前。',
    chuaChamSoc: '尚无任何维护记录',
    thoiDiem: '联系日期',
    hinhThuc: '方式',
    noiDung: '内容',
    noiDungGoiY: '客户说了什么、已发送什么、约定何时回电…',
    trangThaiSau: '本次之后的状态',
    trangThaiSauGoiY: '客户的当前状态「就是」最近一次维护记录的状态——没有单独的字段，因此两处不会出现不一致。',
    hoiLuuChamSoc: '保存这条维护记录？',
    hoiXoaChamSoc: '删除这条维护记录？删除后无法恢复。',
    chuaDangKy: '该客户尚未报名任何课程',
    camKet: '承诺金额',
    daThu: '已收',
    daDu: '已缴清',
    chuaDong: '未缴纳',
    thieu: '尚缺 {{so}}',
    ghiThu: '登记收款',
    suaThu: '编辑收款记录',
    ngayThu: '收款日期',
    nguoiThu: '收款人',
    chuaThu: '本次报名尚未收到任何款项。',
    conThieuGoiY: '尚缺 {{so}}。请填写实收金额——可以分多期缴纳。',
    hoiLuuThu: '保存这笔收款记录？',
    hoiXoaThu: '删除 {{so}} 的这笔收款？这是资金数据。',
  },
  loaiDonHang: {
    KhoaHoc: '课程',
    SanPham: '产品',
  },
  sanPham: {
    them: '新增产品',
    sua: '编辑产品',
    tenSp: '产品名称',
    giaTien: '价格',
    donViTien: '货币',
    donViTinh: '计量单位',
    donViTinhGoiY: '本、套、个…',
    soDonHang: '订单数',
    tongSoLuongBan: '已售',
    trangThaiBan: '状态',
    dangBan: '在售',
    ngungBan: '已停售',
    conBan: '继续销售该产品',
    ngungBanGoiY: '已有订单的产品无法删除——旧订单必须保留所售产品的名称。取消勾选上方选项即可停售，同时保留历史记录。',
    chuaCo: '尚无任何产品',
    hoiLuu: '保存产品？当前信息将被覆盖。',
    hoiXoa: '删除产品「{{ten}}」？删除后无法恢复。',
  },
  trangThaiXepLop: {
    DangCho: '等待中',
    DaXep: '已分班',
    DaHuy: '已取消',
    TuChoi: '已被拒绝',
  },
  loaiMxh: {
    Facebook: 'Facebook',
    Zalo: 'Zalo',
    LinkedIn: 'LinkedIn',
    Telegram: 'Telegram',
    Khac: '其他',
  },
  chucVu: {
    them: '新增职务',
    sua: '编辑职务',
    ten: '职务名称',
    thuTu: '显示顺序',
    soNhanSu: '在任人数',
    trangThai: '状态',
    dangDung: '使用中',
    ngungDung: '已停用',
    conDung: '继续使用该职务',
    ngungDungGoiY: '仍有人在任的职务无法删除——旧档案必须保留已记录的职务。取消勾选上方选项即可停用，同时保留历史记录。',
    chuaCo: '尚无任何职务',
    giaiThich: '职务指的是「职衔」（管理层、部门经理…），不同于业务角色（员工、教师、助教、学员）。职务不会授予任何额外权限——权限仍按账号的权限管理执行。',
    hoiLuu: '保存职务？当前信息将被覆盖。',
    hoiXoa: '删除职务「{{ten}}」？仍有人在任的职务无法删除。',
  },
  tagVaiTro: {
    KinhDoanh: '销售组',
    GiaoVien: '教师组',
    TroGiang: '助教组',
    goiYKinhDoanh: '该部门将出现在客户、营收和统计的团队筛选器中。',
    goiYGiaoVien: '用于识别授课教师组。不出现在业绩筛选器中。',
    goiYTroGiang: '用于识别助教组。不出现在业绩筛选器中。',
    KHAC: '其他（未打标记的部门）',
  },
  coCau: {
    xemNhanSuPhong: '查看该部门的员工名单',
    tagVaiTro: '角色标记',
    khongTag: '不打标记（仅用于描述架构）',
    khongTagGoiY: '未打标记的部门只会出现在本架构树中——不会出现在任何模块的筛选器里。',
    themPhongGoc: '新增部门',
    themPhongBan: '新增部门',
    themPhongCon: '新增下级部门',
    suaPhongBan: '编辑部门',
    tenPhongBan: '部门名称',
    nguoiQuanLy: '负责人',
    chuaChonQuanLy: '尚未选择负责人',
    quanLy: '负责人',
    quanLyChiLaThongTin: '仅为组织信息——不授予任何额外权限。权限仍按账号的权限管理执行。',
    thuTu: '显示顺序',
    moTa: '说明',
    phongGoc: '最高层级部门',
    duoiPhong: '{{ten}} 的下级',
    chuaCoPhongBan: '尚无任何部门——点击「新增部门」开始创建',
    chuaXep: '尚未编入部门',
    themNhanSu: '将员工加入部门',
    chonNhanSu: '选择员工',
    goTenNhanSu: '输入员工姓名搜索…',
    hocVienKhongVaoCoCau: '学员不属于组织架构，因此不在列表中。',
    hoiLuu: '保存部门？当前信息将被覆盖。',
    hoiXoa: '删除部门「{{ten}}」？仍有员工或仍有下级部门的部门无法删除。',
    hoiXepNhanSu: '将 {{soLuong}} 名员工编入「{{ten}}」？他们将离开当前所属部门。',
  },
  xepLop: {
    dangCho: '待分班的学员',
    khongCoAiCho: '没有正在等待分班的学员',
    hocVien: '学员',
    hocPhiTuDon: 'CRM 订单金额',
    nguoiGui: '提交人',
    thoiDiemGui: '提交日期',
    duyet: '批准入班',
    timHocVienCho: '按姓名或电话号码搜索...',
    timKhongThayCho: '未找到匹配的学员',
    canhBaoLechKhoa: '课程不匹配',
    hoiLechKhoa: '该学员的订单属于「{{khoaDon}}」课程，但 {{lop}} 班教授的是「{{khoaLop}}」课程。仍要将学员安排进这个班级吗？',
    vanDuyet: '仍然批准',
    duyetVaoLop: '批准学员入班',
    chonLop: '选择班级',
    khoaDaMua: '已购课程',
    hocPhiSeApDung: '适用学费将为 {{so}}——取自 CRM 订单金额，而非班级价格。',
    hoiDuyet: '以 {{hocPhi}} 的学费将「{{ten}}」安排进 {{lop}} 班？该学员将出现在班级的学费账簿中。',
    huyYeuCau: '取消申请',
    tuChoi: '拒绝',
    tuChoiXepLop: '拒绝分班',
    lyDo: '拒绝原因',
    lyDoGoiY: '暂未开设适合该水平的班级，建议等待下一期…',
    lyDoBatBuoc: '销售方需要知道原因才能答复客户——请说明清楚理由。',
    hoiTuChoi: '拒绝「{{ten}}」的申请？销售方会看到此原因，并可重新提交。',
    lanGuiThu: '第 {{so}} 次提交',
    ghiChuNguoiGui: '提交人的备注',
    hoiHuy: '取消「{{ten}}」的分班申请？申请将作为历史记录保留，若要重新分班，销售方须提交新的申请。',
  },
  khoaHoc: {
    them: '新增课程',
    sua: '编辑课程',
    tenKhoa: '课程名称',
    giaTien: '价格',
    donViTien: '货币',
    soBuoi: '课次数',
    soBuoiNgan: '{{so}} 课次',
    soDangKy: '已售',
    trangThaiBan: '状态',
    dangBan: '在售',
    ngungBan: '已停售',
    conBan: '继续销售该课程',
    ngungBanGoiY: '已有报名的课程无法删除——旧订单必须保留所售课程的名称。取消勾选上方选项即可停售，同时保留订单历史。',
    chuaCo: '尚无任何课程',
    hoiLuu: '保存课程？当前信息将被覆盖。',
    hoiXoa: '删除课程「{{ten}}」？删除后无法恢复。',
  },
  donHang: {
    ghiDon: '登记订单',
    suaDon: '编辑订单',
    lichSu: '订单历史',
    loaiMatHang: '客户购买了什么',
    soLuong: '数量',
    chonSanPham: '选择产品',
    hoiLuu: '保存这笔订单？',
    hoiLuuKemChamSoc: '保存这笔订单？系统将添加一条营收记录和一条维护记录。',
    chuaCo: '尚无任何订单',
  },
  doanhThu: {
    them: '新增报名',
    sua: '编辑报名',
    khachHang: '客户',
    khoaHoc: '课程',
    matHang: '商品',
    chonKhach: '选择客户…',
    chonKhoa: '选择课程…',
    giaGoc: '原价',
    soTien: '收款金额',
    phanTram: '占原价 %',
    tyGia: '折算 VND 汇率',
    tyGiaNgan: '×{{ty}}',
    soLuongNgan: '数量 {{so}}',
    quyDoiVnd: '折算为 VND',
    ngayDangKy: '报名日期',
    tuNgay: '开始日期',
    denNgay: '截止日期',
    tongDoanhThu: '营收总额（VND）',
    soDangKy: '报名数',
    soKhachHang: '客户数',
    giaNiemYet: '标价：{{gia}} · {{so}} 课次。如有减免请修改金额。',
    tyGiaGoiY: '汇率在报名时被「锁定」，不会动态查询——因此汇率波动时上月营收数字不会变动。',
    timTheo: '客户姓名、课程名称或电话号码',
    chuaCo: '尚无任何报名',
    hoiLuu: '保存报名？当前信息将被覆盖。',
    hoiXoa: '删除 {{ten}} 的「{{khoa}}」课程报名？这是营收数据。',
  },
  crm: {
    moTaDoanhThu: '按周期、按班级、按员工汇总的营收。与 LMS 的学费账簿不同：学费账簿记录的是某个班级的每一笔收款，营收则是汇总数字。',
  },
  thietLap: {
    hoiLuu: '保存中心设置？当前信息将被覆盖。',
    tieuDe: '通用设置',
    tenTrungTam: '中心名称',
    tenVietTat: '简称',
    moTa: '说明',
    maTrungTam: '中心代码',
    maTrungTamKhongDoi: '中心代码由系统分配，用于登录——无法更改',
    logo: '中心 logo',
    anhBia: '封面图',
    diaChi: '地址',
    diaChiGoiY: '例如：123 Nguyễn Văn Linh, Hải Châu, Đà Nẵng',
    lienHe: '联系方式',
    lienHeGoiY: '电话号码或邮箱',
    nhomChuyenKhoan: '转账信息',
    nhomChuyenKhoanMoTa: '用于向学员展示应将款项汇往何处。系统不处理支付。',
    soTaiKhoan: '银行账号',
    soTaiKhoanGoiY: '例如：0123456789',
    tenNganHang: '开户银行',
    tenNganHangGoiY: '例如：Vietcombank',
    chuTaiKhoan: '账户名',
    chuTaiKhoanGoiY: '须与银行 App 上显示的名称完全一致',
    chuTaiKhoanLuuY: '汇款人需要核对姓名，以免汇错。',
    anhQr: '转账二维码',
    anhQrGoiY: '从您的银行 App 中截取。',
  },
  loi: {
    KHONG_TIM_THAY_TRUNG_TAM: '没有使用该代码的中心。请核对中心代码（7 个字符，不含数字 0 和 1）。',
    MA_TRUNG_TAM_KHONG_HOP_LE: '中心代码无效——须为 7 个字符，且不含 0/O/1/I/L',
    BAI_TAP_DA_CO_BAI_NOP: '已有学员提交该作业——无法删除。提交内容是他们的学习成果。',
    LOP_HOC_KHONG_HOP_LE: '班级无效，或您对该班级没有权限',
    LOAI_DINH_KEM_KHONG_HO_TRO: '不支持的附件类型',
    TAN_SUAT_TRONG: '尚未选择每周上课的星期',
    NGAY_KHONG_HOP_LE: '日期无效。请重新选择生成课表的起始日期。',
    KHACH_HANG_TRUNG_SO_DIEN_THOAI: '该电话号码已被其他客户使用。请按号码搜索，修改已有的客户。',
    KHACH_HANG_DA_CO_DANG_KY: '该客户已有课程报名记录——这是营收数据，无法删除。',
    KHACH_HANG_KHONG_HOP_LE: '客户无效',
    KHOA_ONLINE_KHONG_HOP_LE: '线上课程无效',
    KHOA_ONLINE_DA_CO_NGUOI_HOC: '该课程已有人在学，因此无法删除。请改为「停止新增授权」以不再新增学员。',
    KHOA_ONLINE_KHONG_NHAN_GHI_DANH: '只有开放中的课程才能授予学习权限。草稿课程尚无内容；已停止新增授权的课程不再接收新学员。',
    BAI_HOC_KHONG_DOI_DUOC_KHOA: '无法将课时转移到其他课程。',
    KHONG_XAC_DINH_DUOC_NGUOI_DUNG: '无法确定当前用户。',
    KHACH_HANG_DA_NOI_HO_SO_KHAC: '该客户已关联到另一份档案。请打开那份档案，而不要新建档案。',
    KHOA_HOC_TRUNG_TEN: '课程名称已存在',
    KHOA_HOC_DA_CO_DANG_KY: '该课程已有报名，无法删除。请取消勾选「继续销售该课程」以停售，同时保留订单历史。',
    KHOA_HOC_KHONG_HOP_LE: '课程无效',
    SAN_PHAM_KHONG_HOP_LE: '产品无效',
    SAN_PHAM_TRUNG_TEN: '产品名称已存在',
    SAN_PHAM_DA_CO_DON_HANG: '该产品已有订单，无法删除。请取消勾选「继续销售该产品」以停售，同时保留订单历史。',
    PHAI_CHON_DUNG_MOT_MAT_HANG: '必须且只能选择一种商品：课程或产品。',
    TY_GIA_KHONG_HOP_LE: '汇率必须大于 0',
    THU_VUOT_CAM_KET: '已收款总额超过客户承诺支付的金额。请核对金额——通常是多打了一个 0。',
    DANG_KY_KHONG_HOP_LE: '报名无效',
    SO_TIEN_KHONG_HOP_LE: '金额无效',
    GIO_KET_THUC_KHONG_HOP_LE: '结束时间必须晚于开始时间（不支持跨夜的班级）',
    SO_BUOI_KHONG_HOP_LE: '课次数量必须在 1 到 500 之间',
    NGAY_KET_THUC_TRUOC_KHAI_GIANG: '结课日期必须晚于开班日期',
    DIEU_KIEN_DUNG_KHONG_HOP_LE: '请只选择一种结束方式：按课次数量或按日期',
    KHONG_SINH_DUOC_BUOI_NAO: '未能生成任何课次——请检查每周上课的星期和日期区间',
    CHAN_TREN_SINH_BUOI: '在允许的时间范围内无法排满所需的课次数量',
    GIO_KHONG_TON_TAI_DO_DOI_GIO: '由于夏令时调整，该时刻不存在',
    LICH_DA_CO_DIEM_DANH: '本班已有课次记录了考勤——重新生成课表会丢失数据。请逐个课次修改，而不要重新生成。',
    BUOI_DA_HUY: '该课次已被取消',
    HOC_VIEN_KHONG_THUOC_LOP: '该学员不属于本班级',
    KHONG_THUOC_LOP_NAY: '您不属于本班级',
    NGOAI_KHUNG_GIO_DIEM_DANH: '不在考勤时段内（从上课前 15 分钟开放至下课）',
    THIEU_LY_DO_VANG: '缺席必须填写原因',
    NHAN_SU_KHONG_HOP_LE: '存在无效的员工（已离职或不存在）',
    GIAO_VIEN_TRUNG_TRO_GIANG: '主讲教师不能同时担任本班的助教',
    CHUA_CHON_HINH_THUC_HOC: '尚未选择上课形式',
    HOC_PHI_AM: '学费不能为负数',
    SUC_CHUA_KHONG_HOP_LE: '容量必须大于 0',
    LOP_DA_HOAN_TAT: '该班级已完成建班，无需重复操作',
    CHUA_NHAP_HOC_PHI: '完成建班前需要先填写学费',
    CHI_XOA_DUOC_LOP_NHAP: '只能删除仍处于草稿状态的班级。已运行的班级请使用「取消班级」以保留历史记录。',
    CHUA_CHON_HOC_VIEN: '尚未选择任何学员',
    HOC_VIEN_KHONG_HOP_LE: '学员无效（已退学或不存在）',
    HOC_VIEN_DA_TRONG_LOP: '该学员已在本班级中',
    KHOA_HOC_KHONG_KHOP_LOP: '订单所属课程与本班教授的课程不一致',
    VUOT_SO_KHOA_HOC_CUA_LOP: '每个班级最多只能指定 3 门课程',
    VUOT_SUC_CHUA: '超出班级的最大容量',
    CHI_KHOA_HOC_MOI_XEP_LOP: '只有购买课程的订单才能提交分班申请',
    DA_GUI_YEU_CAU_XEP_LOP: '该订单此前已提交过分班申请',
    YEU_CAU_KHONG_HOP_LE: '分班申请无效或已被删除',
    YEU_CAU_DA_XU_LY: '该申请已被处理，请重新加载列表',
    CHUA_NHAP_LY_DO_TU_CHOI: '必须填写拒绝原因',
    PHONG_BAN_TRUNG_TEN: '该层级下已存在同名部门',
    CHUC_VU_TRUNG_TEN: '中心内已存在同名职务',
    CHUC_VU_CON_NGUOI_GIU: '该职务仍有人在任——请取消勾选「使用中」以停用，同时保留历史记录',
    CHUC_VU_KHONG_HOP_LE: '职务不存在',
    PHONG_BAN_CON_NGUOI: '该部门仍有员工——请先将他们转到其他部门再删除',
    PHONG_BAN_CON_CAP_DUOI: '该部门仍有下级部门——请自下而上删除',
    PHONG_BAN_CHU_TRINH: '无法将该部门设为其自身的下级',
    PHONG_BAN_KHONG_HOP_LE: '部门不存在',
    NGUOI_QUAN_LY_KHONG_HOP_LE: '负责人无效（已离职，或为学员）',
    HOC_VIEN_KHONG_VAO_CO_CAU: '学员不属于组织架构',
    CHUA_CHON_NHAN_SU: '尚未选择任何员工',
    LOAI_TEP_KHONG_HO_TRO: '仅支持 PDF、Word、Excel、PowerPoint、图片或压缩文件',
    LOAI_TEP_HO_SO_KHONG_HO_TRO: '员工档案仅支持 PDF、Word 或 Excel',
    VUOT_SO_TEP_HO_SO: '每份档案最多只能保存 10 个文件——请删除部分旧文件后重试。',
    TIEU_CHI_THIEU_TEN: '评价标准必须填写名称。',
    TIEU_CHI_TEN_QUA_DAI: '评价标准名称过长（最多 200 个字符）。',
    TIEU_CHI_TRUNG_TEN: '该分组中已存在同名的评价标准。',
    TIEU_CHI_NHOM_KHONG_HOP_LE: '评价标准分组无效。',
    TIEU_CHI_DA_CHAM_KHONG_DOI_NHOM: '该标准已被用于评分，因此无法更改分组——更改分组会使所有已评分周期的数据失真。请停用它，并在另一分组中新建一条标准。',
    TIEU_CHI_KHONG_THUOC_NHOM: '存在不属于销售组的评价标准。',
    DIEM_TIEU_CHI_KHONG_HOP_LE: '分数必须在 1 到 5 之间。',
    KY_DANH_GIA_KHONG_HOP_LE: '评价周期的格式必须为 yyyy-MM，例如 2026-09。',
    KHONG_PHAI_NHAN_VIEN_KINH_DOANH: '只能为销售人员评分。',
    TEN_TEP_KHONG_HOP_LE: '文件名无效——请至少输入一个字符。',
    TEP_QUA_LON: '文件过大，最大 20 MB',
    TEP_RONG: '文件为空',
    LOAI_ANH_KHONG_HO_TRO: '仅支持 JPG、PNG、WebP 或 GIF 图片',
    ANH_QUA_LON: '图片过大，最大 5 MB',
    ANH_RONG: '图片文件为空',
    DANG_NHAP_THAT_BAI: '中心代码、用户名或密码不正确',
    TAI_KHOAN_BI_VO_HIEU_HOA: '账号已被停用',
    TAI_KHOAN_BI_KHOA_TAM: '密码错误次数过多。账号已被暂时锁定，请几分钟后重试，或使用「忘记密码」。',
    PHAI_DOI_MAT_KHAU: '您需要先修改密码才能继续',
    MAT_KHAU_CU_KHONG_DUNG: '当前密码不正确',
    TOKEN_DAT_LAI_KHONG_HOP_LE: '重置码无效或已过期',
    PHIEN_DA_BI_DAY_RA: '该账号刚刚在其他地方登录，因此您的会话已结束。如果不是您本人操作，请重新登录并修改密码。',
    CHUA_XAC_THUC: '您需要先登录',
    KHONG_DU_QUYEN: '您没有执行该操作的权限',
    TOKEN_THIEU_TENANT: '登录会话无效，请重新登录',
    KHONG_TIM_THAY: '未找到数据',
    DU_LIEU_KHONG_HOP_LE: '输入的数据不合法',
    TRUNG_TAM_PHAI_CON_NGUOI_PHAN_QUYEN: '中心必须至少保留一位拥有「权限管理」权限的人员。请先将该权限授予其他人，然后重试。',
    KHONG_TU_KHOA_TAI_KHOAN_CHINH_MINH: '无法锁定自己当前登录的账号。请取消勾选后重试。',
    QUA_NHIEU_YEU_CAU: '您的操作过于频繁。请稍候再试。',
    LOI_HE_THONG: '发生错误，请重试',
    USERNAME_DA_TON_TAI: '该用户名在本中心中已存在',
    QUYEN_KHONG_HOP_LE: '权限组无效',
    QUYEN_DANG_DUOC_GAN: '无法删除：该权限组正被分配给账号',
    KHONG_TU_XOA_TAI_KHOAN_CUA_MINH: '无法删除自己的账号',
    KHONG_TU_VO_HIEU_HOA_MINH: '无法停用自己的账号',
    CHUC_NANG_KHONG_HOP_LE: '功能无效',
    MAT_KHAU_QUA_NGAN: '密码至少需要 12 个字符',
    MAT_KHAU_QUA_DAI: '密码过长（最多 128 个字符）',
    MAT_KHAU_MOI_TRUNG_CU: '新密码必须与当前密码不同',
    USERNAME_KY_TU_KHONG_HOP_LE: '用户名只能包含字母、数字以及 . _ -',
    ID_KHONG_KHOP: '数据不匹配',
    NGUOI_DUOC_CHAM_KHONG_DUNG_LOP: '被评分的人员并未在本课次授课。请刷新页面后重试。',
    TRANG_THAI_KHONG_HOP_LE: '课次状态无效。',
    BUOI_HOC_DA_KHOA: '该课次已确认，因此无法修改、取消或删除。已确认课次的考勤是出勤情况的凭证。',
    BUOI_HOC_DA_CO_DIEM_DANH: '该课次已有考勤记录。请取消课次而不要删除，以保留数据。',
    BUOI_HOC_DA_CO_NHAN_XET: '该课次已有学员评价。请取消课次而不要删除，以保留这些反馈。',
    BUOI_HOC_TRUNG_GIO: '有课次与现有课表时间冲突。请选择最后一个课次之后的开始日期。',
    NGUOI_DUNG_KHONG_HOP_LE: '用户无效',
    KHONG_PHAI_NHAN_SU: '「员工」页面只管理员工、教师和助教。学员在 LMS 的「学员」页面中管理。',
    KHONG_PHAI_HOC_VIEN: '「学员」页面只管理学员。员工、教师和助教在 HRM 的「员工」页面中管理。',
    NGUOI_DUNG_DA_CO_TAI_KHOAN: '此人已有账号。每人只能拥有一个登录账号。',
    NGUOI_DUNG_DANG_CO_DU_LIEU: '无法删除：此人仍有班级、考勤或学费数据。请标记为「已离职」而不是删除，以保留数据。',
    SO_TIEN_PHAI_DUONG: '金额必须大于 0',
  },
}

export default zh
