// <auto-generated />
using System;
using GiapTech.SoccerRoom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiapTech.SoccerRoom.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816063558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.CauThu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ho_ten");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<DateOnly?>("NgayThamGia")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tham_gia");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_cau_thu");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cau_thu_tenant_id");

                    b.ToTable("CAU_THU", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DanhGiaCauThu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CauThuId")
                        .HasColumnType("uuid")
                        .HasColumnName("cau_thu_id");

                    b.Property<string>("ChiSoKyNang")
                        .HasColumnType("jsonb")
                        .HasColumnName("chi_so_ky_nang");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("SoBanCuuThua")
                        .HasColumnType("integer")
                        .HasColumnName("so_ban_cuu_thua");

                    b.Property<int>("SoBanGhiDuoc")
                        .HasColumnType("integer")
                        .HasColumnName("so_ban_ghi_duoc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TranDauId")
                        .HasColumnType("uuid")
                        .HasColumnName("tran_dau_id");

                    b.HasKey("Id")
                        .HasName("pk_danhgia_cauthu");

                    b.HasIndex("CauThuId")
                        .HasDatabaseName("ix_danhgia_cauthu_cau_thu_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_danhgia_cauthu_tenant_id");

                    b.HasIndex("TranDauId", "CauThuId")
                        .IsUnique()
                        .HasDatabaseName("ix_danhgia_cauthu_tran_dau_id_cau_thu_id");

                    b.ToTable("DANHGIA_CAUTHU", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DoiHinhTranDau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CauThuId")
                        .HasColumnType("uuid")
                        .HasColumnName("cau_thu_id");

                    b.Property<bool>("LaDuBi")
                        .HasColumnType("boolean")
                        .HasColumnName("la_du_bi");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TranDauId")
                        .HasColumnType("uuid")
                        .HasColumnName("tran_dau_id");

                    b.Property<string>("ViTri")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vi_tri");

                    b.HasKey("Id")
                        .HasName("pk_doihinh_trandau");

                    b.HasIndex("CauThuId")
                        .HasDatabaseName("ix_doihinh_trandau_cau_thu_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_doihinh_trandau_tenant_id");

                    b.HasIndex("TranDauId", "CauThuId")
                        .IsUnique()
                        .HasDatabaseName("ix_doihinh_trandau_tran_dau_id_cau_thu_id");

                    b.ToTable("DOIHINH_TRANDAU", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DoiThu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("LienHe")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lien_he");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenDoi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_doi");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_doi_thu");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_doi_thu_tenant_id");

                    b.ToTable("DOI_THU", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DongGopQuy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CauThuId")
                        .HasColumnType("uuid")
                        .HasColumnName("cau_thu_id");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset?>("NgayDong")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_dong");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("QuyId")
                        .HasColumnType("uuid")
                        .HasColumnName("quy_id");

                    b.Property<decimal>("SoTienCanDong")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("so_tien_can_dong");

                    b.Property<decimal>("SoTienDaDong")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("so_tien_da_dong");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_donggop_quy");

                    b.HasIndex("CauThuId")
                        .HasDatabaseName("ix_donggop_quy_cau_thu_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_donggop_quy_tenant_id");

                    b.HasIndex("QuyId", "CauThuId")
                        .IsUnique()
                        .HasDatabaseName("ix_donggop_quy_quy_id_cau_thu_id");

                    b.ToTable("DONGGOP_QUY", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.LoiMoiDoiThu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DoiThuId")
                        .HasColumnType("uuid")
                        .HasColumnName("doi_thu_id");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ThoiGianDeXuat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_gian_de_xuat");

                    b.Property<Guid?>("TranDauId")
                        .HasColumnType("uuid")
                        .HasColumnName("tran_dau_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_loi_moi_doi_thu");

                    b.HasIndex("DoiThuId")
                        .HasDatabaseName("ix_loi_moi_doi_thu_doi_thu_id");

                    b.HasIndex("TenantId", "TrangThai")
                        .HasDatabaseName("ix_loi_moi_doi_thu_tenant_id_trang_thai");

                    b.ToTable("LOI_MOI_DOI_THU", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CauThuId")
                        .HasColumnType("uuid")
                        .HasColumnName("cau_thu_id");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PhaiDoiMatKhau")
                        .HasColumnType("boolean")
                        .HasColumnName("phai_doi_mat_khau");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_nguoi_dung");

                    b.HasIndex("CauThuId")
                        .HasDatabaseName("ix_nguoi_dung_cau_thu_id");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_nguoi_dung_tenant_id_username");

                    b.ToTable("NGUOI_DUNG", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.NguoiDungQuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quyen_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_nguoidung_quyen");

                    b.HasIndex("QuyenId")
                        .HasDatabaseName("ix_nguoidung_quyen_quyen_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_nguoidung_quyen_tenant_id");

                    b.HasIndex("NguoiDungId", "QuyenId")
                        .IsUnique()
                        .HasDatabaseName("ix_nguoidung_quyen_nguoi_dung_id_quyen_id");

                    b.ToTable("NGUOIDUNG_QUYEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.Quy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenQuy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_quy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("ThoiHan")
                        .HasColumnType("date")
                        .HasColumnName("thoi_han");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_quy");

                    b.HasIndex("TenantId", "TrangThai")
                        .HasDatabaseName("ix_quy_tenant_id_trang_thai");

                    b.ToTable("QUY", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.Quyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_quyen");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quyen");

                    b.HasIndex("TenantId", "TenQuyen")
                        .IsUnique()
                        .HasDatabaseName("ix_quyen_tenant_id_ten_quyen");

                    b.ToTable("QUYEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.QuyenChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("HanhDong")
                        .HasColumnType("integer")
                        .HasColumnName("hanh_dong");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quyen_id");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_chuc_nang");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quyen_chuc_nang");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_quyen_chuc_nang_tenant_id");

                    b.HasIndex("QuyenId", "TenChucNang", "HanhDong")
                        .IsUnique()
                        .HasDatabaseName("ix_quyen_chuc_nang_quyen_id_ten_chuc_nang_hanh_dong");

                    b.ToTable("QUYEN_CHUC_NANG", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.SoDoChienThuat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChuChienThuat")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu_chien_thuat");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("SoDoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("so_do_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TranDauId")
                        .HasColumnType("uuid")
                        .HasColumnName("tran_dau_id");

                    b.HasKey("Id")
                        .HasName("pk_sodo_chienthuat");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sodo_chienthuat_tenant_id");

                    b.HasIndex("TranDauId")
                        .IsUnique()
                        .HasDatabaseName("ix_sodo_chienthuat_tran_dau_id");

                    b.ToTable("SODO_CHIENTHUAT", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhBiaUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_bia_url");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("MaDoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ma_doi");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<DateOnly?>("NgayThanhLap")
                        .HasColumnType("date")
                        .HasColumnName("ngay_thanh_lap");

                    b.Property<string>("TenDoi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_doi");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ten_viet_tat");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("MaDoi")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_ma_doi");

                    b.ToTable("TENANT", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.TranDau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DoiThuId")
                        .HasColumnType("uuid")
                        .HasColumnName("doi_thu_id");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("KetQua")
                        .HasColumnType("integer")
                        .HasColumnName("ket_qua");

                    b.Property<string>("LinkVideo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_video");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NhanXetChung")
                        .HasColumnType("text")
                        .HasColumnName("nhan_xet_chung");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ThoiGian")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_gian");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.Property<int?>("TySoKhach")
                        .HasColumnType("integer")
                        .HasColumnName("ty_so_khach");

                    b.Property<int?>("TySoNha")
                        .HasColumnType("integer")
                        .HasColumnName("ty_so_nha");

                    b.HasKey("Id")
                        .HasName("pk_tran_dau");

                    b.HasIndex("DoiThuId")
                        .HasDatabaseName("ix_tran_dau_doi_thu_id");

                    b.HasIndex("TenantId", "ThoiGian")
                        .HasDatabaseName("ix_tran_dau_tenant_id_thoi_gian");

                    b.ToTable("TRAN_DAU", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.VoteMvp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CauThuDuocVoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cau_thu_duoc_vote_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiVoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_vote_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TranDauId")
                        .HasColumnType("uuid")
                        .HasColumnName("tran_dau_id");

                    b.HasKey("Id")
                        .HasName("pk_vote_mvp");

                    b.HasIndex("TenantId", "CauThuDuocVoteId")
                        .HasDatabaseName("ix_vote_mvp_tenant_id_cau_thu_duoc_vote_id");

                    b.HasIndex("TranDauId", "NguoiVoteId")
                        .IsUnique()
                        .HasDatabaseName("UQ_VOTE_MVP_tran_dau_nguoi_vote");

                    b.ToTable("VOTE_MVP", (string)null);
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.CauThu", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany("CauThus")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cau_thu_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DanhGiaCauThu", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.CauThu", "CauThu")
                        .WithMany("DanhGias")
                        .HasForeignKey("CauThuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_danhgia_cauthu_cau_thu_cau_thu_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_danhgia_cauthu_tenants_tenant_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.TranDau", "TranDau")
                        .WithMany("DanhGias")
                        .HasForeignKey("TranDauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_danhgia_cauthu_tran_daus_tran_dau_id");

                    b.Navigation("CauThu");

                    b.Navigation("Tenant");

                    b.Navigation("TranDau");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DoiHinhTranDau", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.CauThu", "CauThu")
                        .WithMany("DoiHinhs")
                        .HasForeignKey("CauThuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doihinh_trandau_cau_thu_cau_thu_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doihinh_trandau_tenants_tenant_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.TranDau", "TranDau")
                        .WithMany("DoiHinhs")
                        .HasForeignKey("TranDauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doihinh_trandau_tran_daus_tran_dau_id");

                    b.Navigation("CauThu");

                    b.Navigation("Tenant");

                    b.Navigation("TranDau");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DoiThu", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doi_thu_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DongGopQuy", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.CauThu", "CauThu")
                        .WithMany("DongGops")
                        .HasForeignKey("CauThuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_donggop_quy_cau_thu_cau_thu_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Quy", "Quy")
                        .WithMany("DongGops")
                        .HasForeignKey("QuyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_donggop_quy_quys_quy_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_donggop_quy_tenants_tenant_id");

                    b.Navigation("CauThu");

                    b.Navigation("Quy");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.LoiMoiDoiThu", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.DoiThu", "DoiThu")
                        .WithMany("LoiMois")
                        .HasForeignKey("DoiThuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loi_moi_doi_thu_doi_thu_doi_thu_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loi_moi_doi_thu_tenants_tenant_id");

                    b.Navigation("DoiThu");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.CauThu", "CauThu")
                        .WithMany()
                        .HasForeignKey("CauThuId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_nguoi_dung_cau_thu_cau_thu_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoi_dung_tenants_tenant_id");

                    b.Navigation("CauThu");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.NguoiDungQuyen", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungQuyens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoidung_quyen_nguoi_dung_nguoi_dung_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Quyen", "Quyen")
                        .WithMany("NguoiDungQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoidung_quyen_quyens_quyen_id");

                    b.Navigation("NguoiDung");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.Quy", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quy_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.Quyen", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quyen_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.QuyenChucNang", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Quyen", "Quyen")
                        .WithMany("ChucNangs")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quyen_chuc_nang_quyens_quyen_id");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.SoDoChienThuat", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sodo_chienthuat_tenants_tenant_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.TranDau", "TranDau")
                        .WithOne("SoDoChienThuat")
                        .HasForeignKey("GiapTech.SoccerRoom.Domain.Entities.SoDoChienThuat", "TranDauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sodo_chienthuat_tran_daus_tran_dau_id");

                    b.Navigation("Tenant");

                    b.Navigation("TranDau");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.TranDau", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.DoiThu", "DoiThu")
                        .WithMany("TranDaus")
                        .HasForeignKey("DoiThuId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tran_dau_doi_thu_doi_thu_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tran_dau_tenant_tenant_id");

                    b.Navigation("DoiThu");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.VoteMvp", b =>
                {
                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vote_mvp_tenant_tenant_id");

                    b.HasOne("GiapTech.SoccerRoom.Domain.Entities.TranDau", "TranDau")
                        .WithMany("Votes")
                        .HasForeignKey("TranDauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vote_mvp_tran_dau_tran_dau_id");

                    b.Navigation("Tenant");

                    b.Navigation("TranDau");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.CauThu", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DoiHinhs");

                    b.Navigation("DongGops");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.DoiThu", b =>
                {
                    b.Navigation("LoiMois");

                    b.Navigation("TranDaus");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("NguoiDungQuyens");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.Quy", b =>
                {
                    b.Navigation("DongGops");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.Quyen", b =>
                {
                    b.Navigation("ChucNangs");

                    b.Navigation("NguoiDungQuyens");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("CauThus");

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("GiapTech.SoccerRoom.Domain.Entities.TranDau", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DoiHinhs");

                    b.Navigation("SoDoChienThuat");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
