// <auto-generated />
using System;
using GiapTech.LangCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiapTech.LangCenter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905075638_ThemHocPhi")]
    partial class ThemHocPhi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiKiemTra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DongLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dong_luc");

                    b.Property<int>("Loai")
                        .HasColumnType("integer")
                        .HasColumnName("loai");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_hoc_id");

                    b.Property<DateTimeOffset?>("MoLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mo_luc");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_tao_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("ThangDiem")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("thang_diem");

                    b.Property<int?>("ThoiLuongPhut")
                        .HasColumnType("integer")
                        .HasColumnName("thoi_luong_phut");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tieu_de");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_bai_kiem_tra");

                    b.HasIndex("LopHocId")
                        .HasDatabaseName("ix_bai_kiem_tra_lop_hoc_id");

                    b.HasIndex("NguoiTaoId")
                        .HasDatabaseName("ix_bai_kiem_tra_nguoi_tao_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bai_kiem_tra_tenant_id");

                    b.ToTable("BAI_KIEM_TRA", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiLam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaiKiemTraId")
                        .HasColumnType("uuid")
                        .HasColumnName("bai_kiem_tra_id");

                    b.Property<decimal?>("Diem")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("diem");

                    b.Property<DateTimeOffset?>("HanNopRieng")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("han_nop_rieng");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoc_vien_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiChamId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_cham_id");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("nhan_xet");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ThoiDiemCham")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_diem_cham");

                    b.Property<DateTimeOffset?>("ThoiDiemNop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_diem_nop");

                    b.HasKey("Id")
                        .HasName("pk_bai_lam");

                    b.HasIndex("HocVienId")
                        .HasDatabaseName("ix_bai_lam_hoc_vien_id");

                    b.HasIndex("NguoiChamId")
                        .HasDatabaseName("ix_bai_lam_nguoi_cham_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bai_lam_tenant_id");

                    b.HasIndex("BaiKiemTraId", "HocVienId")
                        .IsUnique()
                        .HasDatabaseName("ix_bai_lam_bai_kiem_tra_id_hoc_vien_id");

                    b.ToTable("BAI_LAM", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiNop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaiTapId")
                        .HasColumnType("uuid")
                        .HasColumnName("bai_tap_id");

                    b.Property<decimal?>("Diem")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("diem");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoc_vien_id");

                    b.Property<int>("LanNop")
                        .HasColumnType("integer")
                        .HasColumnName("lan_nop");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiChamId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_cham_id");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("nhan_xet");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("noi_dung");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ThoiDiemCham")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_diem_cham");

                    b.Property<DateTimeOffset>("ThoiDiemNop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_diem_nop");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_bai_nop");

                    b.HasIndex("HocVienId")
                        .HasDatabaseName("ix_bai_nop_hoc_vien_id");

                    b.HasIndex("NguoiChamId")
                        .HasDatabaseName("ix_bai_nop_nguoi_cham_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bai_nop_tenant_id");

                    b.HasIndex("BaiTapId", "HocVienId", "LanNop")
                        .IsUnique()
                        .HasDatabaseName("ix_bai_nop_bai_tap_id_hoc_vien_id_lan_nop");

                    b.ToTable("BAI_NOP", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiTap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuoiHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("buoi_hoc_id");

                    b.Property<DateTimeOffset?>("HanNop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("han_nop");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_tao_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tieu_de");

                    b.HasKey("Id")
                        .HasName("pk_bai_tap");

                    b.HasIndex("BuoiHocId")
                        .HasDatabaseName("ix_bai_tap_buoi_hoc_id");

                    b.HasIndex("NguoiTaoId")
                        .HasDatabaseName("ix_bai_tap_nguoi_tao_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bai_tap_tenant_id");

                    b.ToTable("BAI_TAP", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BuoiHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BatDau")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bat_dau");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("GiaoVienId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_vien_id");

                    b.Property<DateTimeOffset>("KetThuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ket_thuc");

                    b.Property<bool>("LaHocBu")
                        .HasColumnType("boolean")
                        .HasColumnName("la_hoc_bu");

                    b.Property<string>("LinkHoc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_hoc");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_hoc_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phong_hoc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer")
                        .HasColumnName("thu_tu");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_buoi_hoc");

                    b.HasIndex("GiaoVienId", "BatDau")
                        .HasDatabaseName("ix_buoi_hoc_giao_vien_id_bat_dau");

                    b.HasIndex("LopHocId", "ThuTu")
                        .IsUnique()
                        .HasDatabaseName("ix_buoi_hoc_lop_hoc_id_thu_tu");

                    b.HasIndex("TenantId", "BatDau")
                        .HasDatabaseName("ix_buoi_hoc_tenant_id_bat_dau");

                    b.ToTable("BUOI_HOC", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.DiemDanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuoiHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("buoi_hoc_id");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoc_vien_id");

                    b.Property<string>("LyDoVang")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ly_do_vang");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiXacNhanId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_xac_nhan_id");

                    b.Property<int>("NguonGhiNhan")
                        .HasColumnType("integer")
                        .HasColumnName("nguon_ghi_nhan");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ThoiDiemTuCheckIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_diem_tu_check_in");

                    b.Property<DateTimeOffset?>("ThoiDiemXacNhan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_diem_xac_nhan");

                    b.Property<int>("TrangThaiChinhThuc")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai_chinh_thuc");

                    b.Property<int?>("TrangThaiTuKhai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai_tu_khai");

                    b.HasKey("Id")
                        .HasName("pk_diem_danh");

                    b.HasIndex("HocVienId")
                        .HasDatabaseName("ix_diem_danh_hoc_vien_id");

                    b.HasIndex("NguoiXacNhanId")
                        .HasDatabaseName("ix_diem_danh_nguoi_xac_nhan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_diem_danh_tenant_id");

                    b.HasIndex("BuoiHocId", "HocVienId")
                        .IsUnique()
                        .HasDatabaseName("ix_diem_danh_buoi_hoc_id_hoc_vien_id");

                    b.ToTable("DIEM_DANH", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.KhoanThuHocPhi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoc_vien_id");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_hoc_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<DateTimeOffset>("NgayThu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_thu");

                    b.Property<Guid?>("NguoiThuId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_thu_id");

                    b.Property<int>("PhuongThuc")
                        .HasColumnType("integer")
                        .HasColumnName("phuong_thuc");

                    b.Property<string>("SoPhieu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("so_phieu");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("so_tien");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_khoan_thu_hoc_phi");

                    b.HasIndex("HocVienId")
                        .HasDatabaseName("ix_khoan_thu_hoc_phi_hoc_vien_id");

                    b.HasIndex("NguoiThuId")
                        .HasDatabaseName("ix_khoan_thu_hoc_phi_nguoi_thu_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_khoan_thu_hoc_phi_tenant_id");

                    b.HasIndex("LopHocId", "HocVienId")
                        .HasDatabaseName("ix_khoan_thu_hoc_phi_lop_hoc_id_hoc_vien_id");

                    b.ToTable("KHOAN_THU_HOC_PHI", null, t =>
                        {
                            t.HasCheckConstraint("ck_khoan_thu_so_tien_duong", "so_tien > 0");
                        });
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.LopHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoVienChinhId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_vien_chinh_id");

                    b.Property<int>("HinhThuc")
                        .HasColumnType("integer")
                        .HasColumnName("hinh_thuc");

                    b.Property<decimal?>("HocPhi")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("hoc_phi");

                    b.Property<string>("LinkHoc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_hoc");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset?>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<DateTimeOffset?>("NgayKhaiGiang")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_khai_giang");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_tao_id");

                    b.Property<Guid?>("NhanBanTuLopId")
                        .HasColumnType("uuid")
                        .HasColumnName("nhan_ban_tu_lop_id");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phong_hoc");

                    b.Property<int?>("SucChuaToiDa")
                        .HasColumnType("integer")
                        .HasColumnName("suc_chua_toi_da");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_lop_hoc");

                    b.HasIndex("GiaoVienChinhId")
                        .HasDatabaseName("ix_lop_hoc_giao_vien_chinh_id");

                    b.HasIndex("NguoiTaoId")
                        .HasDatabaseName("ix_lop_hoc_nguoi_tao_id");

                    b.HasIndex("NhanBanTuLopId")
                        .HasDatabaseName("ix_lop_hoc_nhan_ban_tu_lop_id");

                    b.HasIndex("TenantId", "Ten")
                        .IsUnique()
                        .HasDatabaseName("ix_lop_hoc_tenant_id_ten")
                        .HasFilter("trang_thai <> 0");

                    b.HasIndex("TenantId", "TrangThai")
                        .HasDatabaseName("ix_lop_hoc_tenant_id_trang_thai");

                    b.ToTable("LOP_HOC", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.LopHocHocVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ghi_chu");

                    b.Property<decimal>("HocPhiApDung")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("hoc_phi_ap_dung");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoc_vien_id");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_hoc_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset?>("NgayRoiLop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_roi_lop");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<DateTimeOffset>("NgayVaoLop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_vao_lop");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_lop_hoc_hoc_vien");

                    b.HasIndex("HocVienId")
                        .HasDatabaseName("ix_lop_hoc_hoc_vien_hoc_vien_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_lop_hoc_hoc_vien_tenant_id");

                    b.HasIndex("LopHocId", "HocVienId")
                        .IsUnique()
                        .HasDatabaseName("ix_lop_hoc_hoc_vien_lop_hoc_id_hoc_vien_id");

                    b.ToTable("LOP_HOC_HOC_VIEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.LopHocTroGiang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_hoc_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TroGiangId")
                        .HasColumnType("uuid")
                        .HasColumnName("tro_giang_id");

                    b.HasKey("Id")
                        .HasName("pk_lop_hoc_tro_giang");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_lop_hoc_tro_giang_tenant_id");

                    b.HasIndex("TroGiangId")
                        .HasDatabaseName("ix_lop_hoc_tro_giang_tro_giang_id");

                    b.HasIndex("LopHocId", "TroGiangId")
                        .IsUnique()
                        .HasDatabaseName("ix_lop_hoc_tro_giang_lop_hoc_id_tro_giang_id");

                    b.ToTable("LOP_HOC_TRO_GIANG", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_dai_dien_url");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ho_ten");

                    b.Property<int>("LoaiNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("loai_nguoi_dung");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset?>("NgaySinh")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PhaiDoiMatKhau")
                        .HasColumnType("boolean")
                        .HasColumnName("phai_doi_mat_khau");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_nguoi_dung");

                    b.HasIndex("TenantId", "LoaiNguoiDung")
                        .HasDatabaseName("ix_nguoi_dung_tenant_id_loai_nguoi_dung");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_nguoi_dung_tenant_id_username");

                    b.ToTable("NGUOI_DUNG", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.NguoiDungQuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quyen_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_nguoidung_quyen");

                    b.HasIndex("QuyenId")
                        .HasDatabaseName("ix_nguoidung_quyen_quyen_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_nguoidung_quyen_tenant_id");

                    b.HasIndex("NguoiDungId", "QuyenId")
                        .IsUnique()
                        .HasDatabaseName("ix_nguoidung_quyen_nguoi_dung_id_quyen_id");

                    b.ToTable("NGUOIDUNG_QUYEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.Quyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_quyen");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quyen");

                    b.HasIndex("TenantId", "TenQuyen")
                        .IsUnique()
                        .HasDatabaseName("ix_quyen_tenant_id_ten_quyen");

                    b.ToTable("QUYEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.QuyenChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("HanhDong")
                        .HasColumnType("integer")
                        .HasColumnName("hanh_dong");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quyen_id");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_chuc_nang");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quyen_chuc_nang");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_quyen_chuc_nang_tenant_id");

                    b.HasIndex("QuyenId", "TenChucNang", "HanhDong")
                        .IsUnique()
                        .HasDatabaseName("ix_quyen_chuc_nang_quyen_id_ten_chuc_nang_hanh_dong");

                    b.ToTable("QUYEN_CHUC_NANG", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("HetHan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("het_han");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ThuHoiLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thu_hoi_luc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("NguoiDungId", "ThuHoiLuc")
                        .HasDatabaseName("ix_refresh_token_nguoi_dung_id_thu_hoi_luc");

                    b.ToTable("REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TaiLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Loai")
                        .HasColumnType("integer")
                        .HasColumnName("loai");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiTaiLenId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_tai_len_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tieu_de");

                    b.HasKey("Id")
                        .HasName("pk_tai_lieu");

                    b.HasIndex("NguoiTaiLenId")
                        .HasDatabaseName("ix_tai_lieu_nguoi_tai_len_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tai_lieu_tenant_id");

                    b.ToTable("TAI_LIEU", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TaiLieuLopHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_hoc_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("TaiLieuId")
                        .HasColumnType("uuid")
                        .HasColumnName("tai_lieu_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tai_lieu_lop_hoc");

                    b.HasIndex("LopHocId")
                        .HasDatabaseName("ix_tai_lieu_lop_hoc_lop_hoc_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tai_lieu_lop_hoc_tenant_id");

                    b.HasIndex("TaiLieuId", "LopHocId")
                        .IsUnique()
                        .HasDatabaseName("ix_tai_lieu_lop_hoc_tai_lieu_id_lop_hoc_id");

                    b.ToTable("TAI_LIEU_LOP_HOC", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhBiaUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_bia_url");

                    b.Property<string>("AnhQrUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_qr_url");

                    b.Property<string>("ChuTaiKhoan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chu_tai_khoan");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("LienHe")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lien_he");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("MaTrungTam")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("ma_trung_tam")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("MuiGio")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mui_gio");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("SoNgayCanhBaoNoHocPhi")
                        .HasColumnType("integer")
                        .HasColumnName("so_ngay_canh_bao_no_hoc_phi");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<string>("TenTrungTam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_trung_tam");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ten_viet_tat");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("MaTrungTam")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_ma_trung_tam");

                    b.ToTable("TENANT", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TepDinhKem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BaiKiemTraId")
                        .HasColumnType("uuid")
                        .HasColumnName("bai_kiem_tra_id");

                    b.Property<Guid?>("BaiLamId")
                        .HasColumnType("uuid")
                        .HasColumnName("bai_lam_id");

                    b.Property<Guid?>("BaiNopId")
                        .HasColumnType("uuid")
                        .HasColumnName("bai_nop_id");

                    b.Property<Guid?>("BaiTapId")
                        .HasColumnType("uuid")
                        .HasColumnName("bai_tap_id");

                    b.Property<string>("KhoaLuuTru")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("khoa_luu_tru");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("bigint")
                        .HasColumnName("kich_thuoc");

                    b.Property<string>("LoaiNoiDung")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("loai_noi_dung");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiTaiLenId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_tai_len_id");

                    b.Property<Guid?>("TaiLieuId")
                        .HasColumnType("uuid")
                        .HasColumnName("tai_lieu_id");

                    b.Property<string>("TenGoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_goc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tep_dinh_kem");

                    b.HasIndex("BaiKiemTraId")
                        .HasDatabaseName("ix_tep_dinh_kem_bai_kiem_tra_id");

                    b.HasIndex("BaiLamId")
                        .HasDatabaseName("ix_tep_dinh_kem_bai_lam_id");

                    b.HasIndex("BaiNopId")
                        .HasDatabaseName("ix_tep_dinh_kem_bai_nop_id");

                    b.HasIndex("BaiTapId")
                        .HasDatabaseName("ix_tep_dinh_kem_bai_tap_id");

                    b.HasIndex("KhoaLuuTru")
                        .HasDatabaseName("ix_tep_dinh_kem_khoa_luu_tru");

                    b.HasIndex("NguoiTaiLenId")
                        .HasDatabaseName("ix_tep_dinh_kem_nguoi_tai_len_id");

                    b.HasIndex("TaiLieuId")
                        .HasDatabaseName("ix_tep_dinh_kem_tai_lieu_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tep_dinh_kem_tenant_id");

                    b.ToTable("TEP_DINH_KEM", null, t =>
                        {
                            t.HasCheckConstraint("ck_tep_dinh_kem_dung_mot_chu", "(CASE WHEN bai_tap_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN bai_nop_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN bai_kiem_tra_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN bai_lam_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN tai_lieu_id IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TokenDatLaiMatKhau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DaDungLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("da_dung_luc");

                    b.Property<DateTimeOffset>("HetHan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("het_han");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_token_datlai_matkhau");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_token_datlai_matkhau_token_hash");

                    b.HasIndex("NguoiDungId", "DaDungLuc")
                        .HasDatabaseName("ix_token_datlai_matkhau_nguoi_dung_id_da_dung_luc");

                    b.ToTable("TOKEN_DATLAI_MATKHAU", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiKiemTra", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bai_kiem_tra_lop_hocs_lop_hoc_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bai_kiem_tra_nguoi_dungs_nguoi_tao_id");

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiLam", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.BaiKiemTra", "BaiKiemTra")
                        .WithMany("BaiLams")
                        .HasForeignKey("BaiKiemTraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bai_lam_bai_kiem_tra_bai_kiem_tra_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bai_lam_nguoi_dungs_hoc_vien_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiCham")
                        .WithMany()
                        .HasForeignKey("NguoiChamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bai_lam_nguoi_dungs_nguoi_cham_id");

                    b.Navigation("BaiKiemTra");

                    b.Navigation("HocVien");

                    b.Navigation("NguoiCham");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiNop", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.BaiTap", "BaiTap")
                        .WithMany("BaiNops")
                        .HasForeignKey("BaiTapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bai_nop_bai_taps_bai_tap_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bai_nop_nguoi_dungs_hoc_vien_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiCham")
                        .WithMany()
                        .HasForeignKey("NguoiChamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bai_nop_nguoi_dungs_nguoi_cham_id");

                    b.Navigation("BaiTap");

                    b.Navigation("HocVien");

                    b.Navigation("NguoiCham");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiTap", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.BuoiHoc", "BuoiHoc")
                        .WithMany()
                        .HasForeignKey("BuoiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bai_tap_buoi_hocs_buoi_hoc_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bai_tap_nguoi_dungs_nguoi_tao_id");

                    b.Navigation("BuoiHoc");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BuoiHoc", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_buoi_hoc_nguoi_dungs_giao_vien_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_buoi_hoc_lop_hocs_lop_hoc_id");

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.DiemDanh", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.BuoiHoc", "BuoiHoc")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("BuoiHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_diem_danh_buoi_hoc_buoi_hoc_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_diem_danh_nguoi_dungs_hoc_vien_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiXacNhan")
                        .WithMany()
                        .HasForeignKey("NguoiXacNhanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_diem_danh_nguoi_dungs_nguoi_xac_nhan_id");

                    b.Navigation("BuoiHoc");

                    b.Navigation("HocVien");

                    b.Navigation("NguoiXacNhan");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.KhoanThuHocPhi", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_khoan_thu_hoc_phi_nguoi_dungs_hoc_vien_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_khoan_thu_hoc_phi_lop_hocs_lop_hoc_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiThu")
                        .WithMany()
                        .HasForeignKey("NguoiThuId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_khoan_thu_hoc_phi_nguoi_dungs_nguoi_thu_id");

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiThu");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.LopHoc", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "GiaoVienChinh")
                        .WithMany()
                        .HasForeignKey("GiaoVienChinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_nguoi_dungs_giao_vien_chinh_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lop_hoc_nguoi_dungs_nguoi_tao_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.LopHoc", "NhanBanTuLop")
                        .WithMany()
                        .HasForeignKey("NhanBanTuLopId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lop_hoc_lop_hoc_nhan_ban_tu_lop_id");

                    b.Navigation("GiaoVienChinh");

                    b.Navigation("NguoiTao");

                    b.Navigation("NhanBanTuLop");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.LopHocHocVien", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_hoc_vien_nguoi_dungs_hoc_vien_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany("HocViens")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_hoc_vien_lop_hoc_lop_hoc_id");

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.LopHocTroGiang", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany("TroGiangs")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_tro_giang_lop_hoc_lop_hoc_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "TroGiang")
                        .WithMany()
                        .HasForeignKey("TroGiangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_tro_giang_nguoi_dungs_tro_giang_id");

                    b.Navigation("LopHoc");

                    b.Navigation("TroGiang");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoi_dung_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.NguoiDungQuyen", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungQuyens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoidung_quyen_nguoi_dung_nguoi_dung_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.Quyen", "Quyen")
                        .WithMany("NguoiDungQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoidung_quyen_quyens_quyen_id");

                    b.Navigation("NguoiDung");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.Quyen", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quyen_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.QuyenChucNang", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.Quyen", "Quyen")
                        .WithMany("ChucNangs")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quyen_chuc_nang_quyens_quyen_id");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_nguoi_dung_nguoi_dung_id");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TaiLieu", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiTaiLen")
                        .WithMany()
                        .HasForeignKey("NguoiTaiLenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tai_lieu_nguoi_dung_nguoi_tai_len_id");

                    b.Navigation("NguoiTaiLen");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TaiLieuLopHoc", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tai_lieu_lop_hoc_lop_hoc_lop_hoc_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.TaiLieu", "TaiLieu")
                        .WithMany("LopHocs")
                        .HasForeignKey("TaiLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tai_lieu_lop_hoc_tai_lieu_tai_lieu_id");

                    b.Navigation("LopHoc");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TepDinhKem", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.BaiKiemTra", "BaiKiemTra")
                        .WithMany("Teps")
                        .HasForeignKey("BaiKiemTraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tep_dinh_kem_bai_kiem_tra_bai_kiem_tra_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.BaiLam", "BaiLam")
                        .WithMany("Teps")
                        .HasForeignKey("BaiLamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tep_dinh_kem_bai_lam_bai_lam_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.BaiNop", "BaiNop")
                        .WithMany("Teps")
                        .HasForeignKey("BaiNopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tep_dinh_kem_bai_nop_bai_nop_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.BaiTap", "BaiTap")
                        .WithMany("Teps")
                        .HasForeignKey("BaiTapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tep_dinh_kem_bai_tap_bai_tap_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiTaiLen")
                        .WithMany()
                        .HasForeignKey("NguoiTaiLenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tep_dinh_kem_nguoi_dung_nguoi_tai_len_id");

                    b.HasOne("GiapTech.LangCenter.Domain.Entities.TaiLieu", "TaiLieu")
                        .WithMany("Teps")
                        .HasForeignKey("TaiLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tep_dinh_kem_tai_lieu_tai_lieu_id");

                    b.Navigation("BaiKiemTra");

                    b.Navigation("BaiLam");

                    b.Navigation("BaiNop");

                    b.Navigation("BaiTap");

                    b.Navigation("NguoiTaiLen");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TokenDatLaiMatKhau", b =>
                {
                    b.HasOne("GiapTech.LangCenter.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_datlai_matkhau_nguoi_dung_nguoi_dung_id");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiKiemTra", b =>
                {
                    b.Navigation("BaiLams");

                    b.Navigation("Teps");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiLam", b =>
                {
                    b.Navigation("Teps");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiNop", b =>
                {
                    b.Navigation("Teps");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BaiTap", b =>
                {
                    b.Navigation("BaiNops");

                    b.Navigation("Teps");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.BuoiHoc", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.LopHoc", b =>
                {
                    b.Navigation("HocViens");

                    b.Navigation("TroGiangs");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("NguoiDungQuyens");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.Quyen", b =>
                {
                    b.Navigation("ChucNangs");

                    b.Navigation("NguoiDungQuyens");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.TaiLieu", b =>
                {
                    b.Navigation("LopHocs");

                    b.Navigation("Teps");
                });

            modelBuilder.Entity("GiapTech.LangCenter.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
