// <auto-generated />
using System;
using GiapTech.LangCenter.LMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiapTech.LangCenter.LMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905033930_ThemLopHoc")]
    partial class ThemLopHoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.LopHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoVienChinhId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_vien_chinh_id");

                    b.Property<int>("HinhThuc")
                        .HasColumnType("integer")
                        .HasColumnName("hinh_thuc");

                    b.Property<decimal?>("HocPhi")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("hoc_phi");

                    b.Property<string>("LinkHoc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_hoc");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset?>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<DateTimeOffset?>("NgayKhaiGiang")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_khai_giang");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_tao_id");

                    b.Property<Guid?>("NhanBanTuLopId")
                        .HasColumnType("uuid")
                        .HasColumnName("nhan_ban_tu_lop_id");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phong_hoc");

                    b.Property<int?>("SucChuaToiDa")
                        .HasColumnType("integer")
                        .HasColumnName("suc_chua_toi_da");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_lop_hoc");

                    b.HasIndex("GiaoVienChinhId")
                        .HasDatabaseName("ix_lop_hoc_giao_vien_chinh_id");

                    b.HasIndex("NguoiTaoId")
                        .HasDatabaseName("ix_lop_hoc_nguoi_tao_id");

                    b.HasIndex("NhanBanTuLopId")
                        .HasDatabaseName("ix_lop_hoc_nhan_ban_tu_lop_id");

                    b.HasIndex("TenantId", "Ten")
                        .IsUnique()
                        .HasDatabaseName("ix_lop_hoc_tenant_id_ten")
                        .HasFilter("trang_thai <> 0");

                    b.HasIndex("TenantId", "TrangThai")
                        .HasDatabaseName("ix_lop_hoc_tenant_id_trang_thai");

                    b.ToTable("LOP_HOC", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.LopHocHocVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ghi_chu");

                    b.Property<decimal>("HocPhiApDung")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("hoc_phi_ap_dung");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoc_vien_id");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_hoc_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset?>("NgayRoiLop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_roi_lop");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<DateTimeOffset>("NgayVaoLop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_vao_lop");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_lop_hoc_hoc_vien");

                    b.HasIndex("HocVienId")
                        .HasDatabaseName("ix_lop_hoc_hoc_vien_hoc_vien_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_lop_hoc_hoc_vien_tenant_id");

                    b.HasIndex("LopHocId", "HocVienId")
                        .IsUnique()
                        .HasDatabaseName("ix_lop_hoc_hoc_vien_lop_hoc_id_hoc_vien_id");

                    b.ToTable("LOP_HOC_HOC_VIEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.LopHocTroGiang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_hoc_id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TroGiangId")
                        .HasColumnType("uuid")
                        .HasColumnName("tro_giang_id");

                    b.HasKey("Id")
                        .HasName("pk_lop_hoc_tro_giang");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_lop_hoc_tro_giang_tenant_id");

                    b.HasIndex("TroGiangId")
                        .HasDatabaseName("ix_lop_hoc_tro_giang_tro_giang_id");

                    b.HasIndex("LopHocId", "TroGiangId")
                        .IsUnique()
                        .HasDatabaseName("ix_lop_hoc_tro_giang_lop_hoc_id_tro_giang_id");

                    b.ToTable("LOP_HOC_TRO_GIANG", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_dai_dien_url");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ho_ten");

                    b.Property<int>("LoaiNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("loai_nguoi_dung");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset?>("NgaySinh")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PhaiDoiMatKhau")
                        .HasColumnType("boolean")
                        .HasColumnName("phai_doi_mat_khau");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_nguoi_dung");

                    b.HasIndex("TenantId", "LoaiNguoiDung")
                        .HasDatabaseName("ix_nguoi_dung_tenant_id_loai_nguoi_dung");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_nguoi_dung_tenant_id_username");

                    b.ToTable("NGUOI_DUNG", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDungQuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quyen_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_nguoidung_quyen");

                    b.HasIndex("QuyenId")
                        .HasDatabaseName("ix_nguoidung_quyen_quyen_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_nguoidung_quyen_tenant_id");

                    b.HasIndex("NguoiDungId", "QuyenId")
                        .IsUnique()
                        .HasDatabaseName("ix_nguoidung_quyen_nguoi_dung_id_quyen_id");

                    b.ToTable("NGUOIDUNG_QUYEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_quyen");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quyen");

                    b.HasIndex("TenantId", "TenQuyen")
                        .IsUnique()
                        .HasDatabaseName("ix_quyen_tenant_id_ten_quyen");

                    b.ToTable("QUYEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.QuyenChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("HanhDong")
                        .HasColumnType("integer")
                        .HasColumnName("hanh_dong");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quyen_id");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_chuc_nang");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quyen_chuc_nang");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_quyen_chuc_nang_tenant_id");

                    b.HasIndex("QuyenId", "TenChucNang", "HanhDong")
                        .IsUnique()
                        .HasDatabaseName("ix_quyen_chuc_nang_quyen_id_ten_chuc_nang_hanh_dong");

                    b.ToTable("QUYEN_CHUC_NANG", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("HetHan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("het_han");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ThuHoiLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thu_hoi_luc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("NguoiDungId", "ThuHoiLuc")
                        .HasDatabaseName("ix_refresh_token_nguoi_dung_id_thu_hoi_luc");

                    b.ToTable("REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhBiaUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_bia_url");

                    b.Property<string>("AnhQrUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_qr_url");

                    b.Property<string>("ChuTaiKhoan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chu_tai_khoan");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("LienHe")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lien_he");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("MaTrungTam")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("ma_trung_tam")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("MuiGio")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mui_gio");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("SoNgayCanhBaoNoHocPhi")
                        .HasColumnType("integer")
                        .HasColumnName("so_ngay_canh_bao_no_hoc_phi");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<string>("TenTrungTam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_trung_tam");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ten_viet_tat");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("MaTrungTam")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_ma_trung_tam");

                    b.ToTable("TENANT", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.TokenDatLaiMatKhau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DaDungLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("da_dung_luc");

                    b.Property<DateTimeOffset>("HetHan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("het_han");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_token_datlai_matkhau");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_token_datlai_matkhau_token_hash");

                    b.HasIndex("NguoiDungId", "DaDungLuc")
                        .HasDatabaseName("ix_token_datlai_matkhau_nguoi_dung_id_da_dung_luc");

                    b.ToTable("TOKEN_DATLAI_MATKHAU", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.LopHoc", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "GiaoVienChinh")
                        .WithMany()
                        .HasForeignKey("GiaoVienChinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_nguoi_dungs_giao_vien_chinh_id");

                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lop_hoc_nguoi_dungs_nguoi_tao_id");

                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.LopHoc", "NhanBanTuLop")
                        .WithMany()
                        .HasForeignKey("NhanBanTuLopId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lop_hoc_lop_hoc_nhan_ban_tu_lop_id");

                    b.Navigation("GiaoVienChinh");

                    b.Navigation("NguoiTao");

                    b.Navigation("NhanBanTuLop");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.LopHocHocVien", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_hoc_vien_nguoi_dungs_hoc_vien_id");

                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany("HocViens")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_hoc_vien_lop_hoc_lop_hoc_id");

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.LopHocTroGiang", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany("TroGiangs")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_tro_giang_lop_hoc_lop_hoc_id");

                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "TroGiang")
                        .WithMany()
                        .HasForeignKey("TroGiangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_tro_giang_nguoi_dungs_tro_giang_id");

                    b.Navigation("LopHoc");

                    b.Navigation("TroGiang");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoi_dung_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDungQuyen", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungQuyens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoidung_quyen_nguoi_dung_nguoi_dung_id");

                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", "Quyen")
                        .WithMany("NguoiDungQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoidung_quyen_quyens_quyen_id");

                    b.Navigation("NguoiDung");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quyen_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.QuyenChucNang", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", "Quyen")
                        .WithMany("ChucNangs")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quyen_chuc_nang_quyens_quyen_id");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_nguoi_dung_nguoi_dung_id");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.TokenDatLaiMatKhau", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_datlai_matkhau_nguoi_dung_nguoi_dung_id");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.LopHoc", b =>
                {
                    b.Navigation("HocViens");

                    b.Navigation("TroGiangs");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("NguoiDungQuyens");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", b =>
                {
                    b.Navigation("ChucNangs");

                    b.Navigation("NguoiDungQuyens");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
