// <auto-generated />
using System;
using GiapTech.LangCenter.LMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiapTech.LangCenter.LMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PhaiDoiMatKhau")
                        .HasColumnType("boolean")
                        .HasColumnName("phai_doi_mat_khau");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_nguoi_dung");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_nguoi_dung_tenant_id_username");

                    b.ToTable("NGUOI_DUNG", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDungQuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quyen_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_nguoidung_quyen");

                    b.HasIndex("QuyenId")
                        .HasDatabaseName("ix_nguoidung_quyen_quyen_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_nguoidung_quyen_tenant_id");

                    b.HasIndex("NguoiDungId", "QuyenId")
                        .IsUnique()
                        .HasDatabaseName("ix_nguoidung_quyen_nguoi_dung_id_quyen_id");

                    b.ToTable("NGUOIDUNG_QUYEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_quyen");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quyen");

                    b.HasIndex("TenantId", "TenQuyen")
                        .IsUnique()
                        .HasDatabaseName("ix_quyen_tenant_id_ten_quyen");

                    b.ToTable("QUYEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.QuyenChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("HanhDong")
                        .HasColumnType("integer")
                        .HasColumnName("hanh_dong");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quyen_id");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_chuc_nang");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quyen_chuc_nang");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_quyen_chuc_nang_tenant_id");

                    b.HasIndex("QuyenId", "TenChucNang", "HanhDong")
                        .IsUnique()
                        .HasDatabaseName("ix_quyen_chuc_nang_quyen_id_ten_chuc_nang_hanh_dong");

                    b.ToTable("QUYEN_CHUC_NANG", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("HetHan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("het_han");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ThuHoiLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thu_hoi_luc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("NguoiDungId", "ThuHoiLuc")
                        .HasDatabaseName("ix_refresh_token_nguoi_dung_id_thu_hoi_luc");

                    b.ToTable("REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhBiaUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_bia_url");

                    b.Property<string>("AnhQrUrl")
                        .HasColumnType("text")
                        .HasColumnName("anh_qr_url");

                    b.Property<string>("ChuTaiKhoan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chu_tai_khoan");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("LienHe")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lien_he");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("MaTrungTam")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("ma_trung_tam")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<string>("TenTrungTam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_trung_tam");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ten_viet_tat");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("MaTrungTam")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_ma_trung_tam");

                    b.ToTable("TENANT", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.TokenDatLaiMatKhau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DaDungLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("da_dung_luc");

                    b.Property<DateTimeOffset>("HetHan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("het_han");

                    b.Property<DateTimeOffset?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_token_datlai_matkhau");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_token_datlai_matkhau_token_hash");

                    b.HasIndex("NguoiDungId", "DaDungLuc")
                        .HasDatabaseName("ix_token_datlai_matkhau_nguoi_dung_id_da_dung_luc");

                    b.ToTable("TOKEN_DATLAI_MATKHAU", (string)null);
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoi_dung_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDungQuyen", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungQuyens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoidung_quyen_nguoi_dung_nguoi_dung_id");

                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", "Quyen")
                        .WithMany("NguoiDungQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nguoidung_quyen_quyens_quyen_id");

                    b.Navigation("NguoiDung");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quyen_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.QuyenChucNang", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", "Quyen")
                        .WithMany("ChucNangs")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quyen_chuc_nang_quyens_quyen_id");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_nguoi_dung_nguoi_dung_id");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.TokenDatLaiMatKhau", b =>
                {
                    b.HasOne("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_datlai_matkhau_nguoi_dung_nguoi_dung_id");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("NguoiDungQuyens");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Quyen", b =>
                {
                    b.Navigation("ChucNangs");

                    b.Navigation("NguoiDungQuyens");
                });

            modelBuilder.Entity("GiapTech.LangCenter.LMS.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
